// Generated by GitHub Copilot
using EventSync.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Data;

/// <summary>
/// Primary EF Core <see cref="DbContext"/> for the EventSync application.
/// </summary>
/// <remarks>
/// Applies all <c>IEntityTypeConfiguration</c> implementations from this assembly and seeds
/// the <see cref="EventTypes"/> lookup table on model creation.
/// </remarks>
public class AppDbContext : DbContext
{
    /// <summary>
    /// Initializes a new instance of <see cref="AppDbContext"/>.
    /// </summary>
    /// <param name="options">EF Core options injected by DI.</param>
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

    /// <summary>Application users.</summary>
    public DbSet<User> Users => Set<User>();

    /// <summary>Event type lookup.</summary>
    public DbSet<EventType> EventTypes => Set<EventType>();

    /// <summary>Events.</summary>
    public DbSet<Event> Events => Set<Event>();

    /// <summary>Invite links.</summary>
    public DbSet<InviteLink> InviteLinks => Set<InviteLink>();

    /// <summary>RSVP responses.</summary>
    public DbSet<Rsvp> Rsvps => Set<Rsvp>();

    /// <inheritdoc/>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);

        // Seed EventTypes lookup. Ids are stable so migrations remain deterministic.
        modelBuilder.Entity<EventType>().HasData(
            new EventType { Id = 1, Name = "Seminar", Icon = "\uD83D\uDCD6" },          // 📖 Open Book
            new EventType { Id = 2, Name = "Meeting", Icon = "\uD83D\uDCC5" },          // 📅 Calendar
            new EventType { Id = 3, Name = "Gathering", Icon = "\uD83E\uDD1D" },        // 🤝 Handshake
            new EventType { Id = 4, Name = "Wedding Anniversary", Icon = "\uD83D\uDC8D" }, // 💍 Ring
            new EventType { Id = 5, Name = "Birthday", Icon = "\uD83C\uDF82" },         // 🎂 Birthday Cake
            new EventType { Id = 6, Name = "Workshop", Icon = "\uD83D\uDEE0\uFE0F" },   // 🛠️ Hammer and Wrench
            new EventType { Id = 7, Name = "Conference", Icon = "\uD83C\uDFE2" },       // 🏢 Office Building
            new EventType { Id = 8, Name = "Other", Icon = "\u2728" },                  // ✨ Sparkles
            new EventType { Id = 9, Name = "Church Anniversary", Icon = "\u26EA" },     // ⛪ Church
            new EventType { Id = 10, Name = "Swimming Vacation", Icon = "\uD83C\uDFD6\uFE0F" }, // 🏖️ Beach with Umbrella
            new EventType { Id = 11, Name = "Family Reunion", Icon = "\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67\u200D\uD83D\uDC66" } // 👨‍👩‍👧‍👦 Family
        );

    }
}
