// Generated by GitHub Copilot
using System.Globalization;
using System.Text;
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.RSVPs.ExportRsvps;

/// <summary>
/// Query: export every RSVP for an event the current user organizes as CSV text.
/// </summary>
/// <param name="EventId">Owning event identifier.</param>
public sealed record ExportRsvpsQuery(Guid EventId) : IRequest<RsvpCsvExport>;

/// <summary>Result of a CSV export: a suggested download file name and the CSV body.</summary>
/// <param name="FileName">Suggested attachment file name (e.g. <c>rsvps-my-event-20260929.csv</c>).</param>
/// <param name="Csv">RFC 4180 CSV text (CRLF line endings, header row included).</param>
public sealed record RsvpCsvExport(string FileName, string Csv);

/// <summary>Handler for <see cref="ExportRsvpsQuery"/>.</summary>
public sealed class ExportRsvpsHandler : IRequestHandler<ExportRsvpsQuery, RsvpCsvExport>
{
    private const string HeaderRow = "Name,Email,Status,Note,RespondedAtUtc,UpdatedAtUtc";

    private readonly AppDbContext _dbContext;
    private readonly ICurrentUserService _currentUser;

    /// <summary>Initializes a new instance of <see cref="ExportRsvpsHandler"/>.</summary>
    public ExportRsvpsHandler(AppDbContext dbContext, ICurrentUserService currentUser)
    {
        _dbContext = dbContext;
        _currentUser = currentUser;
    }

    /// <inheritdoc/>
    /// <exception cref="KeyNotFoundException">Event does not exist.</exception>
    /// <exception cref="UnauthorizedAccessException">Event is owned by another user.</exception>
    public async Task<RsvpCsvExport> Handle(ExportRsvpsQuery request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var ev = await _dbContext.Events
            .AsNoTracking()
            .FirstOrDefaultAsync(e => e.Id == request.EventId, cancellationToken)
            ?? throw new KeyNotFoundException($"Event {request.EventId} not found.");

        if (ev.OrganizerId != user.Id)
        {
            throw new UnauthorizedAccessException("You do not have access to this event's RSVPs.");
        }

        var rsvps = await _dbContext.Rsvps
            .AsNoTracking()
            .Where(r => r.EventId == ev.Id)
            .OrderBy(r => r.RespondedAt)
            .Select(r => new
            {
                r.GuestName,
                r.GuestEmail,
                r.Status,
                r.Note,
                r.RespondedAt,
                r.UpdatedAt,
            })
            .ToListAsync(cancellationToken);

        var sb = new StringBuilder();
        sb.Append(HeaderRow).Append("\r\n");

        foreach (var r in rsvps)
        {
            sb.Append(CsvField(r.GuestName)).Append(',')
              .Append(CsvField(r.GuestEmail)).Append(',')
              .Append(CsvField(StatusLabel(r.Status))).Append(',')
              .Append(CsvField(r.Note)).Append(',')
              .Append(CsvField(FormatUtc(r.RespondedAt))).Append(',')
              .Append(CsvField(r.UpdatedAt.HasValue ? FormatUtc(r.UpdatedAt.Value) : null))
              .Append("\r\n");
        }

        return new RsvpCsvExport(BuildFileName(ev.Title), sb.ToString());
    }

    /// <summary>Formats a timestamp as an unambiguous UTC string.</summary>
    private static string FormatUtc(DateTime value) =>
        value.ToString("yyyy-MM-dd HH:mm:ss'Z'", CultureInfo.InvariantCulture);

    /// <summary>Maps the persisted status to a human-friendly label.</summary>
    private static string StatusLabel(RsvpStatus status) => status switch
    {
        RsvpStatus.Going => "Going",
        RsvpStatus.NotGoing => "Not Going",
        RsvpStatus.Maybe => "Maybe",
        _ => "Pending",
    };

    /// <summary>
    /// Escapes a value for a CSV cell.
    /// </summary>
    /// <remarks>
    /// Applies two protections:
    /// <list type="number">
    ///   <item>CSV-injection guard — a leading <c>=</c>, <c>+</c>, <c>-</c>, or <c>@</c> can be
    ///     executed as a formula by spreadsheet apps (Excel, Sheets). Guest-supplied names and
    ///     notes are prefixed with a single quote to neutralise this.</item>
    ///   <item>RFC 4180 quoting — a value containing a comma, double-quote, CR, or LF is wrapped
    ///     in double-quotes with any inner quotes doubled.</item>
    /// </list>
    /// </remarks>
    private static string CsvField(string? value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return string.Empty;
        }

        var sanitized = value[0] is '=' or '+' or '-' or '@'
            ? "'" + value
            : value;

        var needsQuoting = sanitized.IndexOfAny([',', '"', '\r', '\n']) >= 0;
        return needsQuoting
            ? $"\"{sanitized.Replace("\"", "\"\"")}\""
            : sanitized;
    }

    /// <summary>Builds a safe, readable download file name from the event title.</summary>
    private static string BuildFileName(string title)
    {
        var lowered = title.ToLowerInvariant();
        var chars = lowered.Select(c => char.IsLetterOrDigit(c) ? c : '-').ToArray();
        var slug = string.Join('-', new string(chars).Split('-', StringSplitOptions.RemoveEmptyEntries));

        if (slug.Length == 0)
        {
            slug = "event";
        }
        else if (slug.Length > 40)
        {
            slug = slug[..40].TrimEnd('-');
        }

        return $"rsvps-{slug}-{DateTime.UtcNow:yyyyMMdd}.csv";
    }
}
