// Generated by GitHub Copilot
import { Routes } from '@angular/router';

/**
 * Lazy-loaded child routes for the Events feature.
 *
 * Mounted under `/events` by `app.routes.ts` and protected by `authGuard`.
 * The `event-detail` route lands in Phase 3C; until then, the list is the only
 * landing page.
 */
export const EVENTS_ROUTES: Routes = [
  {
    path: '',
    loadComponent: () =>
      import('./event-list/event-list.component').then((m) => m.EventListComponent),
    title: 'My Events — EventSync',
  },
  {
    path: 'create',
    loadComponent: () =>
      import('./create-event/create-event.component').then((m) => m.CreateEventComponent),
    title: 'Create event — EventSync',
  },
  {
    path: ':id/edit',
    loadComponent: () =>
      import('./edit-event/edit-event.component').then((m) => m.EditEventComponent),
    title: 'Edit event — EventSync',
  },
  {
    path: ':id',
    loadComponent: () =>
      import('./event-detail/event-detail.component').then((m) => m.EventDetailComponent),
    title: 'Event — EventSync',
  },
];
