// Generated by GitHub Copilot
import type { Routes } from '@angular/router';

/**
 * Public, unauthenticated RSVP routes.
 *
 * Security note: these routes deliberately have NO `authGuard`. Anyone who
 * holds a valid invite token may view and submit. Server-side validation in
 * `InviteValidationService` is the sole authority on what tokens are honoured.
 */
export const PUBLIC_RSVP_ROUTES: Routes = [
  {
    path: ':token',
    loadComponent: () =>
      import('./rsvp-page/rsvp-page.component').then((m) => m.RsvpPageComponent),
    title: "You're invited \u2014 EventSync",
  },
  {
    path: ':token/confirmed',
    loadComponent: () =>
      import('./rsvp-confirmation/rsvp-confirmation.component').then(
        (m) => m.RsvpConfirmationComponent,
      ),
    title: 'RSVP confirmed \u2014 EventSync',
  },
];
