// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

/** Spinner size keyword. */
export type SpinnerSize = 'sm' | 'md' | 'lg';

/**
 * Pure-CSS spinner with an accessible status label.
 *
 * The visible label is hidden with `sr-only` so the spinner ring carries the
 * visual weight, while screen readers still hear "Loading…" via the live region.
 */
@Component({
  selector: 'app-loading-spinner',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div role="status" aria-live="polite" class="inline-flex items-center gap-2">
      <span
        aria-hidden="true"
        [class]="ringClass()"
      ></span>
      <span class="sr-only">{{ label() }}</span>
    </div>
  `,
})
export class LoadingSpinnerComponent {
  readonly size = input<SpinnerSize>('md');
  readonly label = input<string>('Loading…');

  protected readonly ringClass = computed(() => {
    const sizes: Record<SpinnerSize, string> = {
      sm: 'h-4 w-4 border-2',
      md: 'h-8 w-8 border-4',
      lg: 'h-12 w-12 border-4',
    };
    return `inline-block animate-spin rounded-full border-slate-200 border-t-indigo-600 ${sizes[this.size()]}`;
  });
}
