// Generated by GitHub Copilot
using EventSync.Api.Common.Configuration;
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.Events.Common;
using EventSync.Api.Features.InviteLinks.CreateInviteLink;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace EventSync.Api.Features.Events.GetEventById;

/// <summary>
/// Query: load a single event owned by the current user, with full detail.
/// </summary>
/// <param name="Id">Event identifier.</param>
public sealed record GetEventByIdQuery(Guid Id) : IRequest<EventDetailDto>;

/// <summary>Handler for <see cref="GetEventByIdQuery"/>.</summary>
public sealed class GetEventByIdHandler : IRequestHandler<GetEventByIdQuery, EventDetailDto>
{
    private readonly ICurrentUserService _currentUser;
    private readonly AppDbContext _dbContext;
    private readonly FrontendOptions _frontend;

    /// <summary>Initializes a new instance of <see cref="GetEventByIdHandler"/>.</summary>
    public GetEventByIdHandler(
        ICurrentUserService currentUser,
        AppDbContext dbContext,
        IOptions<FrontendOptions> frontendOptions)
    {
        _currentUser = currentUser;
        _dbContext = dbContext;
        _frontend = frontendOptions.Value;
    }

    /// <inheritdoc/>
    /// <exception cref="KeyNotFoundException">Thrown when no event matches <see cref="GetEventByIdQuery.Id"/>.</exception>
    /// <exception cref="UnauthorizedAccessException">Thrown when the event exists but is not owned by the current user.</exception>
    public async Task<EventDetailDto> Handle(GetEventByIdQuery request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var ev = await _dbContext.Events
            .AsNoTracking()
            .Include(e => e.EventType)
            .Include(e => e.Organizer)
            .FirstOrDefaultAsync(e => e.Id == request.Id, cancellationToken)
            ?? throw new KeyNotFoundException($"Event {request.Id} not found.");

        if (ev.OrganizerId != user.Id)
        {
            throw new UnauthorizedAccessException("You do not have access to this event.");
        }

        // Aggregate RSVP counts in a single round-trip rather than N status queries.
        var counts = await _dbContext.Rsvps
            .AsNoTracking()
            .Where(r => r.EventId == ev.Id)
            .GroupBy(r => r.Status)
            .Select(g => new { Status = g.Key, Count = g.Count() })
            .ToListAsync(cancellationToken);

        var going = counts.FirstOrDefault(c => c.Status == RsvpStatus.Going)?.Count ?? 0;
        var notGoing = counts.FirstOrDefault(c => c.Status == RsvpStatus.NotGoing)?.Count ?? 0;
        var maybe = counts.FirstOrDefault(c => c.Status == RsvpStatus.Maybe)?.Count ?? 0;
        var total = going + notGoing + maybe;

        var links = await _dbContext.InviteLinks
            .AsNoTracking()
            .Where(l => l.EventId == ev.Id)
            .OrderByDescending(l => l.CreatedAt)
            .ToListAsync(cancellationToken);

        var linkDtos = links
            .Select(l => CreateInviteLinkHandler.ToDto(l, _frontend.BaseUrl))
            .ToList();

        return new EventDetailDto(
            ev.Id,
            ev.Title,
            ev.OrganizerName,
            ev.Description,
            ev.Location,
            ev.IsVirtual,
            ev.MeetingUrl,
            ev.StartDate,
            ev.EndDate,
            ev.MaxAttendees,
            ev.CoverImageUrl,
            ev.IsCancelled,
            ev.CreatedAt,
            ev.UpdatedAt,
            new EventTypeDto(ev.EventType.Id, ev.EventType.Name, ev.EventType.Icon),
            new OrganizerDto(ev.OrganizerName, ev.Organizer.AvatarUrl),
            new RsvpSummaryDto(going, notGoing, maybe, total),
            linkDtos);
    }
}
