// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';

import { EventService } from '../../core/api/event.service';
import { AuthService } from '../../core/auth/auth.service';
import type { EventSummaryDto } from '../../core/models/event.model';
import { EmptyStateComponent } from '../../shared/components/empty-state/empty-state.component';
import { LoadingSpinnerComponent } from '../../shared/components/loading-spinner/loading-spinner.component';
import { EventCardComponent } from './event-card/event-card.component';

/**
 * Personal home screen — at-a-glance stats + the next five upcoming events.
 *
 * Pulls a single page of events on init (page size 50, sorted by date asc) so
 * we can derive all dashboard stats client-side without extra round-trips.
 * Replace with dedicated `/stats` endpoints once the dataset grows.
 */
@Component({
  selector: 'app-dashboard',
  imports: [RouterLink, EventCardComponent, EmptyStateComponent, LoadingSpinnerComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './dashboard.component.html',
})
export class DashboardComponent {
  private readonly auth = inject(AuthService);
  private readonly eventService = inject(EventService);

  protected readonly displayName = this.auth.displayName;
  protected readonly loading = signal(true);
  protected readonly errorMessage = signal<string | null>(null);

  private readonly events = signal<readonly EventSummaryDto[]>([]);

  protected readonly totalEvents = computed(() => this.events().length);

  protected readonly upcomingEvents = computed(() => {
    const now = Date.now();
    return this.events().filter(
      (e) => !e.isCancelled && new Date(e.startDate).getTime() > now,
    );
  });

  protected readonly upcomingCount = computed(() => this.upcomingEvents().length);

  protected readonly totalRsvpsGoing = computed(() =>
    this.events().reduce((sum, e) => sum + e.rsvpCount, 0),
  );

  protected readonly nextFive = computed(() =>
    [...this.upcomingEvents()]
      .sort((a, b) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime())
      .slice(0, 5),
  );

  protected trackById = (_: number, e: EventSummaryDto): string => e.id;

  constructor() {
    this.eventService
      .getEvents({ page: 1, pageSize: 50, sortBy: 'date', sortDir: 'asc' })
      .subscribe({
        next: (result) => {
          this.events.set(result.items);
          this.loading.set(false);
        },
        error: () => {
          this.loading.set(false);
          this.errorMessage.set(this.eventService.error() ?? 'Could not load events.');
        },
      });
  }
}
