// Generated by GitHub Copilot
import { HttpErrorResponse, HttpInterceptorFn } from '@angular/common/http';
import { inject } from '@angular/core';
import { Router } from '@angular/router';
import { catchError, retry, throwError, timer } from 'rxjs';

import { ToastService } from '../../shared/services/toast.service';

/**
 * Functional HTTP interceptor that converts low-level HTTP failures into
 * user-facing toasts and standardised navigation side-effects.
 *
 * Behaviour:
 * | Status | Action                                                          |
 * |--------|-----------------------------------------------------------------|
 * | 0      | Toast "Unable to connect…" — likely network/CORS failure.       |
 * | 400    | Re-throw — forms render field-level errors from the response.   |
 * | 401    | Toast + redirect to /login (preserves return URL).              |
 * | 403    | Toast "You don't have permission…".                             |
 * | 404    | Toast "Not found.".                                             |
 * | 410    | Re-throw — invite-link pages render a Gone-specific UX.         |
 * | 429    | Toast "Too many attempts. Please wait a moment.".               |
 * | 5xx    | Toast "Something went wrong. Please try again.".                |
 *
 * Registration order matters: place this AFTER `authInterceptor` so the bearer
 * token is attached before this interceptor observes the response.
 *
 * Security: error bodies are NEVER displayed verbatim — only the curated
 * messages above. The original error is re-thrown so callers retain access to
 * details (e.g. ProblemDetails) when they choose to handle it themselves.
 */
export const errorInterceptor: HttpInterceptorFn = (req, next) => {
  const toast = inject(ToastService);
  const router = inject(Router);

  return next(req).pipe(
    // Retry up to 3 times on status 0 (no connection) — handles Azure App
    // Service cold starts where the backend needs a few seconds to wake up.
    retry({
      count: 3,
      delay: (error, retryCount) => {
        if (error instanceof HttpErrorResponse && error.status === 0) {
          return timer(retryCount * 2000); // 2 s, 4 s, 6 s
        }
        return throwError(() => error);
      },
    }),
    catchError((error: unknown) => {
      if (!(error instanceof HttpErrorResponse)) {
        // Non-HTTP failure (rare): let it propagate to GlobalErrorHandler.
        return throwError(() => error);
      }

      switch (error.status) {
        case 0:
          toast.error('Unable to connect. Check your internet.');
          break;

        case 400:
          // Validation problems — let the form display field-level messages.
          break;

        case 401: {
          toast.error('Session expired. Please log in again.');
          const returnUrl = router.url && router.url !== '/login' ? router.url : '/dashboard';
          router.navigate(['/login'], { queryParams: { returnUrl } });
          break;
        }

        case 403:
          toast.error("You don't have permission to do that.");
          break;

        case 404:
          toast.error('Not found.');
          break;

        case 410:
          // Public-RSVP pages render a Gone-specific message; pass through.
          break;

        case 429:
          toast.error('Too many attempts. Please wait a moment.');
          break;

        default:
          if (error.status >= 500) {
            toast.error('Something went wrong. Please try again.');
          }
          break;
      }

      return throwError(() => error);
    }),
  );
};
