// Generated by GitHub Copilot
import { ErrorHandler, Injectable, inject, isDevMode } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';

import { ToastService } from '../../shared/services/toast.service';

/**
 * Application-wide last-resort error handler.
 *
 * Responsibilities:
 * - Logs every uncaught exception (full object in dev, message-only in prod).
 * - Surfaces a friendly toast for non-HTTP failures (HTTP errors are owned by
 *   {@link errorInterceptor} and would otherwise be reported twice).
 *
 * Registered in `app.config.ts` via
 * `{ provide: ErrorHandler, useClass: GlobalErrorHandler }`.
 *
 * Security: error messages shown to the user are intentionally generic — server
 * stack traces and internal field names must never reach the UI.
 */
@Injectable({ providedIn: 'root' })
export class GlobalErrorHandler implements ErrorHandler {
  private readonly toast = inject(ToastService);

  /**
   * Handles an uncaught error. Always invoked by Angular on the JS task that
   * threw; safe to perform synchronous DOM/signal updates here.
   */
  handleError(error: unknown): void {
    if (isDevMode()) {
      console.error('[GlobalErrorHandler]', error);
    } else {
      console.error('[GlobalErrorHandler]', this.summarize(error));
    }

    // HTTP errors are translated into toasts by the interceptor — don't double-notify.
    if (this.isHttpError(error)) {
      return;
    }

    this.toast.error('Something went wrong. Please try again.');
  }

  /** Detects HttpErrorResponse without importing it via a value-only check. */
  private isHttpError(error: unknown): boolean {
    return (
      error instanceof HttpErrorResponse ||
      (typeof error === 'object' &&
        error !== null &&
        (error as { rejection?: unknown }).rejection instanceof HttpErrorResponse)
    );
  }

  /** Returns a single-line description safe to log in production. */
  private summarize(error: unknown): string {
    if (error instanceof Error) {
      return `${error.name}: ${error.message}`;
    }
    if (typeof error === 'string') {
      return error;
    }
    return 'Unknown error';
  }
}
