// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component, computed, effect, inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

import { AuthService } from '../../../core/auth/auth.service';

/**
 * Public sign-in page. Triggers the Auth0 Universal Login redirect.
 *
 * Behaviour:
 * - When the SDK reports an existing authenticated session, immediately
 *   navigates to the route in `?returnUrl=` (default `/dashboard`).
 * - Pressing the "Sign in" button calls `AuthService.login()` with that
 *   same `returnUrl` preserved as `appState.target`.
 *
 * Accessibility:
 * - Page heading is the only `<h1>` in the routed view.
 * - Button has descriptive label and visible focus styles.
 */
@Component({
  selector: 'app-login',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section
      class="flex min-h-[calc(100vh-8rem)] items-center justify-center px-4 py-12 sm:px-6"
      aria-labelledby="login-heading"
    >
      <div
        class="w-full max-w-md rounded-xl border border-slate-200 bg-white p-8 shadow-sm"
      >
        <div class="text-center">
          <p class="text-3xl" aria-hidden="true">📅</p>
          <h1 id="login-heading" class="mt-2 text-2xl font-semibold text-slate-900">
            Sign in to EventSync
          </h1>
          <p class="mt-2 text-sm text-slate-600">
            Plan, share, and track event RSVPs in one place.
          </p>
        </div>

        <button
          type="button"
          (click)="onSignIn()"
          [disabled]="isBusy()"
          [attr.aria-busy]="isBusy() ? 'true' : 'false'"
          class="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700 focus:outline-none disabled:cursor-not-allowed disabled:opacity-60"
        >
          @if (isBusy()) {
            <span aria-hidden="true">…</span>
            <span>Redirecting…</span>
          } @else {
            <span aria-hidden="true">🔐</span>
            <span>Sign in with Auth0</span>
          }
        </button>

        <p class="mt-6 text-center text-xs text-slate-500">
          By signing in you agree to the EventSync terms of service.
        </p>
      </div>
    </section>
  `,
})
export class LoginComponent {
  private readonly auth = inject(AuthService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);

  /** True while Auth0 SDK boots or while we're redirecting. */
  protected readonly isBusy = computed(() => this.auth.isLoading());

  constructor() {
    // Redirect away from /login if the user already has a session.
    effect(() => {
      if (!this.auth.isLoading() && this.auth.isAuthenticated()) {
        const target = this.route.snapshot.queryParamMap.get('returnUrl') ?? '/dashboard';
        this.router.navigateByUrl(target);
      }
    });
  }

  /** Click handler — kicks off the Auth0 Universal Login redirect. */
  protected onSignIn(): void {
    const target = this.route.snapshot.queryParamMap.get('returnUrl') ?? '/dashboard';
    this.auth.login({ target });
  }
}
