// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { RouterLink } from '@angular/router';

/**
 * Friendly empty-state placeholder used when a list has no items.
 *
 * Either supply `actionLink` for navigation, or omit it to receive the
 * `action` event and handle it yourself (e.g. open a modal).
 */
@Component({
  selector: 'app-empty-state',
  imports: [RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './empty-state.component.html',
})
export class EmptyStateComponent {
  readonly icon = input<string>('📭');
  readonly title = input.required<string>();
  readonly message = input<string>('');
  readonly actionLabel = input<string | undefined>(undefined);
  readonly actionLink = input<string | undefined>(undefined);

  readonly action = output<void>();

  protected onAction(): void {
    this.action.emit();
  }
}
