// Generated by GitHub Copilot
using EventSync.Api.Common.Models;
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.Events.Common;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.Events.GetEvents;

/// <summary>
/// Query: list the current user's events with paging, search, filter and sort.
/// </summary>
/// <param name="Page">1-based page index. Values &lt; 1 are clamped to 1.</param>
/// <param name="PageSize">Items per page. Clamped to [1, 50].</param>
/// <param name="Search">Optional case-insensitive title search fragment.</param>
/// <param name="TypeId">Optional EventType filter.</param>
/// <param name="SortBy">Either <c>"date"</c> (StartDate) or <c>"title"</c>.</param>
/// <param name="SortDir">Either <c>"asc"</c> or <c>"desc"</c>.</param>
public sealed record GetEventsQuery(
    int Page = 1,
    int PageSize = 10,
    string? Search = null,
    int? TypeId = null,
    string SortBy = "date",
    string SortDir = "asc") : IRequest<PagedResult<EventSummaryDto>>;

/// <summary>Handler for <see cref="GetEventsQuery"/>.</summary>
public sealed class GetEventsHandler : IRequestHandler<GetEventsQuery, PagedResult<EventSummaryDto>>
{
    private const int MinPageSize = 1;
    private const int MaxPageSize = 50;

    private readonly ICurrentUserService _currentUser;
    private readonly AppDbContext _dbContext;

    /// <summary>Initializes a new instance of <see cref="GetEventsHandler"/>.</summary>
    public GetEventsHandler(ICurrentUserService currentUser, AppDbContext dbContext)
    {
        _currentUser = currentUser;
        _dbContext = dbContext;
    }

    /// <inheritdoc/>
    public async Task<PagedResult<EventSummaryDto>> Handle(
        GetEventsQuery request,
        CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var page = Math.Max(1, request.Page);
        var pageSize = Math.Clamp(request.PageSize, MinPageSize, MaxPageSize);

        // Soft-delete is excluded by the global query filter on Event.
        IQueryable<Event> query = _dbContext.Events
            .AsNoTracking()
            .Where(e => e.OrganizerId == user.Id);

        if (!string.IsNullOrWhiteSpace(request.Search))
        {
            var search = request.Search.Trim();
            // EF.Functions.Like with %% gives a case-insensitive contains under SQL Server's
            // default collation — keeps the filter server-side rather than client-evaluated.
            query = query.Where(e => EF.Functions.Like(e.Title, $"%{search}%"));
        }

        if (request.TypeId is int typeId && typeId > 0)
        {
            query = query.Where(e => e.EventTypeId == typeId);
        }

        var sortDescending = string.Equals(request.SortDir, "desc", StringComparison.OrdinalIgnoreCase);
        query = (request.SortBy?.ToLowerInvariant()) switch
        {
            "title" => sortDescending
                ? query.OrderByDescending(e => e.Title)
                : query.OrderBy(e => e.Title),
            _ => sortDescending
                ? query.OrderByDescending(e => e.StartDate)
                : query.OrderBy(e => e.StartDate),
        };

        var totalCount = await query.CountAsync(cancellationToken);

        var items = await query
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .Select(e => new EventSummaryDto(
                e.Id,
                e.Title,
                e.EventType.Name,
                e.EventType.Icon,
                e.StartDate,
                e.EndDate,
                e.Location,
                e.IsVirtual,
                e.IsCancelled,
                e.Rsvps.Count(r => r.Status == RsvpStatus.Going),
                e.CoverImageUrl,
                e.CreatedAt))
            .ToListAsync(cancellationToken);

        return new PagedResult<EventSummaryDto>(items, page, pageSize, totalCount);
    }
}
