// Generated by GitHub Copilot
import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { App } from './app/app';
import { environment } from './environments/environment';

bootstrapApplication(App, appConfig)
  .then(() => enableAxeInDev())
  .catch((err) => console.error(err));

/**
 * Loads `axe-core` lazily in non-production builds and runs an accessibility
 * scan on every route change. Violations are logged to the console with the
 * standard axe report so they're easy to triage during development.
 *
 * Production bundles never import axe (the dynamic import happens behind the
 * environment guard and is tree-shaken away when `environment.production`).
 */
async function enableAxeInDev(): Promise<void> {
  if (environment.production) {
    return;
  }

  const { default: axe } = await import('axe-core');

  const runScan = (): void => {
    // Defer until the next animation frame so freshly-routed templates have rendered.
    requestAnimationFrame(() => {
      axe
        .run(document, { resultTypes: ['violations'] })
        .then((results) => {
          if (results.violations.length === 0) {
            return;
          }
          console.groupCollapsed(
            `[axe] ${results.violations.length} accessibility violation(s) on ${location.pathname}`,
          );
          for (const v of results.violations) {
            console.warn(`${v.id} (${v.impact}): ${v.help}\n→ ${v.helpUrl}`, v.nodes);
          }
          console.groupEnd();
        })
        .catch((err) => console.error('[axe] scan failed', err));
    });
  };

  // Initial scan + re-scan on history navigation.
  runScan();
  window.addEventListener('popstate', runScan);
}
