// Generated by GitHub Copilot
import { DatePipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  signal,
} from '@angular/core';
import {
  FormBuilder,
  ReactiveFormsModule,
  Validators,
  type ValidationErrors,
} from '@angular/forms';
import { Router } from '@angular/router';

import { RsvpService } from '../../../core/api/rsvp.service';
import { environment } from '../../../../environments/environment';
import type {
  PublicEventDto,
  RsvpConfirmationDto,
  SubmitRsvpRequest,
} from '../../../core/models/rsvp.model';
import { RsvpStatus } from '../../../core/models/rsvp.model';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';

/** Discriminated load state. */
type LoadState =
  | { kind: 'loading' }
  | { kind: 'invalid'; message: string }
  | { kind: 'error'; message: string }
  | { kind: 'ready'; event: PublicEventDto };

/** Visual descriptor for each RSVP status card. */
interface StatusOption {
  readonly value: RsvpStatus;
  readonly label: string;
  readonly description: string;
  readonly icon: string;
  readonly accent: string;
  readonly accentSelected: string;
}

const NOTE_MAX_LENGTH = 500;

/**
 * Anonymous, public-facing RSVP page rendered at `/rsvp/:token`.
 *
 * No auth guard \u2014 anyone with a valid invite token may view and submit. The
 * `RsvpService` reaches `GET /invite/{token}` and `POST /invite/{token}/rsvp`,
 * both of which are explicitly bypassed by the auth interceptor so guests
 * never trigger an Auth0 silent-renew round-trip.
 */
@Component({
  selector: 'app-rsvp-page',
  imports: [ReactiveFormsModule, DatePipe, LoadingSpinnerComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './rsvp-page.component.html',
})
export class RsvpPageComponent {
  private readonly rsvpService = inject(RsvpService);
  private readonly router = inject(Router);
  private readonly fb = inject(FormBuilder);

  /** Route parameter \u2014 bound by `withComponentInputBinding`. */
  readonly token = input.required<string>();

  protected readonly state = signal<LoadState>({ kind: 'loading' });
  protected readonly submitting = signal(false);
  protected readonly submitError = signal<string | null>(null);

  protected readonly noteMaxLength = NOTE_MAX_LENGTH;

  /** RSVP options rendered as the radio-group cards. */
  protected readonly statusOptions: readonly StatusOption[] = [
    {
      value: RsvpStatus.Going,
      label: 'Going',
      description: "I'll be there",
      icon: '\u2713',
      accent: 'border-slate-200 hover:border-emerald-400',
      accentSelected: 'border-emerald-500 bg-emerald-50 ring-2 ring-emerald-500',
    },
    {
      value: RsvpStatus.Maybe,
      label: 'Maybe',
      description: 'Not sure yet',
      icon: '?',
      accent: 'border-slate-200 hover:border-amber-400',
      accentSelected: 'border-amber-500 bg-amber-50 ring-2 ring-amber-500',
    },
    {
      value: RsvpStatus.NotGoing,
      label: 'Not Going',
      description: "Can't make it",
      icon: '\u2715',
      accent: 'border-slate-200 hover:border-rose-400',
      accentSelected: 'border-rose-500 bg-rose-50 ring-2 ring-rose-500',
    },
  ];

  protected readonly form = this.fb.nonNullable.group({
    guestName: ['', [Validators.required, Validators.maxLength(100)]],
    guestEmail: ['', [Validators.email, Validators.maxLength(256)]],
    status: [null as RsvpStatus | null, [Validators.required]],
    note: ['', [Validators.maxLength(NOTE_MAX_LENGTH)]],
  });

  /** Live character count for the note textarea. */
  protected readonly noteCount = computed(() => {
    // Touch the value signal-equivalent via valueChanges is overkill; rely on
    // change detection \u2014 we recompute on every emission via this getter.
    const note = this.form.controls.note.value ?? '';
    return note.length;
  });

  protected readonly coverImageSrc = computed(() => {
    if (this.state().kind !== 'ready') return null;
    const url = (this.state() as { event: PublicEventDto }).event.coverImageUrl;
    if (!url) return null;
    if (url.startsWith('http://') || url.startsWith('https://')) return url;
    const apiOrigin = environment.apiUrl.replace(/\/api\/v1$/, '');
    return `${apiOrigin}${url}`;
  });

  /** The loaded event, or null while loading / on error. */
  protected readonly event = computed<PublicEventDto | null>(() => {
    const s = this.state();
    return s.kind === 'ready' ? s.event : null;
  });

  /** True when a capped event has no remaining "Going" spots. */
  protected readonly isFull = computed(() => this.event()?.isFull ?? false);

  /** Remaining spots for a capped event, or null when uncapped. */
  protected readonly spotsRemaining = computed(() => this.event()?.spotsRemaining ?? null);

  /** The status option that should receive focus first (skips a disabled "Going"). */
  protected readonly initialFocusValue = computed<RsvpStatus>(() => {
    const firstEnabled = this.statusOptions.find((o) => !this.isOptionDisabled(o.value));
    return firstEnabled?.value ?? this.statusOptions[0].value;
  });

  /** "Going" is disabled once a capped event is full; Maybe/NotGoing stay open. */
  protected isOptionDisabled(value: RsvpStatus): boolean {
    return value === RsvpStatus.Going && this.isFull();
  }

  /** True when a status card should appear selected. */
  protected isSelected(value: RsvpStatus): boolean {
    return this.form.controls.status.value === value;
  }

  /**
   * Click handler for a status card. The card is a `<label>` wrapping a native
   * radio `<input>`, so a click on a disabled card would otherwise check the
   * nested input via the browser's default label behaviour (bypassing
   * `selectStatus`). Cancelling the default action keeps a disabled option (e.g.
   * "Going" on a full event) from being selected.
   */
  protected onCardClick(event: MouseEvent, value: RsvpStatus): void {
    if (this.isOptionDisabled(value)) {
      event.preventDefault();
      return;
    }
    this.selectStatus(value);
  }

  /** Selects a status (keyboard + programmatic). Ignores disabled options. */
  protected selectStatus(value: RsvpStatus): void {
    if (this.isOptionDisabled(value)) return;
    this.form.controls.status.setValue(value);
    this.form.controls.status.markAsTouched();
  }

  /**
   * Roving-tabindex keyboard handler for the radio group.
   * Implements WAI-ARIA APG radio-group keyboard pattern (arrow keys cycle).
   */
  protected onStatusKeydown(event: KeyboardEvent, index: number): void {
    let nextIndex: number | null = null;
    switch (event.key) {
      case 'ArrowRight':
      case 'ArrowDown':
        nextIndex = this.nextEnabledIndex(index, 1);
        break;
      case 'ArrowLeft':
      case 'ArrowUp':
        nextIndex = this.nextEnabledIndex(index, -1);
        break;
      case ' ':
      case 'Enter':
        this.selectStatus(this.statusOptions[index].value);
        event.preventDefault();
        return;
      default:
        return;
    }
    if (nextIndex === null || nextIndex === index) return;
    event.preventDefault();
    const next = this.statusOptions[nextIndex];
    this.selectStatus(next.value);
    const target = (event.currentTarget as HTMLElement).ownerDocument
      ?.querySelector<HTMLElement>(`[data-status-card="${next.value}"]`);
    target?.focus();
  }

  /** Finds the next selectable option index in the given direction, skipping disabled cards. */
  private nextEnabledIndex(start: number, step: number): number {
    const count = this.statusOptions.length;
    let idx = start;
    for (let i = 0; i < count; i++) {
      idx = (idx + step + count) % count;
      if (!this.isOptionDisabled(this.statusOptions[idx].value)) return idx;
    }
    return start;
  }
  /**
   * Scrolls the focused field into view once the virtual keyboard has resized
   * the viewport, so guests can see what they type on mobile.
   */
  protected scrollFieldIntoView(event: FocusEvent): void {
    const el = event.target as HTMLElement;
    const scroll = () => el.scrollIntoView({ behavior: 'smooth', block: 'center' });
    if (window.visualViewport) {
      const onResize = () => {
        window.visualViewport!.removeEventListener('resize', onResize);
        scroll();
      };
      window.visualViewport.addEventListener('resize', onResize);
      // Fallback for when the keyboard is already open (no resize fires).
      setTimeout(() => {
        window.visualViewport!.removeEventListener('resize', onResize);
        scroll();
      }, 350);
    } else {
      setTimeout(scroll, 300);
    }
  }
  /** Submit handler \u2014 posts the RSVP and navigates to the confirmation page on success. */
  protected submit(): void {
    if (this.submitting() || this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    const raw = this.form.getRawValue();
    if (raw.status === null) return;

    const payload: SubmitRsvpRequest = {
      guestName: raw.guestName.trim(),
      guestEmail: raw.guestEmail?.trim() ? raw.guestEmail.trim() : null,
      status: raw.status,
      note: raw.note?.trim() ? raw.note.trim() : null,
    };

    this.submitting.set(true);
    this.submitError.set(null);

    this.rsvpService.submitRsvp(this.token(), payload).subscribe({
      next: (confirmation: RsvpConfirmationDto) => {
        this.submitting.set(false);
        // Pass the confirmation via the History API state so the next page can
        // render it without a second round-trip.
        this.router.navigate(['/rsvp', this.token(), 'confirmed'], {
          state: { confirmation },
        });
      },
      error: (err: unknown) => {
        this.submitting.set(false);
        this.submitError.set(this.toFriendlyError(err));
      },
    });
  }

  /** Unique id for an error message paragraph (links via `aria-describedby`). */
  protected errorId(controlName: string): string {
    return `rsvp-${controlName}-error`;
  }

  /** True when the given control is invalid AND has been touched. */
  protected hasError(controlName: keyof typeof this.form.controls): boolean {
    const ctrl = this.form.controls[controlName];
    return ctrl.invalid && (ctrl.touched || ctrl.dirty);
  }

  /** First-error message string for a control. */
  protected errorMessage(controlName: keyof typeof this.form.controls): string {
    const errors = this.form.controls[controlName].errors as ValidationErrors | null;
    if (!errors) return '';
    if (errors['required']) return 'This field is required.';
    if (errors['email']) return 'Enter a valid email address.';
    if (errors['maxlength']) {
      const max = errors['maxlength'] as { requiredLength: number };
      return `Maximum ${max.requiredLength} characters.`;
    }
    return 'Invalid value.';
  }

  // eslint-disable-next-line @typescript-eslint/no-unused-private-class-members
  private readonly loadOnTokenChange = effect(() => {
    const token = this.token();
    if (!token) return;
    this.state.set({ kind: 'loading' });
    this.rsvpService.getPublicEvent(token).subscribe({
      next: (event) => this.state.set({ kind: 'ready', event }),
      error: (err: unknown) => {
        if (err instanceof HttpErrorResponse && err.status === 410) {
          const message =
            (err.error as { message?: string } | null)?.message ??
            'This invite link is no longer available.';
          this.state.set({ kind: 'invalid', message });
        } else {
          this.state.set({
            kind: 'error',
            message:
              this.rsvpService.error() ??
              'We could not load this invitation. Please try again later.',
          });
        }
      },
    });
  });

  /** Maps a server error to a user-friendly message for the inline submit error. */
  private toFriendlyError(err: unknown): string {
    if (err instanceof HttpErrorResponse) {
      if (err.status === 410) {
        return (
          (err.error as { message?: string } | null)?.message ??
          'This invite link is no longer available.'
        );
      }
      if (err.status === 429) {
        return 'Too many submissions. Please wait a moment and try again.';
      }
      if (err.status === 409) {
        // Event filled up between page load and submission (RFC 7807 ProblemDetails).
        const body = err.error as { detail?: string; message?: string } | null;
        return (
          body?.detail ??
          body?.message ??
          'This event is now full and can no longer accept "Going" responses.'
        );
      }
      if (err.status === 400) {
        return 'Please review the form and try again.';
      }
    }
    return this.rsvpService.error() ?? 'Could not submit your RSVP. Please try again.';
  }
}
