// Generated by GitHub Copilot
namespace EventSync.Api.Common.Exceptions;

/// <summary>
/// Thrown when a guest tries to RSVP <c>Going</c> to an event that has already
/// reached its <see cref="Data.Entities.Event.MaxAttendees"/> capacity.
/// </summary>
/// <remarks>
/// Endpoints translate this to <c>409 Conflict</c> — the request was well-formed
/// and the invite valid, but the event's state (a full guest list) prevents it
/// from being fulfilled. Only <c>Going</c> responses consume a seat; a guest may
/// still respond <c>Maybe</c> or <c>NotGoing</c> to a full event.
/// </remarks>
public sealed class EventFullException : Exception
{
    /// <summary>Initializes a new instance of <see cref="EventFullException"/>.</summary>
    /// <param name="eventTitle">Title of the event, echoed into a guest-safe message.</param>
    public EventFullException(string eventTitle)
        : base($"\"{eventTitle}\" has reached its attendee limit and is no longer accepting new guests.")
    {
    }
}
