// Generated by GitHub Copilot
namespace EventSync.Api.Common.Exceptions;

/// <summary>
/// Thrown when an authenticated caller attempts to act on a resource they do not own.
/// </summary>
/// <remarks>
/// Endpoints translate this to <c>403 Forbidden</c>. Distinct from
/// <see cref="UnauthorizedAccessException"/> (which the global handler also maps
/// to 403) so domain code can surface intent without depending on a BCL exception.
/// </remarks>
public sealed class ForbiddenAccessException : Exception
{
    /// <summary>Initializes a new instance of <see cref="ForbiddenAccessException"/>.</summary>
    public ForbiddenAccessException()
        : base("You do not have permission to perform this action.")
    {
    }

    /// <summary>Initializes a new instance of <see cref="ForbiddenAccessException"/> with a custom message.</summary>
    public ForbiddenAccessException(string message) : base(message)
    {
    }
}
