// Generated by GitHub Copilot
namespace EventSync.Api.Common.Exceptions;

/// <summary>
/// Thrown when a public invite token cannot be honoured (not found, deactivated,
/// expired, exhausted, or the underlying event has been removed).
/// </summary>
/// <remarks>
/// Endpoints translate this to <c>410 Gone</c>. The message is safe to expose to
/// the caller because it intentionally avoids confirming whether the token ever
/// existed (e.g., "Invite link not found" is shown for both unknown tokens and
/// tokens whose parent event was deleted).
/// </remarks>
public sealed class InvalidInviteException : Exception
{
    /// <summary>Initializes a new instance of <see cref="InvalidInviteException"/>.</summary>
    /// <param name="message">User-safe explanation of why the link cannot be used.</param>
    public InvalidInviteException(string message) : base(message)
    {
    }
}
