// Generated by GitHub Copilot
namespace EventSync.Api.Common.Exceptions;

/// <summary>
/// Thrown when an entity referenced by an authenticated request cannot be located.
/// </summary>
/// <remarks>
/// Endpoints translate this to <c>404 Not Found</c>. The message intentionally
/// references the entity name (never raw IDs supplied by the caller) so logs are
/// useful while responses remain free of internal data.
/// </remarks>
public sealed class NotFoundException : Exception
{
    /// <summary>Initializes a new instance of <see cref="NotFoundException"/>.</summary>
    /// <param name="entity">Name of the missing entity (e.g. <c>"Event"</c>).</param>
    public NotFoundException(string entity)
        : base($"{entity} was not found.")
    {
        Entity = entity;
    }

    /// <summary>Name of the entity that could not be located.</summary>
    public string Entity { get; }
}
