// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component, effect, inject } from '@angular/core';
import { Router } from '@angular/router';

import { AuthService } from '../../../core/auth/auth.service';

/**
 * Auth0 redirect-callback landing page.
 *
 * The Auth0 SDK intercepts the redirect query string (`code`, `state`) on
 * application bootstrap and exchanges it for tokens. While that is in flight
 * we display an accessible loading state, then forward to `/dashboard` (or to
 * `appState.target` if the SDK preserved one).
 *
 * Accessibility:
 * - The status region uses `role="status"` + `aria-live="polite"` so screen
 *   readers announce the loading message without stealing focus.
 */
@Component({
  selector: 'app-auth-callback',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section
      class="flex min-h-[calc(100vh-8rem)] items-center justify-center px-4"
      aria-labelledby="callback-heading"
    >
      <div class="text-center">
        <h1 id="callback-heading" class="sr-only">Completing sign-in</h1>
        <div
          class="mx-auto h-12 w-12 animate-spin rounded-full border-4 border-slate-200 border-t-indigo-600"
          aria-hidden="true"
        ></div>
        <p
          role="status"
          aria-live="polite"
          class="mt-4 text-sm font-medium text-slate-700"
        >
          Completing sign-in…
        </p>
      </div>
    </section>
  `,
})
export class AuthCallbackComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  constructor() {
    // Once the SDK finishes processing the redirect, forward the user.
    effect(() => {
      if (this.auth.isLoading()) {
        return;
      }
      const target = this.auth.isAuthenticated() ? '/dashboard' : '/login';
      this.router.navigateByUrl(target);
    });
  }
}
