// Generated by GitHub Copilot
import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { RouterLink } from '@angular/router';

import type { EventSummaryDto } from '../../../core/models/event.model';
import { environment } from '../../../../environments/environment';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';
import { RelativeDatePipe } from '../../../shared/pipes/relative-date.pipe';

/**
 * Dashboard summary card for a single event. Pure presentational — no data
 * fetching. Click target wraps the heading via `routerLink`.
 */
@Component({
  selector: 'app-event-card',
  imports: [RouterLink, DatePipe, RelativeDatePipe, StatusBadgeComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <article class="flex h-full flex-col overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm transition hover:shadow-md">
      @if (coverSrc()) {
        <img
          [src]="coverSrc()!"
          [alt]="'Cover for ' + event().title"
          referrerpolicy="no-referrer"
          class="h-28 w-full object-cover"
          (error)="$any($event).target.style.display='none'"
        />
      }
      <div class="flex flex-1 flex-col p-4">
        <div class="flex items-start justify-between gap-3">
          <a
            [routerLink]="['/events', event().id]"
            class="text-base font-semibold text-indigo-700 hover:underline"
          >
            {{ event().title }}
          </a>
          <app-status-badge [status]="badge().text" [variant]="badge().variant" />
        </div>
        <p class="mt-1 text-xs text-slate-600">
          <span aria-hidden="true">{{ event().eventTypeIcon }}</span>
          {{ event().eventTypeName }}
        </p>
        <p class="mt-2 text-sm text-slate-700">
          {{ event().startDate | date:'medium' }}
        </p>
        <p class="text-xs text-slate-500">
          {{ event().startDate | relativeDate }}
        </p>
        @if (event().location) {
          <p class="mt-1 text-xs text-slate-600">📍 {{ event().location }}</p>
        }
        <p class="mt-auto pt-3 text-xs text-slate-500">
          {{ event().rsvpCount }} going
        </p>
      </div>
    </article>
  `,
})
export class EventCardComponent {
  readonly event = input.required<EventSummaryDto>();

  protected readonly coverSrc = computed(() => {
    const url = this.event().coverImageUrl;
    if (!url) return null;
    if (url.startsWith('http://') || url.startsWith('https://')) return url;
    const apiOrigin = environment.apiUrl.replace(/\/api\/v1$/, '');
    return `${apiOrigin}${url}`;
  });

  protected readonly badge = computed<{ text: string; variant: 'success' | 'danger' | 'default' }>(
    () => {
      const ev = this.event();
      if (ev.isCancelled) return { text: 'Cancelled', variant: 'danger' };
      const upcoming = new Date(ev.startDate).getTime() > Date.now();
      return upcoming
        ? { text: 'Upcoming', variant: 'success' }
        : { text: 'Past', variant: 'default' };
    },
  );
}
