// Generated by GitHub Copilot
using System.Net;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using EventSync.Api.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace EventSync.Api.Tests;

/// <summary>
/// Exercises the authenticated CSV export endpoint over real HTTP via
/// <see cref="WebApplicationFactory{TEntryPoint}"/> with a stub authentication
/// scheme (so no Auth0 round-trip is needed). Verifies the status, the
/// <c>text/csv</c> content type, the download disposition + filename, the UTF-8
/// BOM, and the CSV bytes — i.e. exactly what a browser download would receive.
/// </summary>
public sealed class ExportRsvpsEndpointTests
{
    [Fact]
    public async Task Export_AsOrganizer_Returns200_AsCsvAttachment_WithBomAndRows()
    {
        using var factory = new AuthenticatedApiFactory();
        var eventId = factory.SeedOwnedEvent(goingCount: 2);
        var client = factory.CreateClient();

        var response = await client.GetAsync($"/api/v1/events/{eventId}/rsvps/export");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        Assert.Equal("text/csv", response.Content.Headers.ContentType?.MediaType);
        Assert.Equal("attachment", response.Content.Headers.ContentDisposition?.DispositionType);

        var fileName = response.Content.Headers.ContentDisposition?.FileName
            ?? response.Content.Headers.ContentDisposition?.FileNameStar;
        Assert.NotNull(fileName);
        Assert.Contains(".csv", fileName);

        var bytes = await response.Content.ReadAsByteArrayAsync();
        Assert.True(
            bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF,
            "CSV should start with a UTF-8 BOM for spreadsheet compatibility.");

        var text = Encoding.UTF8.GetString(bytes);
        Assert.Contains("Name,Email,Status,Note,RespondedAtUtc,UpdatedAtUtc", text);
        Assert.Contains("Seeded Guest 0", text);
        Assert.Contains("Going", text);
    }

    [Fact]
    public async Task Export_ForAnotherOrganizersEvent_Returns403()
    {
        using var factory = new AuthenticatedApiFactory();
        var foreignEventId = factory.SeedForeignEvent();
        var client = factory.CreateClient();

        var response = await client.GetAsync($"/api/v1/events/{foreignEventId}/rsvps/export");

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
    }

    [Fact]
    public async Task Export_ForMissingEvent_Returns404()
    {
        using var factory = new AuthenticatedApiFactory();
        factory.SeedOwnedEvent(goingCount: 0); // provisions the caller's user row
        var client = factory.CreateClient();

        var response = await client.GetAsync($"/api/v1/events/{Guid.NewGuid()}/rsvps/export");

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }
}

/// <summary>
/// Test host: swaps the DbContext for an isolated in-memory database and makes a
/// stub authentication scheme the default, so authenticated endpoints run without
/// a real Auth0 token. The caller is always <see cref="TestAuthHandler.OrganizerAuth0Id"/>.
/// </summary>
public sealed class AuthenticatedApiFactory : WebApplicationFactory<global::Program>
{
    private readonly string _dbName = $"api-auth-tests-{Guid.NewGuid():N}";

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.UseEnvironment("Development");

        builder.ConfigureAppConfiguration((_, config) =>
        {
            config.AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["ConnectionStrings:DefaultConnection"] = "Server=(localdb)\\ignored;Database=ignored",
                ["Auth0:Domain"] = "example.auth0.com",
                ["Auth0:Audience"] = "https://eventsync-api",
            });
        });

        builder.ConfigureServices(services =>
        {
            var toRemove = services
                .Where(d => d.ServiceType == typeof(AppDbContext)
                            || (d.ServiceType.FullName?.Contains("DbContextOptions") ?? false))
                .ToList();
            foreach (var descriptor in toRemove)
            {
                services.Remove(descriptor);
            }

            services.AddDbContext<AppDbContext>(options => options.UseInMemoryDatabase(_dbName));

            // Register the stub scheme as the default so RequireAuthorization() uses it.
            services.AddAuthentication(TestAuthHandler.SchemeName)
                .AddScheme<AuthenticationSchemeOptions, TestAuthHandler>(TestAuthHandler.SchemeName, _ => { });
        });
    }

    /// <summary>Seeds an event owned by the authenticated test caller.</summary>
    public Guid SeedOwnedEvent(int goingCount)
    {
        using var scope = Services.CreateScope();
        var ctx = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var (_, eventId) = TestData.SeedEvent(
            ctx, maxAttendees: null, goingCount: goingCount,
            organizerAuth0Id: TestAuthHandler.OrganizerAuth0Id);
        return eventId;
    }

    /// <summary>Seeds an event owned by a different organizer (for the 403 case).</summary>
    public Guid SeedForeignEvent()
    {
        using var scope = Services.CreateScope();
        var ctx = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var (_, eventId) = TestData.SeedEvent(ctx, maxAttendees: null, goingCount: 1);
        return eventId;
    }
}

/// <summary>Authenticates every request as a fixed organizer identity.</summary>
public sealed class TestAuthHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
    public const string SchemeName = "Test";
    public const string OrganizerAuth0Id = "auth0|test-organizer";

    public TestAuthHandler(
        IOptionsMonitor<AuthenticationSchemeOptions> options,
        ILoggerFactory logger,
        UrlEncoder encoder)
        : base(options, logger, encoder)
    {
    }

    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        var identity = new ClaimsIdentity(
            [new Claim(ClaimTypes.NameIdentifier, OrganizerAuth0Id)],
            SchemeName);
        var ticket = new AuthenticationTicket(new ClaimsPrincipal(identity), SchemeName);
        return Task.FromResult(AuthenticateResult.Success(ticket));
    }
}
