// Generated by GitHub Copilot
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.RSVPs.ExportRsvps;

namespace EventSync.Api.Tests;

/// <summary>
/// Tests for <see cref="ExportRsvpsHandler"/> — CSV content, escaping, injection
/// hardening, file naming, and organizer authorization.
/// </summary>
public sealed class ExportRsvpsTests
{
    private const string Header = "Name,Email,Status,Note,RespondedAtUtc,UpdatedAtUtc";

    private static ExportRsvpsHandler HandlerFor(AppDbContext ctx, User asUser) =>
        new(ctx, new FakeCurrentUserService(asUser));

    private static void AddRsvp(
        AppDbContext ctx, Guid eventId, string name, string? email,
        RsvpStatus status, string? note, DateTime respondedAt)
    {
        ctx.Rsvps.Add(new Rsvp
        {
            Id = Guid.NewGuid(),
            EventId = eventId,
            GuestName = name,
            GuestEmail = email,
            Status = status,
            Note = note,
            RespondedAt = respondedAt,
        });
        ctx.SaveChanges();
    }

    [Fact]
    public async Task Export_WritesHeaderAndRows_OrderedByRespondedAt_WithFriendlyStatusAndUtcDates()
    {
        using var ctx = TestData.CreateContext();
        var (_, eventId) = TestData.SeedEvent(ctx, maxAttendees: null);
        var organizer = ctx.Users.Single();

        var t = new DateTime(2026, 9, 29, 8, 30, 0, DateTimeKind.Utc);
        // Added out of order to prove the handler sorts by RespondedAt ascending.
        AddRsvp(ctx, eventId, "Bob", null, RsvpStatus.NotGoing, null, t.AddMinutes(5));
        AddRsvp(ctx, eventId, "Alice", "alice@test.local", RsvpStatus.Going, null, t);

        var result = await HandlerFor(ctx, organizer).Handle(new ExportRsvpsQuery(eventId), CancellationToken.None);

        var lines = result.Csv.Split("\r\n", StringSplitOptions.RemoveEmptyEntries);
        Assert.Equal(Header, lines[0]);
        Assert.Equal("Alice,alice@test.local,Going,,2026-09-29 08:30:00Z,", lines[1]);
        Assert.Equal("Bob,,Not Going,,2026-09-29 08:35:00Z,", lines[2]);
        Assert.StartsWith("rsvps-test-event-", result.FileName);
        Assert.EndsWith(".csv", result.FileName);
    }

    [Fact]
    public async Task Export_QuotesFieldsContainingCommasAndDoublesInnerQuotes()
    {
        using var ctx = TestData.CreateContext();
        var (_, eventId) = TestData.SeedEvent(ctx, maxAttendees: null);
        var organizer = ctx.Users.Single();
        AddRsvp(ctx, eventId, "Doe, Jane", null, RsvpStatus.Maybe, "She said \"hi\"", DateTime.UtcNow);

        var result = await HandlerFor(ctx, organizer).Handle(new ExportRsvpsQuery(eventId), CancellationToken.None);

        Assert.Contains("\"Doe, Jane\"", result.Csv);
        Assert.Contains("\"She said \"\"hi\"\"\"", result.Csv);
    }

    [Fact]
    public async Task Export_NeutralizesFormulaInjection()
    {
        using var ctx = TestData.CreateContext();
        var (_, eventId) = TestData.SeedEvent(ctx, maxAttendees: null);
        var organizer = ctx.Users.Single();
        AddRsvp(ctx, eventId, "=1+1", null, RsvpStatus.Going, "@cmd", DateTime.UtcNow);

        var result = await HandlerFor(ctx, organizer).Handle(new ExportRsvpsQuery(eventId), CancellationToken.None);

        // Leading =, +, -, @ are prefixed with a single quote so spreadsheets don't execute them.
        Assert.Contains("'=1+1", result.Csv);
        Assert.Contains("'@cmd", result.Csv);
    }

    [Fact]
    public async Task Export_EmptyEvent_ReturnsHeaderOnly()
    {
        using var ctx = TestData.CreateContext();
        var (_, eventId) = TestData.SeedEvent(ctx, maxAttendees: null);
        var organizer = ctx.Users.Single();

        var result = await HandlerFor(ctx, organizer).Handle(new ExportRsvpsQuery(eventId), CancellationToken.None);

        var lines = result.Csv.Split("\r\n", StringSplitOptions.RemoveEmptyEntries);
        Assert.Single(lines);
        Assert.Equal(Header, lines[0]);
    }

    [Fact]
    public async Task Export_ByNonOrganizer_ThrowsUnauthorized()
    {
        using var ctx = TestData.CreateContext();
        var (_, eventId) = TestData.SeedEvent(ctx, maxAttendees: null);
        var stranger = new User { Id = Guid.NewGuid(), Auth0Id = "auth0|stranger", Email = "x@test.local", DisplayName = "Stranger" };

        await Assert.ThrowsAsync<UnauthorizedAccessException>(
            () => HandlerFor(ctx, stranger).Handle(new ExportRsvpsQuery(eventId), CancellationToken.None));
    }

    [Fact]
    public async Task Export_MissingEvent_ThrowsKeyNotFound()
    {
        using var ctx = TestData.CreateContext();
        TestData.SeedEvent(ctx, maxAttendees: null);
        var organizer = ctx.Users.Single();

        await Assert.ThrowsAsync<KeyNotFoundException>(
            () => HandlerFor(ctx, organizer).Handle(new ExportRsvpsQuery(Guid.NewGuid()), CancellationToken.None));
    }
}
