// Generated by GitHub Copilot
using EventSync.Api.Common.Services;
using EventSync.Api.Data.Entities;

namespace EventSync.Api.Tests;

/// <summary>
/// Test double for <see cref="ICurrentUserService"/> that returns a fixed user,
/// so handlers depending on the current identity can be exercised without an
/// HTTP context or JWT.
/// </summary>
internal sealed class FakeCurrentUserService : ICurrentUserService
{
    private readonly User _user;

    public FakeCurrentUserService(User user) => _user = user;

    public string? Auth0Id => _user.Auth0Id;

    public string? Email => _user.Email;

    public string? Name => _user.DisplayName;

    public string? Picture => _user.AvatarUrl;

    public bool IsAuthenticated => true;

    public Task<User> GetOrCreateUserAsync(CancellationToken cancellationToken = default) =>
        Task.FromResult(_user);
}
