// Generated by GitHub Copilot
using EventSync.Api.Common.Exceptions;
using EventSync.Api.Data;
using EventSync.Api.Features.RSVPs.Common;
using EventSync.Api.Features.RSVPs.GetEventCalendar;

namespace EventSync.Api.Tests;

/// <summary>
/// Tests for <see cref="GetEventCalendarHandler"/> — iCalendar structure, floating
/// (zone-less) times, RFC 5545 text escaping, cancelled events, and invalid tokens.
/// </summary>
public sealed class GetEventCalendarTests
{
    private static GetEventCalendarHandler HandlerFor(AppDbContext ctx) =>
        new(new InviteValidationService(ctx));

    private static string DtStartLine(string ics) =>
        ics.Split("\r\n").Single(l => l.StartsWith("DTSTART:", StringComparison.Ordinal));

    [Fact]
    public async Task Calendar_HasValidVCalendarAndVEventStructure()
    {
        using var ctx = TestData.CreateContext();
        var (token, _) = TestData.SeedEvent(ctx, maxAttendees: null);

        var result = await HandlerFor(ctx).Handle(new GetEventCalendarQuery(token), CancellationToken.None);
        var ics = result.Content;

        Assert.EndsWith(".ics", result.FileName);
        Assert.StartsWith("BEGIN:VCALENDAR\r\n", ics);
        Assert.EndsWith("END:VCALENDAR\r\n", ics);
        Assert.Contains("VERSION:2.0\r\n", ics);
        Assert.Contains("BEGIN:VEVENT\r\n", ics);
        Assert.Contains("END:VEVENT\r\n", ics);
        Assert.Contains($"UID:{token}@eventsync\r\n", ics);
        Assert.Contains("SUMMARY:Test Event\r\n", ics);
        Assert.Contains("STATUS:CONFIRMED\r\n", ics);
        Assert.Contains("DTEND:", ics);
    }

    [Fact]
    public async Task Calendar_UsesFloatingLocalTime_ForDtStart()
    {
        using var ctx = TestData.CreateContext();
        var (token, _) = TestData.SeedEvent(ctx, maxAttendees: null);

        var result = await HandlerFor(ctx).Handle(new GetEventCalendarQuery(token), CancellationToken.None);

        var dtstart = DtStartLine(result.Content);
        // Floating time has no trailing 'Z' (and no TZID); pattern is yyyyMMddTHHmmss.
        Assert.Matches(@"^DTSTART:\d{8}T\d{6}$", dtstart);
    }

    [Fact]
    public async Task Calendar_EscapesTextFields_PerRfc5545()
    {
        using var ctx = TestData.CreateContext();
        var (token, eventId) = TestData.SeedEvent(ctx, maxAttendees: null);
        var ev = ctx.Events.Single(e => e.Id == eventId);
        ev.Title = "Party, Inc; big";
        ev.Location = "Hall A; Room 1, Bldg 2";
        ev.Description = "Line one\nLine two";
        ctx.SaveChanges();

        var result = await HandlerFor(ctx).Handle(new GetEventCalendarQuery(token), CancellationToken.None);
        var ics = result.Content;

        Assert.Contains(@"SUMMARY:Party\, Inc\; big", ics);
        Assert.Contains(@"LOCATION:Hall A\; Room 1\, Bldg 2", ics);
        Assert.Contains(@"DESCRIPTION:Line one\nLine two", ics);
    }

    [Fact]
    public async Task Calendar_ForCancelledEvent_MarksStatusCancelled()
    {
        using var ctx = TestData.CreateContext();
        var (token, _) = TestData.SeedEvent(ctx, maxAttendees: null, isCancelled: true);

        var result = await HandlerFor(ctx).Handle(new GetEventCalendarQuery(token), CancellationToken.None);

        Assert.Contains("STATUS:CANCELLED\r\n", result.Content);
        Assert.Contains("SUMMARY:Cancelled: Test Event\r\n", result.Content);
    }

    [Fact]
    public async Task Calendar_ForUnknownToken_ThrowsInvalidInvite()
    {
        using var ctx = TestData.CreateContext();

        await Assert.ThrowsAsync<InvalidInviteException>(
            () => HandlerFor(ctx).Handle(new GetEventCalendarQuery("does-not-exist"), CancellationToken.None));
    }
}
