// Generated by GitHub Copilot
using System.Net;

namespace EventSync.Api.Tests;

/// <summary>
/// Exercises the public iCalendar endpoint over real HTTP via the shared
/// anonymous test host, verifying the status, the <c>text/calendar</c> content
/// type, the download disposition, and the .ics body — plus the 410 path.
/// </summary>
public sealed class GetEventCalendarEndpointTests
{
    [Fact]
    public async Task Calendar_ForValidToken_Returns200_AsCalendarAttachment()
    {
        using var factory = new CapacityApiFactory();
        var (token, _) = factory.Seed(maxAttendees: null, goingCount: 0);
        var client = factory.CreateClient();

        var response = await client.GetAsync($"/api/v1/invite/{token}/calendar.ics");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        Assert.Equal("text/calendar", response.Content.Headers.ContentType?.MediaType);

        var fileName = response.Content.Headers.ContentDisposition?.FileName
            ?? response.Content.Headers.ContentDisposition?.FileNameStar;
        Assert.NotNull(fileName);
        Assert.Contains(".ics", fileName);

        var body = await response.Content.ReadAsStringAsync();
        Assert.Contains("BEGIN:VCALENDAR", body);
        Assert.Contains("BEGIN:VEVENT", body);
        Assert.Contains("SUMMARY:Test Event", body);
    }

    [Fact]
    public async Task Calendar_ForUnknownToken_Returns410()
    {
        using var factory = new CapacityApiFactory();
        var client = factory.CreateClient();

        var response = await client.GetAsync("/api/v1/invite/does-not-exist/calendar.ics");

        Assert.Equal(HttpStatusCode.Gone, response.StatusCode);
    }
}
