// Generated by GitHub Copilot
using System.Net;

namespace EventSync.Api.Tests;

/// <summary>
/// Exercises the public QR-code endpoint over real HTTP via the shared anonymous
/// test host: a valid token returns a PNG image, an unknown token returns 410.
/// </summary>
public sealed class GetInviteQrCodeEndpointTests
{
    private static readonly byte[] PngSignature =
        [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];

    [Fact]
    public async Task Qr_ForValidToken_Returns200_AsPng()
    {
        using var factory = new CapacityApiFactory();
        var (token, _) = factory.Seed(maxAttendees: null, goingCount: 0);
        var client = factory.CreateClient();

        var response = await client.GetAsync($"/api/v1/invite/{token}/qr.png");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        Assert.Equal("image/png", response.Content.Headers.ContentType?.MediaType);

        var bytes = await response.Content.ReadAsByteArrayAsync();
        Assert.True(bytes.Length > PngSignature.Length);
        Assert.Equal(PngSignature, bytes.Take(PngSignature.Length).ToArray());
    }

    [Fact]
    public async Task Qr_ForUnknownToken_Returns410()
    {
        using var factory = new CapacityApiFactory();
        var client = factory.CreateClient();

        var response = await client.GetAsync("/api/v1/invite/does-not-exist/qr.png");

        Assert.Equal(HttpStatusCode.Gone, response.StatusCode);
    }
}
