// Generated by GitHub Copilot
using EventSync.Api.Common.Configuration;
using EventSync.Api.Common.Exceptions;
using EventSync.Api.Data;
using EventSync.Api.Features.InviteLinks.GetInviteQrCode;
using EventSync.Api.Features.RSVPs.Common;
using Microsoft.Extensions.Options;

namespace EventSync.Api.Tests;

/// <summary>
/// Tests for <see cref="GetInviteQrCodeHandler"/> — valid PNG output and the
/// invalid/inactive-token guard.
/// </summary>
public sealed class GetInviteQrCodeTests
{
    private static readonly byte[] PngSignature =
        [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];

    private static GetInviteQrCodeHandler HandlerFor(AppDbContext ctx) =>
        new(new InviteValidationService(ctx),
            Options.Create(new FrontendOptions { BaseUrl = "http://localhost:4200" }));

    [Fact]
    public async Task Qr_ForValidToken_ReturnsPngImageBytes()
    {
        using var ctx = TestData.CreateContext();
        var (token, _) = TestData.SeedEvent(ctx, maxAttendees: null);

        var result = await HandlerFor(ctx).Handle(new GetInviteQrCodeQuery(token), CancellationToken.None);

        Assert.EndsWith(".png", result.FileName);
        Assert.True(result.Png.Length > PngSignature.Length);
        Assert.Equal(PngSignature, result.Png.Take(PngSignature.Length).ToArray());
    }

    [Fact]
    public async Task Qr_ForUnknownToken_ThrowsInvalidInvite()
    {
        using var ctx = TestData.CreateContext();

        await Assert.ThrowsAsync<InvalidInviteException>(
            () => HandlerFor(ctx).Handle(new GetInviteQrCodeQuery("does-not-exist"), CancellationToken.None));
    }

    [Fact]
    public async Task Qr_ForDeactivatedLink_ThrowsInvalidInvite()
    {
        using var ctx = TestData.CreateContext();
        var (token, _) = TestData.SeedEvent(ctx, maxAttendees: null);
        var link = ctx.InviteLinks.Single();
        link.IsActive = false;
        ctx.SaveChanges();

        await Assert.ThrowsAsync<InvalidInviteException>(
            () => HandlerFor(ctx).Handle(new GetInviteQrCodeQuery(token), CancellationToken.None));
    }
}
