// Generated by GitHub Copilot
using EventSync.Api.Features.RSVPs.Common;
using EventSync.Api.Features.RSVPs.GetPublicEvent;

namespace EventSync.Api.Tests;

/// <summary>
/// Tests for the availability fields (<c>MaxAttendees</c>, <c>SpotsRemaining</c>,
/// <c>IsFull</c>) that <see cref="GetPublicEventHandler"/> projects onto
/// <see cref="PublicEventDto"/> so the public invite page can show remaining seats.
/// </summary>
public sealed class GetPublicEventAvailabilityTests
{
    private static GetPublicEventHandler CreateHandler(EventSync.Api.Data.AppDbContext context) =>
        new(new InviteValidationService(context), context);

    [Fact]
    public async Task UncappedEvent_ReportsUnlimited()
    {
        using var context = TestData.CreateContext();
        var (token, _) = TestData.SeedEvent(context, maxAttendees: null, goingCount: 5);
        var handler = CreateHandler(context);

        var dto = await handler.Handle(new GetPublicEventQuery(token), CancellationToken.None);

        Assert.Null(dto.MaxAttendees);
        Assert.Null(dto.SpotsRemaining);
        Assert.False(dto.IsFull);
    }

    [Fact]
    public async Task CappedEventWithRoom_ReportsRemainingSpots()
    {
        using var context = TestData.CreateContext();
        var (token, _) = TestData.SeedEvent(context, maxAttendees: 10, goingCount: 4);
        var handler = CreateHandler(context);

        var dto = await handler.Handle(new GetPublicEventQuery(token), CancellationToken.None);

        Assert.Equal(10, dto.MaxAttendees);
        Assert.Equal(6, dto.SpotsRemaining);
        Assert.False(dto.IsFull);
    }

    [Fact]
    public async Task FullEvent_ReportsZeroSpotsAndIsFull()
    {
        using var context = TestData.CreateContext();
        var (token, _) = TestData.SeedEvent(context, maxAttendees: 3, goingCount: 3);
        var handler = CreateHandler(context);

        var dto = await handler.Handle(new GetPublicEventQuery(token), CancellationToken.None);

        Assert.Equal(0, dto.SpotsRemaining);
        Assert.True(dto.IsFull);
    }

    [Fact]
    public async Task SpotsRemaining_NeverGoesNegative_WhenOverbooked()
    {
        using var context = TestData.CreateContext();
        // Defensive: if a cap were lowered below the current headcount, remaining
        // must floor at 0 rather than report a negative number.
        var (token, _) = TestData.SeedEvent(context, maxAttendees: 2, goingCount: 5);
        var handler = CreateHandler(context);

        var dto = await handler.Handle(new GetPublicEventQuery(token), CancellationToken.None);

        Assert.Equal(0, dto.SpotsRemaining);
        Assert.True(dto.IsFull);
    }
}
