// Generated by GitHub Copilot
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace EventSync.Api.Tests;

/// <summary>
/// Boots the real API in-process via <see cref="WebApplicationFactory{TEntryPoint}"/>
/// (backed by an in-memory database) and exercises the public invite endpoints over
/// HTTP. This verifies the parts unit tests can't: the 409 status mapping through the
/// exception middleware, the RFC 7807 <c>problem+json</c> body, and JSON serialization
/// of the new availability fields.
/// </summary>
public sealed class RsvpCapacityEndpointTests
{
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    [Fact]
    public async Task PublicEvent_WhenFull_ReportsIsFull_AndGoingReturns409()
    {
        using var factory = new CapacityApiFactory();
        var (token, _) = factory.Seed(maxAttendees: 1, goingCount: 1);
        var client = factory.CreateClient();

        // GET the public projection — availability must reflect a full event.
        var getResponse = await client.GetAsync($"/api/v1/invite/{token}");
        Assert.Equal(HttpStatusCode.OK, getResponse.StatusCode);

        var eventPayload = await getResponse.Content.ReadFromJsonAsync<JsonElement>(Json);
        Assert.Equal(1, eventPayload.GetProperty("maxAttendees").GetInt32());
        Assert.Equal(0, eventPayload.GetProperty("spotsRemaining").GetInt32());
        Assert.True(eventPayload.GetProperty("isFull").GetBoolean());

        // POST a "Going" RSVP — must be rejected as 409 Conflict (problem+json).
        var goingResponse = await client.PostAsJsonAsync(
            $"/api/v1/invite/{token}/rsvp",
            new { guestName = "Late Guest", status = (int)RsvpStatus.Going });

        Assert.Equal(HttpStatusCode.Conflict, goingResponse.StatusCode);
        Assert.Equal("application/problem+json", goingResponse.Content.Headers.ContentType?.MediaType);

        var problem = await goingResponse.Content.ReadFromJsonAsync<JsonElement>(Json);
        Assert.Equal("Event is full", problem.GetProperty("title").GetString());
        Assert.Equal(409, problem.GetProperty("status").GetInt32());
    }

    [Fact]
    public async Task Maybe_ToFullEvent_Returns201()
    {
        using var factory = new CapacityApiFactory();
        var (token, _) = factory.Seed(maxAttendees: 1, goingCount: 1);
        var client = factory.CreateClient();

        var response = await client.PostAsJsonAsync(
            $"/api/v1/invite/{token}/rsvp",
            new { guestName = "Maybe Guest", status = (int)RsvpStatus.Maybe });

        Assert.Equal(HttpStatusCode.Created, response.StatusCode);
    }

    [Fact]
    public async Task Going_UnderCapacity_Returns201_AndSpotsDecrement()
    {
        using var factory = new CapacityApiFactory();
        var (token, _) = factory.Seed(maxAttendees: 2, goingCount: 0);
        var client = factory.CreateClient();

        var postResponse = await client.PostAsJsonAsync(
            $"/api/v1/invite/{token}/rsvp",
            new { guestName = "Early Guest", status = (int)RsvpStatus.Going });
        Assert.Equal(HttpStatusCode.Created, postResponse.StatusCode);

        // Re-read the public event — one spot should now be consumed.
        var getResponse = await client.GetAsync($"/api/v1/invite/{token}");
        var payload = await getResponse.Content.ReadFromJsonAsync<JsonElement>(Json);
        Assert.Equal(1, payload.GetProperty("spotsRemaining").GetInt32());
        Assert.False(payload.GetProperty("isFull").GetBoolean());
    }

    [Fact]
    public async Task UncappedEvent_ReportsUnlimited_AndAcceptsGoing()
    {
        using var factory = new CapacityApiFactory();
        var (token, _) = factory.Seed(maxAttendees: null, goingCount: 3);
        var client = factory.CreateClient();

        var getResponse = await client.GetAsync($"/api/v1/invite/{token}");
        var payload = await getResponse.Content.ReadFromJsonAsync<JsonElement>(Json);
        Assert.Equal(JsonValueKind.Null, payload.GetProperty("maxAttendees").ValueKind);
        Assert.Equal(JsonValueKind.Null, payload.GetProperty("spotsRemaining").ValueKind);
        Assert.False(payload.GetProperty("isFull").GetBoolean());

        var postResponse = await client.PostAsJsonAsync(
            $"/api/v1/invite/{token}/rsvp",
            new { guestName = "Any Guest", status = (int)RsvpStatus.Going });
        Assert.Equal(HttpStatusCode.Created, postResponse.StatusCode);
    }
}

/// <summary>
/// A test host that swaps the SQL Server <see cref="AppDbContext"/> registration for an
/// isolated in-memory database and supplies dummy Auth0 / connection-string configuration
/// (only anonymous endpoints are exercised, so no real tokens are needed).
/// </summary>
public sealed class CapacityApiFactory : WebApplicationFactory<global::Program>
{
    private readonly string _dbName = $"api-tests-{Guid.NewGuid():N}";

    /// <inheritdoc/>
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        // Development skips the auto-migrate block (unsupported on InMemory) and HSTS/HTTPS.
        builder.UseEnvironment("Development");

        builder.ConfigureAppConfiguration((_, config) =>
        {
            config.AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["ConnectionStrings:DefaultConnection"] = "Server=(localdb)\\ignored;Database=ignored",
                ["Auth0:Domain"] = "example.auth0.com",
                ["Auth0:Audience"] = "https://eventsync-api",
            });
        });

        builder.ConfigureServices(services =>
        {
            // Remove the SQL Server context, its options, and the EF Core options-configuration
            // singleton so InMemory becomes the single registered provider.
            var toRemove = services
                .Where(d => d.ServiceType == typeof(AppDbContext)
                            || (d.ServiceType.FullName?.Contains("DbContextOptions") ?? false))
                .ToList();
            foreach (var descriptor in toRemove)
            {
                services.Remove(descriptor);
            }

            services.AddDbContext<AppDbContext>(options => options.UseInMemoryDatabase(_dbName));
        });
    }

    /// <summary>Seeds an event + active invite link in the host's in-memory database.</summary>
    public (string Token, Guid EventId) Seed(int? maxAttendees, int goingCount = 0, bool isCancelled = false)
    {
        using var scope = Services.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        return TestData.SeedEvent(context, maxAttendees, goingCount, isCancelled);
    }
}
