// Generated by GitHub Copilot
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.RSVPs.Common;
using EventSync.Api.Features.RSVPs.SubmitRsvp;

namespace EventSync.Api.Tests;

/// <summary>
/// Guards the server-generated RSVP timestamp against a regression to
/// <c>DateTime.Now</c>. Asserting the <see cref="DateTimeKind"/> is deterministic
/// across machines: <c>DateTime.UtcNow</c> yields <see cref="DateTimeKind.Utc"/>
/// while <c>DateTime.Now</c> yields <see cref="DateTimeKind.Local"/>, so this fails
/// even on a UTC-configured host (where the two values would otherwise be equal).
/// </summary>
public sealed class SubmitRsvpTimestampTests
{
    [Fact]
    public async Task SubmitRsvp_RecordsRespondedAt_InUtc()
    {
        using var context = TestData.CreateContext();
        var (token, _) = TestData.SeedEvent(context, maxAttendees: null);
        var handler = new SubmitRsvpHandler(context, new InviteValidationService(context));

        await handler.Handle(
            new SubmitRsvpCommand(token, "Zed", GuestEmail: null, RsvpStatus.Going, Note: null),
            CancellationToken.None);

        var rsvp = context.Rsvps.Single(r => r.GuestName == "Zed");
        Assert.Equal(DateTimeKind.Utc, rsvp.RespondedAt.Kind);
    }
}
