// Generated by GitHub Copilot
using EventSync.Api.Common.Exceptions;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.RSVPs.Common;
using EventSync.Api.Features.RSVPs.SubmitRsvp;

namespace EventSync.Api.Tests;

/// <summary>
/// Behavioural tests for <see cref="SubmitRsvpHandler"/>'s attendee-capacity
/// enforcement (Event.MaxAttendees). Uses the real
/// <see cref="InviteValidationService"/> against an in-memory database so the
/// tests exercise the same token-validation + counting path as production.
/// </summary>
public sealed class SubmitRsvpCapacityTests
{
    private static SubmitRsvpHandler CreateHandler(EventSync.Api.Data.AppDbContext context) =>
        new(context, new InviteValidationService(context));

    private static SubmitRsvpCommand Going(string token, string name, string? email = null) =>
        new(token, name, email, RsvpStatus.Going, Note: null);

    [Fact]
    public async Task Going_WhenUnderCapacity_IsAccepted()
    {
        using var context = TestData.CreateContext();
        var (token, eventId) = TestData.SeedEvent(context, maxAttendees: 3, goingCount: 1);
        var handler = CreateHandler(context);

        var result = await handler.Handle(Going(token, "Alice"), CancellationToken.None);

        Assert.Equal(RsvpStatus.Going, result.Status);
        Assert.Equal(2, TestData.GoingCount(context, eventId));
    }

    [Fact]
    public async Task Going_ThatFillsTheLastSpot_IsAccepted()
    {
        using var context = TestData.CreateContext();
        var (token, eventId) = TestData.SeedEvent(context, maxAttendees: 2, goingCount: 1);
        var handler = CreateHandler(context);

        await handler.Handle(Going(token, "Bob"), CancellationToken.None);

        Assert.Equal(2, TestData.GoingCount(context, eventId));
    }

    [Fact]
    public async Task Going_WhenEventIsFull_ThrowsEventFull()
    {
        using var context = TestData.CreateContext();
        var (token, eventId) = TestData.SeedEvent(context, maxAttendees: 2, goingCount: 2);
        var handler = CreateHandler(context);

        await Assert.ThrowsAsync<EventFullException>(
            () => handler.Handle(Going(token, "Carol"), CancellationToken.None));

        // The rejected RSVP must not have been persisted.
        Assert.Equal(2, TestData.GoingCount(context, eventId));
        Assert.Null(context.Rsvps.FirstOrDefault(r => r.GuestName == "Carol"));
    }

    [Fact]
    public async Task Maybe_WhenEventIsFull_IsAccepted()
    {
        using var context = TestData.CreateContext();
        var (token, eventId) = TestData.SeedEvent(context, maxAttendees: 1, goingCount: 1);
        var handler = CreateHandler(context);

        var result = await handler.Handle(
            new SubmitRsvpCommand(token, "Dana", GuestEmail: null, RsvpStatus.Maybe, Note: null),
            CancellationToken.None);

        Assert.Equal(RsvpStatus.Maybe, result.Status);
        // A "Maybe" does not consume a seat, so the Going count is unchanged.
        Assert.Equal(1, TestData.GoingCount(context, eventId));
    }

    [Fact]
    public async Task NotGoing_WhenEventIsFull_IsAccepted()
    {
        using var context = TestData.CreateContext();
        var (token, eventId) = TestData.SeedEvent(context, maxAttendees: 1, goingCount: 1);
        var handler = CreateHandler(context);

        var result = await handler.Handle(
            new SubmitRsvpCommand(token, "Erin", GuestEmail: null, RsvpStatus.NotGoing, Note: null),
            CancellationToken.None);

        Assert.Equal(RsvpStatus.NotGoing, result.Status);
        Assert.Equal(1, TestData.GoingCount(context, eventId));
    }

    [Fact]
    public async Task Going_WhenCapacityIsUnlimited_IsAlwaysAccepted()
    {
        using var context = TestData.CreateContext();
        var (token, eventId) = TestData.SeedEvent(context, maxAttendees: null, goingCount: 50);
        var handler = CreateHandler(context);

        await handler.Handle(Going(token, "Frank"), CancellationToken.None);

        Assert.Equal(51, TestData.GoingCount(context, eventId));
    }

    [Fact]
    public async Task ExistingGoingGuest_UpdatingDetails_WhenFull_KeepsTheirSpot()
    {
        using var context = TestData.CreateContext();
        // Capacity 1, and the only spot is already held by this guest (via email).
        var (token, eventId) = TestData.SeedEvent(context, maxAttendees: 1, goingCount: 0);
        TestData.AddRsvp(context, eventId, "Grace", "grace@test.local", RsvpStatus.Going);
        var handler = CreateHandler(context);

        // Re-submitting Going with an updated note must not lock the guest out of
        // the full event (they are excluded from their own capacity check).
        var result = await handler.Handle(
            new SubmitRsvpCommand(token, "Grace Hopper", "grace@test.local", RsvpStatus.Going, "Running late"),
            CancellationToken.None);

        Assert.Equal(RsvpStatus.Going, result.Status);
        Assert.Equal("Grace Hopper", result.GuestName);
        Assert.Equal(1, TestData.GoingCount(context, eventId));
        Assert.Equal("Running late", context.Rsvps.Single(r => r.GuestEmail == "grace@test.local").Note);
    }

    [Fact]
    public async Task ExistingMaybeGuest_SwitchingToGoing_WhenFull_ThrowsEventFull()
    {
        using var context = TestData.CreateContext();
        // One anonymous guest holds the single seat; this guest was "Maybe".
        var (token, eventId) = TestData.SeedEvent(context, maxAttendees: 1, goingCount: 1);
        TestData.AddRsvp(context, eventId, "Heidi", "heidi@test.local", RsvpStatus.Maybe);
        var handler = CreateHandler(context);

        await Assert.ThrowsAsync<EventFullException>(
            () => handler.Handle(Going(token, "Heidi", "heidi@test.local"), CancellationToken.None));

        // Heidi should remain "Maybe" — the switch was rejected.
        Assert.Equal(RsvpStatus.Maybe, context.Rsvps.Single(r => r.GuestEmail == "heidi@test.local").Status);
    }

    [Fact]
    public async Task ExistingNotGoingGuest_SwitchingToGoing_WhenSpotIsFree_IsAccepted()
    {
        using var context = TestData.CreateContext();
        // Capacity 2, one anonymous guest going; this guest previously declined.
        var (token, eventId) = TestData.SeedEvent(context, maxAttendees: 2, goingCount: 1);
        TestData.AddRsvp(context, eventId, "Ivan", "ivan@test.local", RsvpStatus.NotGoing);
        var handler = CreateHandler(context);

        var result = await handler.Handle(Going(token, "Ivan", "ivan@test.local"), CancellationToken.None);

        Assert.Equal(RsvpStatus.Going, result.Status);
        Assert.Equal(2, TestData.GoingCount(context, eventId));
    }
}
