// Generated by GitHub Copilot
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Tests;

/// <summary>
/// Test helpers for building an isolated in-memory <see cref="AppDbContext"/> and
/// seeding the minimal object graph (organizer → event → invite link → RSVPs)
/// that the RSVP handlers operate on.
/// </summary>
/// <remarks>
/// Each context uses a uniquely-named in-memory database so tests are fully
/// isolated and can run in parallel. The in-memory provider does not enforce
/// unique indexes or foreign keys, which is fine here — the behaviour under test
/// (capacity counting) depends only on LINQ query results, not DB constraints.
/// A dedicated <see cref="EventType"/> with a high id (99) is added so it never
/// collides with the lookup rows the model seeds via <c>HasData</c>.
/// </remarks>
internal static class TestData
{
    /// <summary>Creates a fresh in-memory context backed by a unique database.</summary>
    public static AppDbContext CreateContext() =>
        new(new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase($"eventsync-tests-{Guid.NewGuid():N}")
            .Options);

    /// <summary>
    /// Seeds one event (with an active, non-expiring invite link) plus
    /// <paramref name="goingCount"/> pre-existing "Going" RSVPs that have no email.
    /// </summary>
    /// <param name="context">Target context.</param>
    /// <param name="maxAttendees">Capacity cap; <c>null</c> means unlimited.</param>
    /// <param name="goingCount">Number of anonymous "Going" RSVPs to pre-seed.</param>
    /// <param name="isCancelled">Whether the event is cancelled.</param>
    /// <returns>The generated invite token and the event id.</returns>
    public static (string Token, Guid EventId) SeedEvent(
        AppDbContext context,
        int? maxAttendees,
        int goingCount = 0,
        bool isCancelled = false)
    {
        var organizer = new User
        {
            Id = Guid.NewGuid(),
            Auth0Id = $"auth0|{Guid.NewGuid():N}",
            Email = "organizer@test.local",
            DisplayName = "Test Organizer",
            CreatedAt = DateTime.UtcNow,
        };

        var eventType = new EventType { Id = 99, Name = "Test Type", Icon = "🎉" };

        var ev = new Event
        {
            Id = Guid.NewGuid(),
            OrganizerId = organizer.Id,
            Organizer = organizer,
            EventTypeId = eventType.Id,
            EventType = eventType,
            Title = "Test Event",
            OrganizerName = "Test Organizer",
            StartDate = DateTime.UtcNow.AddDays(7),
            CreatedAt = DateTime.UtcNow,
            MaxAttendees = maxAttendees,
            IsCancelled = isCancelled,
        };

        var link = new InviteLink
        {
            Id = Guid.NewGuid(),
            EventId = ev.Id,
            Event = ev,
            Token = $"tok-{Guid.NewGuid():N}",
            IsActive = true,
            CreatedAt = DateTime.UtcNow,
        };

        context.Users.Add(organizer);
        context.EventTypes.Add(eventType);
        context.Events.Add(ev);
        context.InviteLinks.Add(link);

        for (var i = 0; i < goingCount; i++)
        {
            context.Rsvps.Add(new Rsvp
            {
                Id = Guid.NewGuid(),
                EventId = ev.Id,
                InviteLinkId = link.Id,
                GuestName = $"Seeded Guest {i}",
                Status = RsvpStatus.Going,
                RespondedAt = DateTime.UtcNow,
            });
        }

        context.SaveChanges();
        return (link.Token, ev.Id);
    }

    /// <summary>Adds a single RSVP with a specific email + status and saves it.</summary>
    public static Guid AddRsvp(
        AppDbContext context,
        Guid eventId,
        string guestName,
        string? guestEmail,
        RsvpStatus status)
    {
        var rsvp = new Rsvp
        {
            Id = Guid.NewGuid(),
            EventId = eventId,
            GuestName = guestName,
            GuestEmail = guestEmail,
            Status = status,
            RespondedAt = DateTime.UtcNow,
        };
        context.Rsvps.Add(rsvp);
        context.SaveChanges();
        return rsvp.Id;
    }

    /// <summary>Counts the "Going" RSVPs currently stored for an event.</summary>
    public static int GoingCount(AppDbContext context, Guid eventId) =>
        context.Rsvps.Count(r => r.EventId == eventId && r.Status == RsvpStatus.Going);
}
