// Generated by GitHub Copilot
using System.Threading.RateLimiting;
using EventSync.Api.Common.Behaviors;
using EventSync.Api.Common.Configuration;
using EventSync.Api.Common.Middleware;
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Features.Auth;
using EventSync.Api.Features.Events;
using EventSync.Api.Features.EventTypes;
using EventSync.Api.Features.InviteLinks;
using EventSync.Api.Features.RSVPs;
using EventSync.Api.Features.RSVPs.Common;
using EventSync.Api.Features.Uploads;
using FluentValidation;
using FluentValidation.AspNetCore;
using MediatR;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.Filters;
using Microsoft.Extensions.FileProviders;

var builder = WebApplication.CreateBuilder(args);

// ---------------------------------------------------------------------------
// Service registration
// ---------------------------------------------------------------------------

// Force HTTP-only Kestrel binding on port 5000 for local development per spec.
// Production binding is taken from ASPNETCORE_URLS / hosting platform configuration.
if (builder.Environment.IsDevelopment())
{
    builder.WebHost.UseUrls("http://localhost:5000");
}

// EF Core (SQL Server / LocalDB).
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException("Missing connection string 'DefaultConnection'.");
builder.Services.AddDbContext<AppDbContext>(options => options.UseSqlServer(connectionString));

// MediatR — scan the current assembly for handlers/behaviors.
builder.Services.AddMediatR(cfg =>
{
    cfg.RegisterServicesFromAssembly(typeof(Program).Assembly);
    cfg.AddOpenBehavior(typeof(ValidationBehavior<,>));
});

// FluentValidation — automatic ASP.NET Core integration + assembly scanning.
builder.Services.AddFluentValidationAutoValidation();
builder.Services.AddValidatorsFromAssembly(typeof(Program).Assembly);

// Current-user service requires HTTP context access.
builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<ICurrentUserService, CurrentUserService>();

// Strongly-typed configuration sections.
builder.Services.Configure<FrontendOptions>(
    builder.Configuration.GetSection(FrontendOptions.SectionName));
builder.Services.Configure<SecurityHeadersOptions>(options =>
{
    builder.Configuration.GetSection(SecurityHeadersOptions.SectionName).Bind(options);
    // Default: derive Auth0 domain from the Auth0 section so CSP connect-src
    // automatically permits the configured tenant.
    if (string.IsNullOrWhiteSpace(options.Auth0Domain))
    {
        options.Auth0Domain = builder.Configuration["Auth0:Domain"];
    }
});

// Cryptographically-secure token generator (stateless — safe as a singleton).
builder.Services.AddSingleton<ITokenGenerator, TokenGenerator>();

// Invite-link validation lookup (DbContext-bound — must be scoped).
builder.Services.AddScoped<IInviteValidationService, InviteValidationService>();

// Forwarded headers — required when running behind a reverse proxy so
// Connection.RemoteIpAddress (used by the rate limiter) reflects the real client.
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    // Tighten in production via configuration: known proxies / networks.
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});

// ---------------------------------------------------------------------------
// Authentication / Authorization (Auth0 JWT bearer)
// ---------------------------------------------------------------------------
var auth0Domain = builder.Configuration["Auth0:Domain"]
    ?? throw new InvalidOperationException("Missing configuration 'Auth0:Domain'.");
var auth0Audience = builder.Configuration["Auth0:Audience"]
    ?? throw new InvalidOperationException("Missing configuration 'Auth0:Audience'.");

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.Authority = $"https://{auth0Domain}/";
        options.Audience = auth0Audience;
        options.RequireHttpsMetadata = !builder.Environment.IsDevelopment();

        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = $"https://{auth0Domain}/",
            ValidAudience = auth0Audience,
            NameClaimType = System.Security.Claims.ClaimTypes.NameIdentifier,
            RoleClaimType = "https://eventsync-api/roles",
        };

        options.MapInboundClaims = true;
    });

builder.Services.AddAuthorization();

// ---------------------------------------------------------------------------
// CORS — origins come from configuration; wildcards are NOT supported.
// ---------------------------------------------------------------------------
const string CorsPolicyName = "EventSyncCors";
var allowedOrigins = builder.Configuration
    .GetSection("AllowedOrigins")
    .Get<string[]>() ?? [];

if (allowedOrigins.Length == 0 && builder.Environment.IsDevelopment())
{
    // Sensible local-dev fallback so first-run still works.
    allowedOrigins = ["http://localhost:4200"];
}

builder.Services.AddCors(options =>
{
    options.AddPolicy(CorsPolicyName, policy => policy
        .WithOrigins(allowedOrigins)
        .WithMethods("GET", "POST", "PUT", "PATCH", "DELETE")
        .WithHeaders("Authorization", "Content-Type")
        .AllowCredentials());
});

// ---------------------------------------------------------------------------
// Rate limiting — fixed window, IP-partitioned, applied ONLY to public RSVP POST.
// ---------------------------------------------------------------------------
const string RsvpRateLimitPolicy = "RsvpLimit";
var rsvpWindow = TimeSpan.FromMinutes(10);

builder.Services.AddRateLimiter(options =>
{
    options.AddPolicy(RsvpRateLimitPolicy, httpContext =>
    {
        var partitionKey = ResolveClientIp(httpContext) ?? "unknown";

        return RateLimitPartition.GetFixedWindowLimiter(
            partitionKey,
            _ => new FixedWindowRateLimiterOptions
            {
                AutoReplenishment = true,
                PermitLimit = 5,
                QueueLimit = 0,
                Window = rsvpWindow,
            });
    });

    options.OnRejected = async (context, cancellationToken) =>
    {
        var retryAfterSeconds = (int)Math.Ceiling(rsvpWindow.TotalSeconds);
        if (context.Lease.TryGetMetadata(MetadataName.RetryAfter, out var lease))
        {
            retryAfterSeconds = (int)Math.Ceiling(lease.TotalSeconds);
        }

        context.HttpContext.Response.Headers.RetryAfter = retryAfterSeconds.ToString();
        context.HttpContext.Response.StatusCode = StatusCodes.Status429TooManyRequests;
        context.HttpContext.Response.ContentType = "application/json";

        var logger = context.HttpContext.RequestServices.GetRequiredService<ILoggerFactory>()
            .CreateLogger("RateLimiter");
        logger.LogWarning(
            "Rate limit hit for {Path} from {Ip}. RetryAfter={RetryAfter}s",
            context.HttpContext.Request.Path,
            ResolveClientIp(context.HttpContext),
            retryAfterSeconds);

        await context.HttpContext.Response.WriteAsJsonAsync(
            new
            {
                message = "Too many requests. Please try again later.",
                retryAfter = retryAfterSeconds,
            },
            cancellationToken);
    };
});

// Swagger / OpenAPI with Bearer security so the "Authorize" button appears.
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new() { Title = "EventSync API v1", Version = "v1" });

    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Description = "Paste **only** the JWT (without the 'Bearer ' prefix).",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
    });

    options.OperationFilter<SecurityRequirementsOperationFilter>(true, "Bearer");
});

var app = builder.Build();

// ---------------------------------------------------------------------------
// HTTP request pipeline
//
// Order:
//   1. ForwardedHeaders   — populate Connection.RemoteIpAddress from XFF
//   2. ExceptionHandling  — catches everything below it
//   3. SecurityHeaders    — attaches headers via OnStarting
//   4. HSTS / HTTPS redir — Production only
//   5. Routing
//   6. CORS
//   7. Authentication
//   8. Authorization
//   9. RateLimiter
//  10. Endpoint mapping
// ---------------------------------------------------------------------------

app.UseForwardedHeaders();

app.UseExceptionHandling();
app.UseSecurityHeaders();

if (!app.Environment.IsDevelopment())
{
    app.UseHsts();
    app.UseHttpsRedirection();
}

app.UseRouting();

app.UseCors(CorsPolicyName);

app.UseAuthentication();
app.UseAuthorization();

app.UseRateLimiter();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(options => options.SwaggerEndpoint("/swagger/v1/swagger.json", "EventSync API v1"));
}

// Serve uploaded images from wwwroot/ (e.g. /uploads/events/abc.jpg).
app.UseStaticFiles();

// Explicitly map "/uploads" to the physical wwwroot/uploads folder. This
// ensures the uploads path is served even if the default webroot mapping
// behaves differently in some hosting environments.
var uploadsPhysicalPath = Path.Combine(app.Environment.ContentRootPath, "wwwroot", "uploads");
if (!Directory.Exists(uploadsPhysicalPath))
{
    Directory.CreateDirectory(uploadsPhysicalPath);
}

app.UseStaticFiles(new StaticFileOptions
{
    RequestPath = "/uploads",
    FileProvider = new PhysicalFileProvider(uploadsPhysicalPath)
});

// Health-check endpoint. Returns a small JSON payload — no PII, safe to be public.
app.MapGet("/health", () => Results.Ok(new
{
    status = "healthy",
    timestamp = DateTime.UtcNow,
}))
.WithName("HealthCheck")
.WithTags("Diagnostics")
.AllowAnonymous();

// Feature endpoint groups.
app.MapAuthEndpoints();
app.MapEventEndpoints();
app.MapEventTypeEndpoints();
app.MapUploadEndpoints();
app.MapInviteLinkEndpoints();
app.MapRsvpEndpoints(RsvpRateLimitPolicy);

app.Run();

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// <summary>
/// Resolves the caller's IP address. Honours the first hop of <c>X-Forwarded-For</c>
/// when present (common behind reverse proxies); otherwise falls back to the
/// transport-level remote address.
/// </summary>
/// <remarks>
/// XFF is attacker-controlled and must NEVER be used for authorization decisions.
/// Used here strictly as a partition key and for diagnostic logging.
/// </remarks>
static string? ResolveClientIp(HttpContext httpContext)
{
    if (httpContext.Request.Headers.TryGetValue("X-Forwarded-For", out var forwarded) &&
        !string.IsNullOrWhiteSpace(forwarded))
    {
        var firstHop = forwarded.ToString().Split(',', 2)[0].Trim();
        if (!string.IsNullOrEmpty(firstHop))
        {
            return firstHop;
        }
    }

    return httpContext.Connection.RemoteIpAddress?.ToString();
}

/// <summary>
/// Program entry point. Declared explicitly so integration tests can reference
/// <c>WebApplicationFactory&lt;Program&gt;</c>.
/// </summary>
public partial class Program { }
