// Generated by GitHub Copilot
using EventSync.Api.Common.Behaviors;
using EventSync.Api.Common.Configuration;
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Features.Auth;
using EventSync.Api.Features.Events;
using EventSync.Api.Features.EventTypes;
using EventSync.Api.Features.InviteLinks;
using EventSync.Api.Features.RSVPs;
using EventSync.Api.Features.RSVPs.Common;
using EventSync.Api.Features.Uploads;
using FluentValidation;
using FluentValidation.AspNetCore;
using MediatR;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.Filters;

var builder = WebApplication.CreateBuilder(args);

// ---------------------------------------------------------------------------
// Service registration
// ---------------------------------------------------------------------------

// Force HTTP-only Kestrel binding on port 5000 for local development per spec.
builder.WebHost.UseUrls("http://localhost:5000");

// EF Core (SQL Server / LocalDB).
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException("Missing connection string 'DefaultConnection'.");
builder.Services.AddDbContext<AppDbContext>(options => options.UseSqlServer(connectionString));

// MediatR — scan the current assembly for handlers/behaviors.
builder.Services.AddMediatR(cfg =>
{
    cfg.RegisterServicesFromAssembly(typeof(Program).Assembly);
    cfg.AddOpenBehavior(typeof(ValidationBehavior<,>));
});

// FluentValidation — automatic ASP.NET Core integration + assembly scanning.
builder.Services.AddFluentValidationAutoValidation();
builder.Services.AddValidatorsFromAssembly(typeof(Program).Assembly);

// Current-user service requires HTTP context access.
builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<ICurrentUserService, CurrentUserService>();

// Strongly-typed configuration sections.
builder.Services.Configure<FrontendOptions>(
    builder.Configuration.GetSection(FrontendOptions.SectionName));

// Cryptographically-secure token generator (stateless — safe as a singleton).
builder.Services.AddSingleton<ITokenGenerator, TokenGenerator>();

// Invite-link validation lookup (DbContext-bound — must be scoped).
builder.Services.AddScoped<IInviteValidationService, InviteValidationService>();

// ---------------------------------------------------------------------------
// Authentication / Authorization (Auth0 JWT bearer)
// ---------------------------------------------------------------------------
var auth0Domain = builder.Configuration["Auth0:Domain"]
    ?? throw new InvalidOperationException("Missing configuration 'Auth0:Domain'.");
var auth0Audience = builder.Configuration["Auth0:Audience"]
    ?? throw new InvalidOperationException("Missing configuration 'Auth0:Audience'.");

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        // Authority hosts JWKS at /.well-known/jwks.json — used to validate token signatures.
        options.Authority = $"https://{auth0Domain}/";
        options.Audience = auth0Audience;
        options.RequireHttpsMetadata = !builder.Environment.IsDevelopment();

        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = $"https://{auth0Domain}/",
            ValidAudience = auth0Audience,
            // Map "sub" → ClaimTypes.NameIdentifier so MVC/Minimal API conventions work.
            NameClaimType = System.Security.Claims.ClaimTypes.NameIdentifier,
            RoleClaimType = "https://eventsync-api/roles",
        };

        options.MapInboundClaims = true;
    });

builder.Services.AddAuthorization();

// CORS — permit the Angular dev server.
const string DevCorsPolicy = "DevCors";
builder.Services.AddCors(options =>
{
    options.AddPolicy(DevCorsPolicy, policy => policy
        .WithOrigins("http://localhost:4200")
        .WithMethods("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS")
        .AllowAnyHeader());
});

// Swagger / OpenAPI with Bearer security so the "Authorize" button appears.
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new() { Title = "EventSync API v1", Version = "v1" });

    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Description = "Paste **only** the JWT (without the 'Bearer ' prefix).",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
    });

    // Auto-attach the "Bearer" requirement to any operation whose endpoint
    // requires authorization (avoids the v2 OpenApiReference API churn).
    options.OperationFilter<SecurityRequirementsOperationFilter>(true, "Bearer");
});

var app = builder.Build();

// ---------------------------------------------------------------------------
// HTTP request pipeline
// ---------------------------------------------------------------------------

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(options => options.SwaggerEndpoint("/swagger/v1/swagger.json", "EventSync API v1"));
}

app.UseCors(DevCorsPolicy);

// Serve uploaded images from wwwroot/ (e.g. /uploads/events/abc.jpg).
app.UseStaticFiles();

// Order matters: authentication → authorization → endpoints.
app.UseAuthentication();
app.UseAuthorization();

// Health-check endpoint. Returns a small JSON payload — no PII, safe to be public.
app.MapGet("/health", () => Results.Ok(new
{
    status = "healthy",
    timestamp = DateTime.UtcNow,
}))
.WithName("HealthCheck")
.WithTags("Diagnostics")
.AllowAnonymous();

// Feature endpoint groups.
app.MapAuthEndpoints();
app.MapEventEndpoints();
app.MapEventTypeEndpoints();
app.MapUploadEndpoints();
app.MapInviteLinkEndpoints();
app.MapRsvpEndpoints();

app.Run();

/// <summary>
/// Program entry point. Declared explicitly so integration tests can reference
/// <c>WebApplicationFactory&lt;Program&gt;</c>.
/// </summary>
public partial class Program { }
