// Generated by GitHub Copilot
import { DatePipe } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  signal,
} from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';

import { InviteLinkService } from '../../../../core/api/invite-link.service';
import type {
  CreateInviteLinkRequest,
  InviteLinkDto,
} from '../../../../core/models/invite-link.model';
import { ConfirmDialogComponent } from '../../../../shared/components/confirm-dialog/confirm-dialog.component';
import { LoadingSpinnerComponent } from '../../../../shared/components/loading-spinner/loading-spinner.component';
import { ClipboardService } from '../../../../shared/services/clipboard.service';
import { ToastService } from '../../../../shared/services/toast.service';

/** Display-state for an invite-link row. */
type LinkStatus = 'active' | 'inactive' | 'expired' | 'exhausted';

/**
 * Organizer-facing manager for shareable RSVP invite links.
 *
 * Embedded inside `EventDetailComponent`. Loads the link list on init via an
 * `effect` keyed on the `eventId` input, then provides:
 * - A small reactive form to generate a new link (optional expiry + max uses).
 * - A list of existing links with copy + deactivate actions.
 *
 * Accessibility:
 * - Status badges have semantic colour PLUS text (no colour-only conveyance).
 * - Copy + Deactivate buttons have descriptive `aria-label`s.
 * - Empty / loading / error states are announced through normal heading order.
 */
@Component({
  selector: 'app-invite-link-manager',
  imports: [
    ReactiveFormsModule,
    DatePipe,
    LoadingSpinnerComponent,
    ConfirmDialogComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './invite-link-manager.component.html',
})
export class InviteLinkManagerComponent {
  private readonly inviteLinkService = inject(InviteLinkService);
  private readonly clipboard = inject(ClipboardService);
  private readonly toasts = inject(ToastService);
  private readonly fb = inject(FormBuilder);

  /** Owning event identifier. Required input. */
  readonly eventId = input.required<string>();

  protected readonly links = this.inviteLinkService.links;
  protected readonly loading = signal(true);
  protected readonly errorMessage = signal<string | null>(null);
  protected readonly creating = signal(false);
  protected readonly pendingDeactivateId = signal<string | null>(null);
  protected readonly deactivateBusy = signal(false);

  protected readonly form = this.fb.nonNullable.group({
    expiresAt: [''],
    maxUses: [null as number | null, [Validators.min(1)]],
  });

  /** True while the form has any user-supplied value (used for validation gating). */
  protected readonly hasValues = computed(() => this.links().length >= 0);

  /** Convenience computed for the empty-state message. */
  protected readonly isEmpty = computed(
    () => !this.loading() && this.links().length === 0 && this.errorMessage() === null,
  );

  // eslint-disable-next-line @typescript-eslint/no-unused-private-class-members
  private readonly loadOnEventChange = effect(() => {
    const id = this.eventId();
    if (!id) return;
    this.loading.set(true);
    this.errorMessage.set(null);
    this.inviteLinkService.getInviteLinks(id).subscribe({
      next: () => this.loading.set(false),
      error: () => {
        this.loading.set(false);
        this.errorMessage.set(
          this.inviteLinkService.error() ?? 'Could not load invite links.',
        );
      },
    });
  });

  /** Submits the create-link form. */
  protected generate(): void {
    if (this.creating() || this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    const raw = this.form.getRawValue();
    const payload: CreateInviteLinkRequest = {
      expiresAt: this.toIsoUtc(raw.expiresAt),
      maxUses: raw.maxUses && raw.maxUses > 0 ? raw.maxUses : null,
    };

    this.creating.set(true);
    this.inviteLinkService.createInviteLink(this.eventId(), payload).subscribe({
      next: () => {
        this.creating.set(false);
        this.form.reset({ expiresAt: '', maxUses: null });
        this.toasts.success('Invite link generated.');
      },
      error: () => {
        this.creating.set(false);
        this.toasts.error(
          this.inviteLinkService.error() ?? 'Could not create invite link.',
        );
      },
    });
  }

  /** Copies the URL via the clipboard helper and surfaces a toast either way. */
  protected async copy(link: InviteLinkDto): Promise<void> {
    const ok = await this.clipboard.copy(link.url);
    if (ok) {
      this.toasts.success('Invite link copied to clipboard.');
    } else {
      this.toasts.error('Could not copy link. Please copy it manually.');
    }
  }

  /** Open the deactivate confirmation dialog for the given link. */
  protected requestDeactivate(link: InviteLinkDto): void {
    this.pendingDeactivateId.set(link.id);
  }

  /** Close the deactivate confirmation dialog without acting. */
  protected cancelDeactivate(): void {
    if (this.deactivateBusy()) return;
    this.pendingDeactivateId.set(null);
  }

  /** Confirmed deactivation handler. */
  protected confirmDeactivate(): void {
    const id = this.pendingDeactivateId();
    if (!id || this.deactivateBusy()) return;
    this.deactivateBusy.set(true);
    this.inviteLinkService.deactivateLink(id).subscribe({
      next: () => {
        this.deactivateBusy.set(false);
        this.pendingDeactivateId.set(null);
        this.toasts.success('Invite link deactivated.');
      },
      error: () => {
        this.deactivateBusy.set(false);
        this.pendingDeactivateId.set(null);
        this.toasts.error(
          this.inviteLinkService.error() ?? 'Could not deactivate invite link.',
        );
      },
    });
  }

  /** Computes the display status (badge text + variant) for a link row. */
  protected statusOf(link: InviteLinkDto): LinkStatus {
    if (!link.isActive) return 'inactive';
    if (link.expiresAt && new Date(link.expiresAt).getTime() < Date.now()) {
      return 'expired';
    }
    if (link.maxUses !== null && link.useCount >= link.maxUses) {
      return 'exhausted';
    }
    return 'active';
  }

  /** Tailwind classes per status badge. */
  protected statusClass(status: LinkStatus): string {
    switch (status) {
      case 'active':
        return 'bg-emerald-100 text-emerald-800';
      case 'inactive':
        return 'bg-slate-200 text-slate-700';
      case 'expired':
        return 'bg-amber-100 text-amber-800';
      case 'exhausted':
        return 'bg-rose-100 text-rose-800';
    }
  }

  /** Human-readable label per status. */
  protected statusLabel(status: LinkStatus): string {
    switch (status) {
      case 'active':
        return 'Active';
      case 'inactive':
        return 'Deactivated';
      case 'expired':
        return 'Expired';
      case 'exhausted':
        return 'Limit reached';
    }
  }

  /** "12 / 50" or "12 / \u221E" for unlimited links. */
  protected usageDisplay(link: InviteLinkDto): string {
    const cap = link.maxUses === null ? '\u221E' : link.maxUses.toString();
    return `${link.useCount} / ${cap}`;
  }

  /**
   * Truncates the URL display so wide tokens don't break the layout.
   * The full URL is always exposed via the `title` attribute and copy action.
   */
  protected truncateUrl(url: string): string {
    if (url.length <= 64) return url;
    const prefix = url.slice(0, 40);
    const suffix = url.slice(-12);
    return `${prefix}\u2026${suffix}`;
  }

  /**
   * Converts a `<input type="datetime-local">` value (interpreted as the
   * browser's local zone) to an ISO 8601 UTC string. Returns null for empties.
   */
  private toIsoUtc(value: string | null | undefined): string | null {
    if (!value) return null;
    const local = new Date(value);
    if (Number.isNaN(local.getTime())) return null;
    return local.toISOString();
  }
}
