// Generated by GitHub Copilot
namespace EventSync.Api.Features.Events.Common;

/// <summary>
/// Read-model of an <c>EventType</c> lookup row.
/// </summary>
/// <param name="Id">Identity primary key.</param>
/// <param name="Name">Unique name (e.g., "Birthday").</param>
/// <param name="Icon">Optional emoji/icon identifier rendered by the UI.</param>
public sealed record EventTypeDto(int Id, string Name, string? Icon);

/// <summary>
/// Lightweight organizer projection (no PII beyond name and avatar).
/// </summary>
/// <param name="DisplayName">Organizer display name.</param>
/// <param name="AvatarUrl">Optional avatar URL.</param>
public sealed record OrganizerDto(string DisplayName, string? AvatarUrl);

/// <summary>
/// Aggregated RSVP counts for a single event.
/// </summary>
/// <param name="Going">Count of guests who responded "Yes".</param>
/// <param name="NotGoing">Count of guests who responded "No".</param>
/// <param name="Maybe">Count of guests who responded "Maybe".</param>
/// <param name="Total">Sum of all RSVP responses.</param>
public sealed record RsvpSummaryDto(int Going, int NotGoing, int Maybe, int Total);

/// <summary>
/// Read-model returned by Create and Update endpoints. Mirrors the persisted
/// event including its <see cref="EventType"/> projection.
/// </summary>
public sealed record EventDto(
    Guid Id,
    string Title,
    string? Description,
    string? Location,
    bool IsVirtual,
    string? MeetingUrl,
    DateTime StartDate,
    DateTime? EndDate,
    int? MaxAttendees,
    bool IsCancelled,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    EventTypeDto EventType);

/// <summary>
/// Compact list-view projection used by GET /events.
/// </summary>
public sealed record EventSummaryDto(
    Guid Id,
    string Title,
    string EventTypeName,
    string? EventTypeIcon,
    DateTime StartDate,
    DateTime? EndDate,
    string? Location,
    bool IsVirtual,
    bool IsCancelled,
    int RsvpCount,
    string? CoverImageUrl,
    DateTime CreatedAt);

/// <summary>
/// Read-model of an <see cref="EventSync.Api.Data.Entities.InviteLink"/>.
/// </summary>
/// <param name="Id">Identity primary key.</param>
/// <param name="Token">Opaque, URL-safe random token.</param>
/// <param name="Url">Full shareable URL (front-end RSVP page).</param>
/// <param name="ExpiresAt">Optional UTC expiration.</param>
/// <param name="MaxUses">Optional maximum number of times this link may be used.</param>
/// <param name="UseCount">Number of times this link has been used.</param>
/// <param name="IsActive">Whether the organizer has the link enabled.</param>
/// <param name="CreatedAt">UTC creation timestamp.</param>
public sealed record InviteLinkDto(
    Guid Id,
    string Token,
    string Url,
    DateTime? ExpiresAt,
    int? MaxUses,
    int UseCount,
    bool IsActive,
    DateTime CreatedAt);

/// <summary>
/// Detailed event projection for GET /events/{id}, including organizer,
/// type, RSVP summary, and invite links (empty until Phase 4).
/// </summary>
public sealed record EventDetailDto(
    Guid Id,
    string Title,
    string? Description,
    string? Location,
    bool IsVirtual,
    string? MeetingUrl,
    DateTime StartDate,
    DateTime? EndDate,
    int? MaxAttendees,
    string? CoverImageUrl,
    bool IsCancelled,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    EventTypeDto EventType,
    OrganizerDto Organizer,
    RsvpSummaryDto Rsvps,
    IReadOnlyList<InviteLinkDto> InviteLinks);
