// Generated by GitHub Copilot
using System.Globalization;
using System.Text;
using EventSync.Api.Common.Exceptions;
using EventSync.Api.Features.RSVPs.Common;
using MediatR;

namespace EventSync.Api.Features.RSVPs.GetEventCalendar;

/// <summary>
/// Query: build an iCalendar (RFC 5545) representation of the event behind a
/// public invite token, so a guest can add it to their calendar.
/// </summary>
/// <param name="Token">URL-safe invite token.</param>
public sealed record GetEventCalendarQuery(string Token) : IRequest<EventCalendar>;

/// <summary>Result of a calendar export: a suggested file name and the .ics body.</summary>
/// <param name="FileName">Suggested attachment file name (e.g. <c>my-event.ics</c>).</param>
/// <param name="Content">iCalendar text (CRLF line endings).</param>
public sealed record EventCalendar(string FileName, string Content);

/// <summary>Handler for <see cref="GetEventCalendarQuery"/>.</summary>
public sealed class GetEventCalendarHandler : IRequestHandler<GetEventCalendarQuery, EventCalendar>
{
    private readonly IInviteValidationService _inviteValidation;

    /// <summary>Initializes a new instance of <see cref="GetEventCalendarHandler"/>.</summary>
    public GetEventCalendarHandler(IInviteValidationService inviteValidation)
    {
        _inviteValidation = inviteValidation;
    }

    /// <inheritdoc/>
    /// <exception cref="InvalidInviteException">Token is unknown, deactivated, expired, exhausted, or the event is gone.</exception>
    public async Task<EventCalendar> Handle(GetEventCalendarQuery request, CancellationToken cancellationToken)
    {
        // forSubmission: false — cancelled events are still returned so the guest's
        // calendar can be updated with STATUS:CANCELLED.
        var (link, error) = await _inviteValidation.ValidateTokenAsync(
            request.Token,
            cancellationToken: cancellationToken);
        if (link is null)
        {
            throw new InvalidInviteException(error ?? "Invite link not found");
        }

        var ev = link.Event;
        var end = ev.EndDate ?? ev.StartDate.AddHours(1);

        var location = ev.IsVirtual
            ? (string.IsNullOrWhiteSpace(ev.MeetingUrl) ? "Online event" : ev.MeetingUrl!.Trim())
            : ev.Location?.Trim();

        var descriptionParts = new List<string>();
        if (!string.IsNullOrWhiteSpace(ev.Description))
        {
            descriptionParts.Add(ev.Description!.Trim());
        }
        if (ev.IsVirtual && !string.IsNullOrWhiteSpace(ev.MeetingUrl))
        {
            descriptionParts.Add($"Join: {ev.MeetingUrl!.Trim()}");
        }
        if (!string.IsNullOrWhiteSpace(ev.OrganizerName))
        {
            descriptionParts.Add($"Organized by {ev.OrganizerName.Trim()}");
        }
        var description = string.Join("\n\n", descriptionParts);

        var summary = ev.IsCancelled ? $"Cancelled: {ev.Title}" : ev.Title;

        var sb = new StringBuilder();
        sb.Append("BEGIN:VCALENDAR\r\n");
        sb.Append("VERSION:2.0\r\n");
        sb.Append("PRODID:-//EventSync//Event Calendar//EN\r\n");
        sb.Append("CALSCALE:GREGORIAN\r\n");
        sb.Append("METHOD:PUBLISH\r\n");
        sb.Append("BEGIN:VEVENT\r\n");
        // UID is stable per invite token (already known to the guest) — avoids
        // leaking the internal event id while staying unique + reusable.
        sb.Append($"UID:{request.Token}@eventsync\r\n");
        sb.Append($"DTSTAMP:{DateTime.UtcNow.ToString("yyyyMMdd'T'HHmmss'Z'", CultureInfo.InvariantCulture)}\r\n");
        // Floating local time (no 'Z'/TZID): matches how the app stores and displays
        // event times today (a zone-less wall-clock). Calendars interpret it in the
        // viewer's local zone. Revisit once per-event timezones are added.
        sb.Append($"DTSTART:{FormatFloating(ev.StartDate)}\r\n");
        sb.Append($"DTEND:{FormatFloating(end)}\r\n");
        sb.Append($"SUMMARY:{Escape(summary)}\r\n");
        if (!string.IsNullOrWhiteSpace(description))
        {
            sb.Append($"DESCRIPTION:{Escape(description)}\r\n");
        }
        if (!string.IsNullOrWhiteSpace(location))
        {
            sb.Append($"LOCATION:{Escape(location!)}\r\n");
        }
        sb.Append($"STATUS:{(ev.IsCancelled ? "CANCELLED" : "CONFIRMED")}\r\n");
        sb.Append("END:VEVENT\r\n");
        sb.Append("END:VCALENDAR\r\n");

        return new EventCalendar(BuildFileName(ev.Title), sb.ToString());
    }

    /// <summary>Formats a date-time as floating local time (RFC 5545 form without a zone).</summary>
    private static string FormatFloating(DateTime value) =>
        value.ToString("yyyyMMdd'T'HHmmss", CultureInfo.InvariantCulture);

    /// <summary>Escapes an iCalendar TEXT value per RFC 5545 (backslash, semicolon, comma, newline).</summary>
    private static string Escape(string value) =>
        value.Replace("\\", "\\\\")
             .Replace(";", "\\;")
             .Replace(",", "\\,")
             .Replace("\r\n", "\\n")
             .Replace("\n", "\\n");

    /// <summary>Builds a safe, readable .ics file name from the event title.</summary>
    private static string BuildFileName(string title)
    {
        var chars = title.ToLowerInvariant().Select(c => char.IsLetterOrDigit(c) ? c : '-').ToArray();
        var slug = string.Join('-', new string(chars).Split('-', StringSplitOptions.RemoveEmptyEntries));

        if (slug.Length == 0)
        {
            slug = "event";
        }
        else if (slug.Length > 50)
        {
            slug = slug[..50].TrimEnd('-');
        }

        return $"{slug}.ics";
    }
}
