// Generated by GitHub Copilot
namespace EventSync.Api.Common.Models;

/// <summary>
/// Generic paged-result envelope returned by list endpoints.
/// </summary>
/// <typeparam name="T">Item DTO type.</typeparam>
/// <param name="Items">The page of items (never null; may be empty).</param>
/// <param name="Page">1-based page index that was requested and returned.</param>
/// <param name="PageSize">Number of items per page (clamped by the handler).</param>
/// <param name="TotalCount">Total number of items across all pages after filtering.</param>
public sealed record PagedResult<T>(
    IReadOnlyList<T> Items,
    int Page,
    int PageSize,
    int TotalCount)
{
    /// <summary>
    /// Total number of pages, derived from <see cref="TotalCount"/> and
    /// <see cref="PageSize"/>. Returns <c>0</c> when there are no items.
    /// </summary>
    public int TotalPages => PageSize <= 0 || TotalCount <= 0
        ? 0
        : (int)Math.Ceiling(TotalCount / (double)PageSize);
}
