// Generated by GitHub Copilot
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import {
  FormBuilder,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { Router, RouterLink } from '@angular/router';

import { EventService } from '../../../core/api/event.service';
import type { CreateEventRequest } from '../../../core/models/event.model';
import {
  dateAfter,
  futureDate,
  urlFormat,
} from '../../../shared/validators/custom-validators';

/**
 * Form to create a new event. Reactive, typed, and accessible.
 *
 * Validation:
 * - Title required, max 200.
 * - Description max 2000.
 * - EventTypeId required.
 * - Location max 300.
 * - MeetingUrl is required AND must be a valid http(s) URL when `isVirtual` is checked.
 * - StartDate must be in the future.
 * - EndDate (when provided) must be after StartDate.
 * - MaxAttendees min 1.
 *
 * Accessibility:
 * - Every control has an associated `<label for="…">`.
 * - Inline error messages are linked via `aria-describedby` and use `role="alert"`.
 * - The submit button is disabled while pending or invalid; live region announces save status.
 */
@Component({
  selector: 'app-create-event',
  imports: [ReactiveFormsModule, RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './create-event.component.html',
})
export class CreateEventComponent {
  private readonly fb = inject(FormBuilder);
  private readonly eventService = inject(EventService);
  private readonly router = inject(Router);

  protected readonly eventTypes = this.eventService.eventTypes;
  protected readonly submitting = signal(false);
  protected readonly submitError = signal<string | null>(null);
  protected readonly uploading = signal(false);
  protected readonly uploadError = signal<string | null>(null);
  protected readonly coverImageUrl = signal<string | null>(null);
  protected readonly coverPreview = signal<string | null>(null);

  /** Strictly typed form. */
  protected readonly form = this.fb.nonNullable.group({
    title: ['', [Validators.required, Validators.maxLength(200)]],
    organizerName: ['', [Validators.required, Validators.maxLength(100)]],
    description: ['', [Validators.maxLength(2000)]],
    eventTypeId: this.fb.control<number | null>(null, [Validators.required]),
    location: ['', [Validators.maxLength(300)]],
    isVirtual: [false],
    meetingUrl: ['', [urlFormat()]],
    startDate: ['', [Validators.required, futureDate()]],
    endDate: ['', [dateAfter('startDate')]],
    maxAttendees: this.fb.control<number | null>(null, [Validators.min(1)]),
  });

  /** Mirror of `isVirtual` so the template can reactively show/hide MeetingUrl. */
  private readonly isVirtual = toSignal(this.form.controls.isVirtual.valueChanges, {
    initialValue: false,
  });

  protected readonly showMeetingUrl = computed(() => this.isVirtual() === true);

  // eslint-disable-next-line @typescript-eslint/no-unused-private-class-members
  private readonly toggleMeetingUrlValidators = effect(() => {
    const required = this.showMeetingUrl();
    const ctrl = this.form.controls.meetingUrl;
    ctrl.setValidators(
      required ? [Validators.required, urlFormat()] : [urlFormat()],
    );
    ctrl.updateValueAndValidity({ emitEvent: false });
  });

  constructor() {
    // Load event types if not already cached.
    if (this.eventTypes().length === 0) {
      this.eventService.getEventTypes().subscribe({ error: () => undefined });
    }
  }

  protected onSubmit(): void {
    if (this.form.invalid || this.submitting()) {
      this.form.markAllAsTouched();
      return;
    }
    const v = this.form.getRawValue();
    const payload: CreateEventRequest = {
      title: v.title.trim(),
      organizerName: v.organizerName.trim(),
      description: v.description.trim() || null,
      eventTypeId: Number(v.eventTypeId),
      location: v.location.trim() || null,
      isVirtual: v.isVirtual,
      meetingUrl: v.isVirtual ? v.meetingUrl.trim() || null : null,
      startDate: v.startDate,
      endDate: v.endDate || null,
      maxAttendees: v.maxAttendees ?? null,
      coverImageUrl: this.coverImageUrl(),
    };

    this.submitting.set(true);
    this.submitError.set(null);
    this.eventService.createEvent(payload).subscribe({
      next: (created) => {
        this.submitting.set(false);
        this.router.navigate(['/events', created.id]);
      },
      error: () => {
        this.submitting.set(false);
        this.submitError.set(
          this.eventService.error() ?? 'Could not create event. Please try again.',
        );
      },
    });
  }

  protected onCancel(): void {
    this.router.navigate(['/events']);
  }

  /** Handles cover image file selection. Uploads immediately and stores the returned URL. */
  protected onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;
    this.uploadFile(file);
  }

  /** Handles drag-and-drop onto the cover image zone. */
  protected onDrop(event: DragEvent): void {
    const file = event.dataTransfer?.files?.[0];
    if (!file) return;
    this.uploadFile(file);
  }

  private uploadFile(file: File): void {
    const allowed = ['image/jpeg', 'image/png', 'image/webp'];
    if (!allowed.includes(file.type)) {
      this.uploadError.set('Only JPEG, PNG, and WebP images are allowed.');
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      this.uploadError.set('Image must be under 5 MB.');
      return;
    }
    // Show local preview immediately.
    this.coverPreview.set(URL.createObjectURL(file));
    this.uploading.set(true);
    this.uploadError.set(null);

    this.eventService.uploadImage(file).subscribe({
      next: (res) => {
        this.coverImageUrl.set(res.url);
        this.uploading.set(false);
      },
      error: () => {
        this.uploading.set(false);
        this.uploadError.set(this.eventService.error() ?? 'Upload failed.');
        this.coverPreview.set(null);
      },
    });
  }

  /** Removes the cover image. */
  protected removeCover(): void {
    this.coverImageUrl.set(null);
    this.coverPreview.set(null);
    this.uploadError.set(null);
  }
}
