// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component } from '@angular/core';

/**
 * Authenticated-area sidebar placeholder. Hidden until Phase 2 introduces auth.
 */
@Component({
  selector: 'app-sidebar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <aside aria-label="Secondary" hidden>
      <!-- Sidebar content arrives in Phase 3 (Dashboard). -->
    </aside>
  `,
})
export class SidebarComponent {}
