// Generated by GitHub Copilot
import { inject } from '@angular/core';
import { CanActivateFn, Router, UrlTree } from '@angular/router';
import { AuthService as Auth0Service } from '@auth0/auth0-angular';
import { Observable, combineLatest, filter, from, map, switchMap, take } from 'rxjs';

import { AuthService } from './auth.service';

/**
 * Functional route guard that requires an authenticated Auth0 session.
 *
 * Behaviour:
 * - Waits for the Auth0 SDK to finish initialising (`isLoading$ === false`)
 *   BEFORE inspecting `isAuthenticated$`. This prevents a race where a hard
 *   refresh on a guarded route briefly sees `isAuthenticated === false`
 *   while the SDK is still restoring the session from storage, which would
 *   incorrectly redirect signed-in users to `/login`.
 * - When unauthenticated, redirects to `/login` and preserves the original
 *   path/query in `?returnUrl=...` so the user lands back where they intended
 *   after sign-in.
 *
 * Security:
 * - This guard is a UX convenience only. Authorization is enforced by the API
 *   via JWT validation; never rely solely on the guard for sensitive data.
 */
export const authGuard: CanActivateFn = (_route, state): Observable<boolean | UrlTree> => {
  const auth0 = inject(Auth0Service);
  const auth = inject(AuthService);
  const router = inject(Router);

  return combineLatest([auth0.isLoading$, auth0.isAuthenticated$]).pipe(
    // Block the navigation until the SDK has finished bootstrapping.
    filter(([isLoading]) => !isLoading),
    take(1),
    switchMap(([, isAuthenticated]) => {
      if (!isAuthenticated) {
        return from([
          router.createUrlTree(['/login'], { queryParams: { returnUrl: state.url } }),
        ]);
      }

      return from(auth.hasUsableSession()).pipe(
        map((hasUsableSession) =>
          hasUsableSession
            ? true
            : router.createUrlTree(['/login'], { queryParams: { returnUrl: state.url } }),
        ),
      );
    }),
  );
};

