// Generated by GitHub Copilot
import { HttpInterceptorFn, HttpRequest } from '@angular/common/http';
import { inject } from '@angular/core';
import { catchError, switchMap, throwError } from 'rxjs';

import { environment } from '../../../environments/environment';
import { AuthService } from './auth.service';

/**
 * Functional HTTP interceptor that attaches an Auth0 access token as
 * `Authorization: Bearer {jwt}` to outgoing requests targeted at the EventSync API.
 *
 * Rules:
 * - Only requests whose URL starts with `environment.apiUrl` are touched. This
 *   prevents leaking tokens to third-party origins.
 * - If the silent token request fails, the error is propagated so the caller
 *   can react (e.g. redirect to login). It is NOT silently swallowed.
 *
 * Security:
 * - Tokens are scoped to the EventSync audience by `provideAuth0`.
 * - The `apiUrl` prefix check is the audit point; do not relax it.
 */
export const authInterceptor: HttpInterceptorFn = (req, next) => {
  if (!req.url.startsWith(environment.apiUrl)) {
    return next(req);
  }

  // Public endpoints (anonymous invite + public RSVP submission) MUST NOT carry
  // a bearer token — attempting to fetch one when the user is signed out would
  // throw and prevent the page from loading for guests. Match by path so the
  // check is robust against future host changes.
  if (isPublicEndpoint(req.url)) {
    return next(req);
  }

  const auth = inject(AuthService);

  return auth.getAccessToken$().pipe(
    catchError((err) => {
      console.error('[Auth] Failed to retrieve access token:', err);
      return throwError(() => err);
    }),
    switchMap((token) => {
      if (!token) {
        console.warn('[Auth] No access token available — request will be unauthenticated.');
        return next(req);
      }
      return next(withBearer(req, token));
    }),
  );
};

/** True when the URL targets an explicitly anonymous backend endpoint. */
function isPublicEndpoint(url: string): boolean {
  // Strip the API origin so we match path segments only.
  const path = url.startsWith(environment.apiUrl)
    ? url.slice(environment.apiUrl.length)
    : url;
  // /invite/{token} and /invite/{token}/rsvp are anonymous (Phase 4A).
  return path.startsWith('/invite/');
}

/** Returns a clone of `req` with the `Authorization: Bearer {token}` header. */
function withBearer<T>(req: HttpRequest<T>, token: string): HttpRequest<T> {
  return req.clone({ setHeaders: { Authorization: `Bearer ${token}` } });
}
