// Generated by GitHub Copilot
import { HttpInterceptorFn, HttpRequest } from '@angular/common/http';
import { inject } from '@angular/core';
import { catchError, switchMap, throwError } from 'rxjs';

import { environment } from '../../../environments/environment';
import { AuthService } from './auth.service';

/**
 * Functional HTTP interceptor that attaches an Auth0 access token as
 * `Authorization: Bearer {jwt}` to outgoing requests targeted at the EventSync API.
 *
 * Rules:
 * - Only requests whose URL starts with `environment.apiUrl` are touched. This
 *   prevents leaking tokens to third-party origins.
 * - If the silent token request fails due to an expired or missing refresh
 *   token, the user is logged out automatically so the next login obtains a
 *   fresh set of tokens.
 *
 * Security:
 * - Tokens are scoped to the EventSync audience by `provideAuth0`.
 * - The `apiUrl` prefix check is the audit point; do not relax it.
 */
export const authInterceptor: HttpInterceptorFn = (req, next) => {
  if (!req.url.startsWith(environment.apiUrl)) {
    return next(req);
  }

  // Public endpoints (anonymous invite + public RSVP submission) MUST NOT carry
  // a bearer token — attempting to fetch one when the user is signed out would
  // throw and prevent the page from loading for guests. Match by path so the
  // check is robust against future host changes.
  if (isPublicEndpoint(req.url)) {
    return next(req);
  }

  const auth = inject(AuthService);

  return auth.getAccessToken$().pipe(
    catchError((err) => {
      console.error('[Auth] Failed to retrieve access token:', err);

      // When the refresh token is expired, revoked, or missing the Auth0 SDK
      // throws an error whose message or code indicates the session is
      // unrecoverable. Log the user out so the next login produces fresh tokens.
      if (isRefreshTokenError(err)) {
        console.warn('[Auth] Refresh token expired or missing — logging out.');
        auth.logout();
        return throwError(() => err);
      }

      return throwError(() => err);
    }),
    switchMap((token) => {
      if (!token) {
        console.warn('[Auth] No access token available — request will be unauthenticated.');
        return next(req);
      }
      return next(withBearer(req, token));
    }),
  );
};

/**
 * Detects refresh-token failures emitted by the Auth0 SDK.
 *
 * The SDK surfaces these as plain `Error` objects whose `message` contains
 * keywords like "Missing Refresh Token" or "Unknown or invalid refresh token".
 * The `error` field on the object (if present) may also carry the OAuth code
 * `"login_required"` or `"missing_refresh_token"`.
 */
function isRefreshTokenError(err: unknown): boolean {
  if (typeof err === 'object' && err !== null) {
    const record = err as Record<string, unknown>;

    // Auth0 SDK error codes.
    if (
      record['error'] === 'login_required' ||
      record['error'] === 'missing_refresh_token' ||
      record['error'] === 'invalid_grant'
    ) {
      return true;
    }

    // Fallback: match the error message text.
    const message =
      typeof record['message'] === 'string'
        ? record['message'].toLowerCase()
        : '';
    if (
      message.includes('missing refresh token') ||
      message.includes('invalid refresh token') ||
      message.includes('unknown or invalid refresh token')
    ) {
      return true;
    }
  }

  return false;
}

/** True when the URL targets an explicitly anonymous backend endpoint. */
function isPublicEndpoint(url: string): boolean {
  // Strip the API origin so we match path segments only.
  const path = url.startsWith(environment.apiUrl)
    ? url.slice(environment.apiUrl.length)
    : url;
  // /invite/{token} and /invite/{token}/rsvp are anonymous (Phase 4A).
  return path.startsWith('/invite/');
}

/** Returns a clone of `req` with the `Authorization: Bearer {token}` header. */
function withBearer<T>(req: HttpRequest<T>, token: string): HttpRequest<T> {
  return req.clone({ setHeaders: { Authorization: `Bearer ${token}` } });
}
