// Generated by GitHub Copilot
import { HttpInterceptorFn, HttpRequest } from '@angular/common/http';
import { inject } from '@angular/core';
import { Router } from '@angular/router';
import { catchError, switchMap, throwError, timeout } from 'rxjs';

import { environment } from '../../../environments/environment';
import { ToastService } from '../../shared/services/toast.service';
import { AuthService } from './auth.service';

/**
 * Maximum time (ms) we'll wait for Auth0's silent token retrieval before
 * treating the session as unrecoverable. Bounds two failure modes the SDK
 * does NOT bound itself: a blocked silent-renew iframe (third-party cookies
 * disabled) and an offline/very-slow network during refresh.
 */
const AUTH_TOKEN_TIMEOUT_MS = 10_000;

/** Sentinel error message used to identify the timeout in catchError. */
const AUTH_TIMEOUT_MESSAGE = 'auth_timeout';

/**
 * Module-level guard so that when several in-flight requests fail at the same
 * time (e.g. the event-detail page fans out 3–4 parallel calls), we only show
 * ONE toast and trigger ONE navigation to /login. Reset on the next successful
 * token retrieval so a fresh sign-in can fail-and-redirect again later.
 */
let redirecting = false;

/**
 * Functional HTTP interceptor that attaches an Auth0 access token as
 * `Authorization: Bearer {jwt}` to outgoing requests targeted at the EventSync API.
 *
 * Rules:
 * - Only requests whose URL starts with `environment.apiUrl` are touched. This
 *   prevents leaking tokens to third-party origins.
 * - Token retrieval is bounded by {@link AUTH_TOKEN_TIMEOUT_MS}. Timeout, a
 *   missing refresh token, an expired refresh token, or an `invalid_grant`
 *   from Auth0 are all treated as "session unrecoverable": we show a toast,
 *   clear the SDK's local state, and route the user to `/login` with the
 *   current URL preserved as `returnUrl`.
 *
 * Security:
 * - Tokens are scoped to the EventSync audience by `provideAuth0`.
 * - The `apiUrl` prefix check is the audit point; do not relax it.
 */
export const authInterceptor: HttpInterceptorFn = (req, next) => {
  if (!req.url.startsWith(environment.apiUrl)) {
    return next(req);
  }

  // Public endpoints (anonymous invite + public RSVP submission) MUST NOT carry
  // a bearer token — attempting to fetch one when the user is signed out would
  // throw and prevent the page from loading for guests. Match by path so the
  // check is robust against future host changes.
  if (isPublicEndpoint(req.url)) {
    return next(req);
  }

  const auth = inject(AuthService);
  const toast = inject(ToastService);
  const router = inject(Router);

  return auth.getAccessToken$().pipe(
    timeout({
      each: AUTH_TOKEN_TIMEOUT_MS,
      with: () => throwError(() => new Error(AUTH_TIMEOUT_MESSAGE)),
    }),
    catchError((err) => {
      const sessionLost = isSessionUnrecoverable(err);
      if (sessionLost) {
        console.warn('[Auth] Session unrecoverable — routing to /login.', err);
        handleSessionLoss(auth, toast, router);
      } else {
        console.error('[Auth] Failed to retrieve access token:', err);
      }
      return throwError(() => err);
    }),
    switchMap((token) => {
      // Token retrieval succeeded — allow future failures to trigger the
      // redirect flow again.
      redirecting = false;

      if (!token) {
        console.warn('[Auth] No access token available — request will be unauthenticated.');
        return next(req);
      }
      return next(withBearer(req, token));
    }),
  );
};

/**
 * True for any error that signals the user's session cannot be recovered
 * without a fresh interactive login. Covers Auth0 SDK refresh-token errors
 * AND our own silent-renew timeout sentinel.
 */
function isSessionUnrecoverable(err: unknown): boolean {
  if (err instanceof Error && err.message === AUTH_TIMEOUT_MESSAGE) {
    return true;
  }
  return isRefreshTokenError(err);
}

/**
 * Detects refresh-token failures emitted by the Auth0 SDK.
 *
 * The SDK surfaces these as plain `Error` objects whose `message` contains
 * keywords like "Missing Refresh Token" or "Unknown or invalid refresh token".
 * The `error` field on the object (if present) may also carry the OAuth code
 * `"login_required"` or `"missing_refresh_token"`.
 */
function isRefreshTokenError(err: unknown): boolean {
  if (typeof err === 'object' && err !== null) {
    const record = err as Record<string, unknown>;

    // Auth0 SDK error codes.
    if (
      record['error'] === 'login_required' ||
      record['error'] === 'missing_refresh_token' ||
      record['error'] === 'invalid_grant'
    ) {
      return true;
    }

    // Fallback: match the error message text.
    const message =
      typeof record['message'] === 'string'
        ? record['message'].toLowerCase()
        : '';
    if (
      message.includes('missing refresh token') ||
      message.includes('invalid refresh token') ||
      message.includes('unknown or invalid refresh token')
    ) {
      return true;
    }
  }

  return false;
}

/**
 * Shows the "session expired" toast, clears the Auth0 SDK's local state, and
 * navigates to `/login` with the current URL preserved as `returnUrl`.
 *
 * Idempotent for the duration of a single failure burst — the {@link redirecting}
 * flag suppresses duplicates so users don't see N toasts when N parallel
 * requests fail at once.
 */
function handleSessionLoss(auth: AuthService, toast: ToastService, router: Router): void {
  if (redirecting) {
    return;
  }
  redirecting = true;

  toast.error('Session expired. Please log in again.');
  auth.logoutLocal();

  const returnUrl =
    router.url && router.url !== '/login' ? router.url : '/dashboard';
  router.navigate(['/login'], { queryParams: { returnUrl } });
}

/** True when the URL targets an explicitly anonymous backend endpoint. */
function isPublicEndpoint(url: string): boolean {
  // Strip the API origin so we match path segments only.
  const path = url.startsWith(environment.apiUrl)
    ? url.slice(environment.apiUrl.length)
    : url;
  // /invite/{token} and /invite/{token}/rsvp are anonymous (Phase 4A).
  return path.startsWith('/invite/');
}

/** Returns a clone of `req` with the `Authorization: Bearer {token}` header. */
function withBearer<T>(req: HttpRequest<T>, token: string): HttpRequest<T> {
  return req.clone({ setHeaders: { Authorization: `Bearer ${token}` } });
}
