// Generated by GitHub Copilot
import { Injectable, computed, inject } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { AuthService as Auth0Service } from '@auth0/auth0-angular';
import { Observable, firstValueFrom } from 'rxjs';

/**
 * Thin Angular-idiomatic wrapper around `@auth0/auth0-angular`.
 *
 * Exposes the SDK's RxJS streams as **signals** so components can consume them
 * with `OnPush` change detection without manual subscription management.
 *
 * Security:
 * - Tokens are obtained via `getAccessTokenSilently()` which uses Auth0 PKCE flow.
 * - Tokens are NEVER persisted to localStorage by us — the Auth0 SDK manages
 *   storage in-memory by default; we just read on demand.
 */
@Injectable({ providedIn: 'root' })
export class AuthService {
  private readonly auth0 = inject(Auth0Service);

  /** True while the SDK is initializing or processing a redirect callback. */
  readonly isLoading = toSignal(this.auth0.isLoading$, { initialValue: true });

  /** True when the SDK has a valid session. */
  readonly isAuthenticated = toSignal(this.auth0.isAuthenticated$, { initialValue: false });

  /** Auth0 user profile (id_token claims), or null/undefined when signed out. */
  readonly user = toSignal(this.auth0.user$, { initialValue: undefined });

  /** Convenience: a non-null display name with sensible fallbacks. */
  readonly displayName = computed(() => {
    const u = this.user();
    return u?.name ?? u?.nickname ?? u?.email ?? 'Account';
  });

  /** Convenience: avatar URL or null. */
  readonly avatarUrl = computed(() => this.user()?.picture ?? null);

  /**
   * Initiates the Auth0 Universal Login redirect.
   *
   * NOTE: `loginWithRedirect` returns a cold Observable in `@auth0/auth0-angular`
   * v2 — it must be subscribed for the navigation to actually occur.
   *
   * @param appState Optional state preserved across the redirect (e.g. return URL).
   */
  login(appState?: { target?: string }): void {
    this.auth0.loginWithRedirect({ appState }).subscribe({
      error: (err) => console.error('[Auth] loginWithRedirect failed', err),
    });
  }

  /**
   * Logs out and redirects back to the application origin.
   *
   * NOTE: `logout` also returns a cold Observable — must be subscribed.
   */
  logout(): void {
    this.auth0
      .logout({ logoutParams: { returnTo: window.location.origin } })
      .subscribe({
        error: (err) => console.error('[Auth] logout failed', err),
      });
  }

  /**
   * Clears the Auth0 SDK's local session state (in-memory + localStorage cache)
   * WITHOUT redirecting through Auth0's `/v2/logout` endpoint.
   *
   * Use this when we've detected the session is unrecoverable (expired refresh
   * token, silent-renew timeout) and want to route the user to our own `/login`
   * page without a disruptive third-party round-trip.
   */
  logoutLocal(): void {
    this.auth0.logout({ openUrl: false }).subscribe({
      error: (err) => console.error('[Auth] local logout failed', err),
    });
  }

  /**
   * Returns a Promise that resolves with a fresh access token.
   * Throws if the user is not authenticated or the silent renew fails.
   */
  async getAccessToken(): Promise<string> {
    return firstValueFrom(this.auth0.getAccessTokenSilently());
  }

  /** Same as {@link getAccessToken} but as an Observable for interceptor use. */
  getAccessToken$(): Observable<string> {
    return this.auth0.getAccessTokenSilently();
  }

  /**
   * Returns true only when the cached Auth0 session can still produce a usable
   * access token. When silent renewal fails, clear the local SDK state so the
   * app can send the user back through an interactive login cleanly.
   */
  async hasUsableSession(): Promise<boolean> {
    try
    {
      await this.getAccessToken();
      return true;
    }
    catch (err)
    {
      console.warn('[Auth] Cached session is no longer usable.', err);
      this.logoutLocal();
      return false;
    }
  }
}
