// Generated by GitHub Copilot
using EventSync.Api.Common.Exceptions;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.RSVPs.Common;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.RSVPs.SubmitRsvp;

/// <summary>
/// Command: record an RSVP submitted by an anonymous guest.
/// </summary>
/// <param name="Token">URL-safe invite token (resolves event + link).</param>
/// <param name="GuestName">Required guest display name.</param>
/// <param name="GuestEmail">Optional contact email; when provided enables idempotent updates.</param>
/// <param name="Status">Going / NotGoing / Maybe. Pending is rejected.</param>
/// <param name="Note">Optional free-text note.</param>
public sealed record SubmitRsvpCommand(
    string Token,
    string GuestName,
    string? GuestEmail,
    RsvpStatus Status,
    string? Note) : IRequest<RsvpConfirmationDto>
{
    /// <summary>
    /// Caller IP address captured by the endpoint and forwarded to the handler. Bypasses
    /// validation/serialization (the public payload never carries this value).
    /// </summary>
    public string? IpAddress { get; init; }
}

/// <summary>FluentValidation rules for <see cref="SubmitRsvpCommand"/>.</summary>
public sealed class SubmitRsvpValidator : AbstractValidator<SubmitRsvpCommand>
{
    /// <summary>Configures the validation rules.</summary>
    public SubmitRsvpValidator()
    {
        RuleFor(x => x.Token).NotEmpty();

        RuleFor(x => x.GuestName)
            .NotEmpty()
            .MaximumLength(100);

        RuleFor(x => x.GuestEmail)
            .EmailAddress()
            .MaximumLength(256)
            .When(x => !string.IsNullOrWhiteSpace(x.GuestEmail));

        RuleFor(x => x.Note)
            .MaximumLength(500)
            .When(x => !string.IsNullOrEmpty(x.Note));

        RuleFor(x => x.Status)
            .Must(s => s == RsvpStatus.Going || s == RsvpStatus.NotGoing || s == RsvpStatus.Maybe)
                .WithMessage("Status must be Going, NotGoing, or Maybe.");
    }
}

/// <summary>Handler for <see cref="SubmitRsvpCommand"/>.</summary>
public sealed class SubmitRsvpHandler : IRequestHandler<SubmitRsvpCommand, RsvpConfirmationDto>
{
    private readonly AppDbContext _dbContext;
    private readonly IInviteValidationService _inviteValidation;

    /// <summary>Initializes a new instance of <see cref="SubmitRsvpHandler"/>.</summary>
    public SubmitRsvpHandler(AppDbContext dbContext, IInviteValidationService inviteValidation)
    {
        _dbContext = dbContext;
        _inviteValidation = inviteValidation;
    }

    /// <inheritdoc/>
    /// <exception cref="InvalidInviteException">Thrown when the invite token cannot be honoured.</exception>
    public async Task<RsvpConfirmationDto> Handle(SubmitRsvpCommand request, CancellationToken cancellationToken)
    {
        var (validatedLink, error) = await _inviteValidation.ValidateTokenAsync(
            request.Token,
            forSubmission: true,
            cancellationToken);
        if (validatedLink is null)
        {
            throw new InvalidInviteException(error ?? "Invite link not found");
        }

        // Re-load the link as TRACKED so we can persist the UseCount increment.
        var link = await _dbContext.InviteLinks
            .Include(l => l.Event)
            .FirstAsync(l => l.Id == validatedLink.Id, cancellationToken);

        var now = DateTime.Now;
        Rsvp? existing = null;

        if (!string.IsNullOrWhiteSpace(request.GuestEmail))
        {
            existing = await _dbContext.Rsvps
                .FirstOrDefaultAsync(
                    r => r.EventId == link.EventId && r.GuestEmail == request.GuestEmail,
                    cancellationToken);
        }

        Rsvp rsvp;
        if (existing is not null)
        {
            existing.GuestName = request.GuestName;
            existing.Status = request.Status;
            existing.Note = request.Note;
            existing.UpdatedAt = now;
            existing.IpAddress = TruncateIp(request.IpAddress);
            rsvp = existing;
        }
        else
        {
            rsvp = new Rsvp
            {
                Id = Guid.NewGuid(),
                EventId = link.EventId,
                InviteLinkId = link.Id,
                GuestName = request.GuestName,
                GuestEmail = string.IsNullOrWhiteSpace(request.GuestEmail) ? null : request.GuestEmail,
                Status = request.Status,
                Note = request.Note,
                RespondedAt = now,
                UpdatedAt = null,
                IpAddress = TruncateIp(request.IpAddress),
            };
            _dbContext.Rsvps.Add(rsvp);
            link.UseCount += 1;
        }

        await _dbContext.SaveChangesAsync(cancellationToken);

        return new RsvpConfirmationDto(
            rsvp.Id,
            rsvp.GuestName,
            rsvp.Status,
            link.Event.Title,
            link.Event.StartDate);
    }

    /// <summary>Truncates the captured IP to the column length (45 chars covers IPv6).</summary>
    private static string? TruncateIp(string? ip)
    {
        if (string.IsNullOrWhiteSpace(ip))
        {
            return null;
        }

        return ip.Length <= 45 ? ip : ip[..45];
    }
}
