// Generated by GitHub Copilot
import { DatePipe } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  signal,
} from '@angular/core';

import { EventService } from '../../../../core/api/event.service';
import { RsvpService } from '../../../../core/api/rsvp.service';
import type { PagedResult } from '../../../../core/models/paged-result.model';
import type { RsvpDto } from '../../../../core/models/rsvp.model';
import { RsvpStatus } from '../../../../core/models/rsvp.model';
import { LoadingSpinnerComponent } from '../../../../shared/components/loading-spinner/loading-spinner.component';
import { PaginationComponent } from '../../../../shared/components/pagination/pagination.component';
import {
  StatusBadgeComponent,
  type StatusBadgeVariant,
} from '../../../../shared/components/status-badge/status-badge.component';

/** Discriminated value used by the filter tabs. `null` means "All". */
type StatusFilter = RsvpStatus | null;

/** Filter-tab descriptor. */
interface FilterTab {
  readonly value: StatusFilter;
  readonly label: string;
  readonly count: number;
}

const PAGE_SIZE = 20;

/**
 * Organizer-facing list of RSVPs for an event.
 *
 * Lives inside `EventDetailComponent`. Pulls the rolled-up counts from
 * `EventService.selectedEvent()` (already loaded by the parent) so the filter
 * tabs render counts without an extra request, and pulls the paged rows from
 * `RsvpService.getRsvps()` whenever the filter or page changes.
 */
@Component({
  selector: 'app-rsvp-list',
  imports: [
    DatePipe,
    LoadingSpinnerComponent,
    PaginationComponent,
    StatusBadgeComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './rsvp-list.component.html',
})
export class RsvpListComponent {
  private readonly rsvpService = inject(RsvpService);
  private readonly eventService = inject(EventService);

  /** Owning event identifier. */
  readonly eventId = input.required<string>();

  /** Currently active filter tab. `null` = All. */
  protected readonly statusFilter = signal<StatusFilter>(null);
  protected readonly currentPage = signal<number>(1);
  protected readonly loading = signal<boolean>(true);
  protected readonly errorMessage = signal<string | null>(null);

  protected readonly result = signal<PagedResult<RsvpDto> | null>(null);

  /** Tabs derived from the selected-event RSVP summary. */
  protected readonly tabs = computed<readonly FilterTab[]>(() => {
    const summary = this.eventService.selectedEvent()?.rsvps;
    return [
      { value: null, label: 'All', count: summary?.total ?? 0 },
      { value: RsvpStatus.Going, label: 'Going', count: summary?.going ?? 0 },
      { value: RsvpStatus.Maybe, label: 'Maybe', count: summary?.maybe ?? 0 },
      { value: RsvpStatus.NotGoing, label: 'Not Going', count: summary?.notGoing ?? 0 },
    ];
  });

  protected readonly hasResults = computed(() => (this.result()?.items.length ?? 0) > 0);

  protected readonly isEmpty = computed(
    () => !this.loading() && !this.errorMessage() && !this.hasResults(),
  );

  // eslint-disable-next-line @typescript-eslint/no-unused-private-class-members
  private readonly load = effect(() => {
    const id = this.eventId();
    const status = this.statusFilter();
    const page = this.currentPage();
    if (!id) return;

    this.loading.set(true);
    this.errorMessage.set(null);

    const params: { page: number; pageSize: number; status?: RsvpStatus } = {
      page,
      pageSize: PAGE_SIZE,
    };
    if (status !== null) params.status = status;

    this.rsvpService.getRsvps(id, params).subscribe({
      next: (res) => {
        this.result.set(res);
        this.loading.set(false);
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set(this.rsvpService.error() ?? 'Could not load RSVPs.');
      },
    });
  });

  /** Switch the active filter tab and reset to page 1. */
  protected selectFilter(value: StatusFilter): void {
    if (this.statusFilter() === value) return;
    this.statusFilter.set(value);
    this.currentPage.set(1);
  }

  /** Pagination handler. */
  protected goToPage(page: number): void {
    this.currentPage.set(page);
  }

  /** Maps a RSVP status to a badge variant + label. */
  protected statusBadge(status: RsvpStatus): { text: string; variant: StatusBadgeVariant } {
    switch (status) {
      case RsvpStatus.Going:
        return { text: 'Going', variant: 'success' };
      case RsvpStatus.Maybe:
        return { text: 'Maybe', variant: 'warning' };
      case RsvpStatus.NotGoing:
        return { text: 'Not Going', variant: 'danger' };
      default:
        return { text: 'Pending', variant: 'default' };
    }
  }

  /** Truncate long notes for table display; full text exposed via `title`. */
  protected truncateNote(note: string | null): string {
    if (!note) return '';
    return note.length <= 60 ? note : `${note.slice(0, 60)}\u2026`;
  }

  /** Smooth-scrolls to the invite manager on the same page. */
  protected scrollToInviteManager(): void {
    const target = document.getElementById('invite-links-heading');
    if (!target) return;
    target.scrollIntoView({ behavior: 'smooth', block: 'start' });
    // Move focus for keyboard / screen-reader users.
    target.setAttribute('tabindex', '-1');
    target.focus({ preventScroll: true });
  }
}
