// Generated by GitHub Copilot
using EventSync.Api.Common.Models;
using EventSync.Api.Features.Events.CancelEvent;
using EventSync.Api.Features.Events.Common;
using EventSync.Api.Features.Events.CreateEvent;
using EventSync.Api.Features.Events.DeleteEvent;
using EventSync.Api.Features.Events.GetEventById;
using EventSync.Api.Features.Events.GetEvents;
using EventSync.Api.Features.Events.UpdateEvent;
using FluentValidation;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace EventSync.Api.Features.Events;

/// <summary>
/// Maps Event-feature minimal-API endpoints onto the application route table.
/// All endpoints require a valid bearer token and verify resource ownership.
/// </summary>
public static class EventEndpoints
{
    /// <summary>
    /// Registers <c>/api/v1/events*</c> endpoints.
    /// </summary>
    /// <param name="app">The application route builder.</param>
    /// <returns>The supplied <paramref name="app"/> for chaining.</returns>
    public static IEndpointRouteBuilder MapEventEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/v1/events")
            .WithTags("Events")
            .RequireAuthorization();

        group.MapGet("/", async (
            IMediator mediator,
            CancellationToken ct,
            [FromQuery] int page = 1,
            [FromQuery] int pageSize = 10,
            [FromQuery] string? search = null,
            [FromQuery] int? typeId = null,
            [FromQuery] string sortBy = "date",
            [FromQuery] string sortDir = "asc") =>
        {
            var result = await mediator.Send(
                new GetEventsQuery(page, pageSize, search, typeId, sortBy, sortDir), ct);
            return Results.Ok(result);
        })
        .WithName("GetEvents")
        .WithSummary("List the current user's events with paging, search and filters.")
        .Produces<PagedResult<EventSummaryDto>>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status401Unauthorized);

        group.MapGet("/{id:guid}", async (Guid id, IMediator mediator, CancellationToken ct) =>
        {
            try
            {
                var ev = await mediator.Send(new GetEventByIdQuery(id), ct);
                return Results.Ok(ev);
            }
            catch (KeyNotFoundException ex)
            {
                return Results.NotFound(new { error = ex.Message });
            }
            catch (UnauthorizedAccessException)
            {
                return Results.Forbid();
            }
        })
        .WithName("GetEventById")
        .WithSummary("Get full details for a single event you organize.")
        .Produces<EventDetailDto>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status401Unauthorized)
        .Produces(StatusCodes.Status403Forbidden)
        .Produces(StatusCodes.Status404NotFound);

        group.MapPost("/", async (
            [FromBody] CreateEventCommand command,
            IMediator mediator,
            CancellationToken ct) =>
        {
            try
            {
                var ev = await mediator.Send(command, ct);
                return Results.Created($"/api/v1/events/{ev.Id}", ev);
            }
            catch (ValidationException ex)
            {
                return ToValidationProblem(ex);
            }
        })
        .WithName("CreateEvent")
        .WithSummary("Create a new event owned by the current user.")
        .Produces<EventDto>(StatusCodes.Status201Created)
        .ProducesValidationProblem()
        .Produces(StatusCodes.Status401Unauthorized);

        group.MapPut("/{id:guid}", async (
            Guid id,
            [FromBody] UpdateEventCommand body,
            IMediator mediator,
            CancellationToken ct) =>
        {
            // Bind the route id authoritatively, ignoring any value supplied in the body.
            var command = body with { Id = id };
            try
            {
                var ev = await mediator.Send(command, ct);
                return Results.Ok(ev);
            }
            catch (ValidationException ex)
            {
                return ToValidationProblem(ex);
            }
            catch (KeyNotFoundException ex)
            {
                return Results.NotFound(new { error = ex.Message });
            }
            catch (UnauthorizedAccessException)
            {
                return Results.Forbid();
            }
        })
        .WithName("UpdateEvent")
        .WithSummary("Update an event you organize.")
        .Produces<EventDto>(StatusCodes.Status200OK)
        .ProducesValidationProblem()
        .Produces(StatusCodes.Status401Unauthorized)
        .Produces(StatusCodes.Status403Forbidden)
        .Produces(StatusCodes.Status404NotFound);

        group.MapDelete("/{id:guid}", async (Guid id, IMediator mediator, CancellationToken ct) =>
        {
            try
            {
                await mediator.Send(new DeleteEventCommand(id), ct);
                return Results.NoContent();
            }
            catch (KeyNotFoundException ex)
            {
                return Results.NotFound(new { error = ex.Message });
            }
            catch (UnauthorizedAccessException)
            {
                return Results.Forbid();
            }
        })
        .WithName("DeleteEvent")
        .WithSummary("Soft-delete an event you organize.")
        .Produces(StatusCodes.Status204NoContent)
        .Produces(StatusCodes.Status401Unauthorized)
        .Produces(StatusCodes.Status403Forbidden)
        .Produces(StatusCodes.Status404NotFound);

        group.MapPatch("/{id:guid}/cancel", async (Guid id, IMediator mediator, CancellationToken ct) =>
        {
            try
            {
                await mediator.Send(new CancelEventCommand(id), ct);
                return Results.NoContent();
            }
            catch (KeyNotFoundException ex)
            {
                return Results.NotFound(new { error = ex.Message });
            }
            catch (UnauthorizedAccessException)
            {
                return Results.Forbid();
            }
        })
        .WithName("CancelEvent")
        .WithSummary("Mark an event you organize as cancelled.")
        .Produces(StatusCodes.Status204NoContent)
        .Produces(StatusCodes.Status401Unauthorized)
        .Produces(StatusCodes.Status403Forbidden)
        .Produces(StatusCodes.Status404NotFound);

        return app;
    }

    /// <summary>
    /// Converts a FluentValidation <see cref="ValidationException"/> into a
    /// problem-details 400 response. Phase 5 will replace this with a global handler.
    /// </summary>
    private static IResult ToValidationProblem(ValidationException ex)
    {
        var errors = ex.Errors
            .GroupBy(e => e.PropertyName)
            .ToDictionary(g => g.Key, g => g.Select(e => e.ErrorMessage).ToArray());
        return Results.ValidationProblem(errors);
    }
}
