// Generated by GitHub Copilot
import type { InviteLinkDto } from './invite-link.model';

/**
 * DTO contracts shared with the EventSync backend.
 *
 * Field names and types must stay in lock-step with the C# records under
 * `EventSync.Api.Features.Events.Common`. Backend uses `System.Text.Json`
 * camelCase by default, so property names are camelCase here.
 */

/** Lookup row for an event category. */
export interface EventTypeDto {
  readonly id: number;
  readonly name: string;
  readonly icon: string | null;
}

/** Public organizer projection (no PII beyond name + avatar). */
export interface OrganizerDto {
  readonly displayName: string;
  readonly avatarUrl: string | null;
}

/** Aggregated RSVP counts. */
export interface RsvpSummaryDto {
  readonly going: number;
  readonly notGoing: number;
  readonly maybe: number;
  readonly total: number;
}

/** Response from `POST /events` and `PUT /events/{id}`. */
export interface EventDto {
  readonly id: string;
  readonly title: string;
  readonly organizerName: string;
  readonly description: string | null;
  readonly location: string | null;
  readonly isVirtual: boolean;
  readonly meetingUrl: string | null;
  readonly startDate: string;
  readonly endDate: string | null;
  readonly maxAttendees: number | null;
  readonly isCancelled: boolean;
  readonly createdAt: string;
  readonly updatedAt: string | null;
  readonly eventType: EventTypeDto;
}

/** Item shape for `GET /events` paged results. */
export interface EventSummaryDto {
  readonly id: string;
  readonly title: string;
  readonly eventTypeName: string;
  readonly eventTypeIcon: string | null;
  readonly startDate: string;
  readonly endDate: string | null;
  readonly location: string | null;
  readonly isVirtual: boolean;
  readonly isCancelled: boolean;
  readonly rsvpCount: number;
  readonly coverImageUrl: string | null;
  readonly createdAt: string;
}

/** Response from `GET /events/{id}` (full detail + summary + organizer). */
export interface EventDetailDto {
  readonly id: string;
  readonly title: string;
  readonly organizerName: string;
  readonly description: string | null;
  readonly location: string | null;
  readonly isVirtual: boolean;
  readonly meetingUrl: string | null;
  readonly startDate: string;
  readonly endDate: string | null;
  readonly maxAttendees: number | null;
  readonly coverImageUrl: string | null;
  readonly isCancelled: boolean;
  readonly createdAt: string;
  readonly updatedAt: string | null;
  readonly eventType: EventTypeDto;
  readonly organizer: OrganizerDto;
  readonly rsvps: RsvpSummaryDto;
  readonly inviteLinks: readonly InviteLinkDto[];
}

/** Body for `POST /events`. */
export interface CreateEventRequest {
  readonly title: string;
  readonly organizerName: string;
  readonly description: string | null;
  readonly eventTypeId: number;
  readonly location: string | null;
  readonly isVirtual: boolean;
  readonly meetingUrl: string | null;
  /** ISO 8601 UTC string. */
  readonly startDate: string;
  /** ISO 8601 UTC string or null. */
  readonly endDate: string | null;
  readonly maxAttendees: number | null;
  readonly coverImageUrl: string | null;
}

/** Body for `PUT /events/{id}`. Mirrors `CreateEventRequest`. */
export type UpdateEventRequest = CreateEventRequest;

/** Query parameters accepted by `GET /events`. */
export interface EventListParams {
  readonly page?: number;
  readonly pageSize?: number;
  readonly search?: string | null;
  readonly typeId?: number | null;
  readonly sortBy?: 'date' | 'title';
  readonly sortDir?: 'asc' | 'desc';
}
