// Generated by GitHub Copilot
/**
 * Invite-link contracts shared with the backend.
 *
 * Mirrors `EventSync.Api.Features.Events.Common.InviteLinkDto` and the
 * `CreateInviteLinkCommand` payload from
 * `EventSync.Api.Features.InviteLinks.CreateInviteLink`.
 */

/** Read-model returned by `GET /events/{id}/invite-links`. */
export interface InviteLinkDto {
  readonly id: string;
  readonly token: string;
  /** Full shareable URL (e.g. `http://localhost:4200/rsvp/abc...`). */
  readonly url: string;
  /** ISO 8601 UTC string, or null if the link never expires. */
  readonly expiresAt: string | null;
  /** Maximum allowed uses, or null for unlimited. */
  readonly maxUses: number | null;
  readonly useCount: number;
  readonly isActive: boolean;
  readonly createdAt: string;
}

/** Body for `POST /events/{id}/invite-links`. */
export interface CreateInviteLinkRequest {
  /** ISO 8601 UTC string, or null for no expiry. */
  readonly expiresAt: string | null;
  /** Optional usage cap (>= 1). */
  readonly maxUses: number | null;
}
