// Generated by GitHub Copilot
import type { EventTypeDto, RsvpSummaryDto } from './event.model';

/**
 * RSVP + public-event contracts shared with the backend.
 *
 * Mirrors records under `EventSync.Api.Features.RSVPs.Common` and matches the
 * persisted `RsvpStatus` enum (numeric values are part of the contract).
 */

/**
 * Persisted RSVP status. Numeric values match the backend `RsvpStatus` enum
 * (`Pending = 0` is intentionally omitted because the public submission API
 * rejects it).
 */
export enum RsvpStatus {
  Going = 1,
  NotGoing = 2,
  Maybe = 3,
}

/** Anonymous, public-facing event projection. */
export interface PublicEventDto {
  readonly title: string;
  readonly description: string | null;
  readonly eventType: EventTypeDto;
  readonly location: string | null;
  readonly isVirtual: boolean;
  readonly startDate: string;
  readonly endDate: string | null;
  /** Display name only — backend never exposes the organizer's email. */
  readonly organizerName: string;
  readonly coverImageUrl: string | null;
  readonly isCancelled: boolean;
}

/** Body for `POST /invite/{token}/rsvp`. */
export interface SubmitRsvpRequest {
  readonly guestName: string;
  readonly guestEmail: string | null;
  readonly status: RsvpStatus;
  readonly note: string | null;
}

/** Confirmation echoed back after a successful submission. */
export interface RsvpConfirmationDto {
  readonly id: string;
  readonly guestName: string;
  readonly status: RsvpStatus;
  readonly eventTitle: string;
  readonly eventDate: string;
}

/** Read-model row for the organizer-side RSVP list. */
export interface RsvpDto {
  readonly id: string;
  readonly guestName: string;
  readonly guestEmail: string | null;
  readonly status: RsvpStatus;
  readonly note: string | null;
  readonly respondedAt: string;
  readonly updatedAt: string | null;
}

/** Re-export so RSVP consumers don't need to know about event.model. */
export type { RsvpSummaryDto };
