// Generated by GitHub Copilot
/**
 * Shape of the user profile returned by the EventSync API.
 * Mirrors the backend `UserProfileDto` record (Phase 2A).
 */
export interface UserProfileDto {
  /** Local user primary key (Guid serialized as a string). */
  readonly id: string;
  /** Email address. */
  readonly email: string;
  /** Display name shown in the UI. */
  readonly displayName: string;
  /** Optional avatar image URL. */
  readonly avatarUrl?: string | null;
}
