// Generated by GitHub Copilot
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.Events.Common;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.Events.CreateEvent;

/// <summary>
/// Command: create a new event owned by the current user.
/// </summary>
public sealed record CreateEventCommand(
    string Title,
    string OrganizerName,
    string? Description,
    int EventTypeId,
    string? Location,
    bool IsVirtual,
    string? MeetingUrl,
    DateTime StartDate,
    DateTime? EndDate,
    int? MaxAttendees,
    string? CoverImageUrl) : IRequest<EventDto>;

/// <summary>FluentValidation rules for <see cref="CreateEventCommand"/>.</summary>
public sealed class CreateEventValidator : AbstractValidator<CreateEventCommand>
{
    /// <summary>Configures the validation rules.</summary>
    public CreateEventValidator()
    {
        RuleFor(x => x.Title).NotEmpty().MaximumLength(200);
        RuleFor(x => x.OrganizerName).NotEmpty().MaximumLength(100);
        RuleFor(x => x.Description).MaximumLength(2000);
        RuleFor(x => x.EventTypeId).GreaterThan(0);
        RuleFor(x => x.Location).MaximumLength(300);

        RuleFor(x => x.MeetingUrl)
            .Must(BeAValidAbsoluteUrl)
                .WithMessage("MeetingUrl must be a valid absolute http(s) URL.")
            .MaximumLength(1024)
            .When(x => !string.IsNullOrWhiteSpace(x.MeetingUrl));

        RuleFor(x => x.StartDate)
            .GreaterThan(_ => DateTime.Now)
                .WithMessage("StartDate must be in the future.");

        RuleFor(x => x.EndDate)
            .GreaterThan(x => x.StartDate)
                .WithMessage("EndDate must be after StartDate.")
            .When(x => x.EndDate.HasValue);

        RuleFor(x => x.MaxAttendees)
            .GreaterThanOrEqualTo(1)
            .When(x => x.MaxAttendees.HasValue);

        RuleFor(x => x.CoverImageUrl)
            .Must(BeAValidImageUrl)
                .WithMessage("CoverImageUrl must be a valid https URL or an /uploads/ path.")
            .MaximumLength(512)
            .When(x => !string.IsNullOrWhiteSpace(x.CoverImageUrl));
    }

    private static bool BeAValidAbsoluteUrl(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return true;
        }

        return Uri.TryCreate(value, UriKind.Absolute, out var uri)
            && (uri.Scheme == Uri.UriSchemeHttp || uri.Scheme == Uri.UriSchemeHttps);
    }

    /// <summary>
    /// Accepts either an absolute http(s) URL or a server-relative path beginning
    /// with <c>/uploads/</c> (returned by the upload endpoint).
    /// </summary>
    private static bool BeAValidImageUrl(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return true;
        }

        if (value.StartsWith("/uploads/", StringComparison.Ordinal))
        {
            return true;
        }

        return BeAValidAbsoluteUrl(value);
    }
}

/// <summary>Handler for <see cref="CreateEventCommand"/>.</summary>
public sealed class CreateEventHandler : IRequestHandler<CreateEventCommand, EventDto>
{
    private readonly ICurrentUserService _currentUser;
    private readonly AppDbContext _dbContext;

    /// <summary>Initializes a new instance of <see cref="CreateEventHandler"/>.</summary>
    public CreateEventHandler(ICurrentUserService currentUser, AppDbContext dbContext)
    {
        _currentUser = currentUser;
        _dbContext = dbContext;
    }

    /// <inheritdoc/>
    public async Task<EventDto> Handle(CreateEventCommand request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        // Verify the supplied EventTypeId references a real lookup row before saving —
        // EF will otherwise surface a less helpful FK constraint error.
        var eventType = await _dbContext.EventTypes
            .AsNoTracking()
            .FirstOrDefaultAsync(t => t.Id == request.EventTypeId, cancellationToken)
            ?? throw new ValidationException(
                [new FluentValidation.Results.ValidationFailure(
                    nameof(request.EventTypeId),
                    $"EventTypeId {request.EventTypeId} does not exist.")]);

        var now = DateTime.Now;
        var entity = new Event
        {
            Id = Guid.NewGuid(),
            OrganizerId = user.Id,
            EventTypeId = request.EventTypeId,
            Title = request.Title.Trim(),
            OrganizerName = request.OrganizerName.Trim(),
            Description = string.IsNullOrWhiteSpace(request.Description) ? null : request.Description.Trim(),
            Location = string.IsNullOrWhiteSpace(request.Location) ? null : request.Location.Trim(),
            IsVirtual = request.IsVirtual,
            MeetingUrl = string.IsNullOrWhiteSpace(request.MeetingUrl) ? null : request.MeetingUrl.Trim(),
            StartDate = request.StartDate,
            EndDate = request.EndDate,
            MaxAttendees = request.MaxAttendees,
            CoverImageUrl = string.IsNullOrWhiteSpace(request.CoverImageUrl) ? null : request.CoverImageUrl.Trim(),
            CreatedAt = now,
            IsCancelled = false,
            IsDeleted = false,
        };

        _dbContext.Events.Add(entity);
        await _dbContext.SaveChangesAsync(cancellationToken);

        return new EventDto(
            entity.Id,
            entity.Title,
            entity.OrganizerName,
            entity.Description,
            entity.Location,
            entity.IsVirtual,
            entity.MeetingUrl,
            entity.StartDate,
            entity.EndDate,
            entity.MaxAttendees,
            entity.IsCancelled,
            entity.CreatedAt,
            entity.UpdatedAt,
            new EventTypeDto(eventType.Id, eventType.Name, eventType.Icon));
    }
}
