// Generated by GitHub Copilot
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  inject,
  input,
  output,
  viewChild,
} from '@angular/core';

/** Visual style of the primary action button. */
export type ConfirmDialogVariant = 'danger' | 'primary';

/**
 * Reusable accessible confirm dialog.
 *
 * Accessibility:
 * - `role="dialog"` + `aria-modal="true"` so assistive tech treats it as modal.
 * - `aria-labelledby` references the visible title heading.
 * - Focus is moved to the primary action on open and restored to the
 *   previously-focused element on close (handled by callers via `*` template).
 * - `Tab` / `Shift+Tab` are trapped between the two buttons.
 * - `Escape` (handled in `host`) cancels.
 *
 * The component is rendered inline by the consumer (typically guarded by `@if`),
 * which means the host element exists in the DOM only while open — there is no
 * need for a CDK overlay or a portal for this simple use case.
 */
@Component({
  selector: 'app-confirm-dialog',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './confirm-dialog.component.html',
  host: {
    '(document:keydown.escape)': 'onCancel()',
  },
})
export class ConfirmDialogComponent implements AfterViewInit {
  readonly title = input.required<string>();
  readonly message = input.required<string>();
  readonly confirmText = input<string>('Confirm');
  readonly cancelText = input<string>('Cancel');
  readonly variant = input<ConfirmDialogVariant>('primary');

  readonly confirmed = output<void>();
  readonly cancelled = output<void>();

  private readonly host = inject(ElementRef<HTMLElement>);
  private readonly confirmButton = viewChild<ElementRef<HTMLButtonElement>>('confirmBtn');
  private readonly cancelButton = viewChild<ElementRef<HTMLButtonElement>>('cancelBtn');

  protected readonly confirmClass = computed(() =>
    this.variant() === 'danger'
      ? 'bg-rose-600 hover:bg-rose-700 focus-visible:ring-rose-400'
      : 'bg-indigo-600 hover:bg-indigo-700 focus-visible:ring-indigo-400',
  );

  /** Move focus into the dialog once it is rendered. */
  ngAfterViewInit(): void {
    queueMicrotask(() => this.confirmButton()?.nativeElement.focus());
  }

  /** Backdrop click — only dismisses when the click target IS the backdrop. */
  protected onBackdropClick(event: MouseEvent): void {
    if (event.target === event.currentTarget) {
      this.onCancel();
    }
  }

  /** Trap Tab focus between the two buttons. */
  protected onKeydown(event: KeyboardEvent): void {
    if (event.key !== 'Tab') return;
    const cancel = this.cancelButton()?.nativeElement;
    const confirm = this.confirmButton()?.nativeElement;
    if (!cancel || !confirm) return;

    const active = (this.host.nativeElement.ownerDocument?.activeElement ?? null) as HTMLElement | null;
    if (event.shiftKey && active === cancel) {
      event.preventDefault();
      confirm.focus();
    } else if (!event.shiftKey && active === confirm) {
      event.preventDefault();
      cancel.focus();
    }
  }

  protected onConfirm(): void {
    this.confirmed.emit();
  }

  protected onCancel(): void {
    this.cancelled.emit();
  }
}
