// Generated by GitHub Copilot
using EventSync.Api.Common.Services;
using MediatR;

namespace EventSync.Api.Features.Auth.GetProfile;

/// <summary>
/// Request: returns the profile of the currently authenticated user.
/// Triggers first-time user provisioning when needed.
/// </summary>
public sealed record GetProfileQuery : IRequest<UserProfileDto>;

/// <summary>Handler for <see cref="GetProfileQuery"/>.</summary>
public sealed class GetProfileHandler : IRequestHandler<GetProfileQuery, UserProfileDto>
{
    private readonly ICurrentUserService _currentUser;

    /// <summary>Initializes a new instance of <see cref="GetProfileHandler"/>.</summary>
    /// <param name="currentUser">Current-user accessor.</param>
    public GetProfileHandler(ICurrentUserService currentUser)
    {
        _currentUser = currentUser;
    }

    /// <inheritdoc/>
    public async Task<UserProfileDto> Handle(GetProfileQuery request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);
        return new UserProfileDto(user.Id, user.Email, user.DisplayName, user.AvatarUrl);
    }
}
