// Generated by GitHub Copilot
namespace EventSync.Api.Data.Entities;

/// <summary>
/// Lookup table classifying events (e.g., Seminar, Birthday). Seeded at model creation.
/// </summary>
public class EventType
{
    /// <summary>Identity primary key.</summary>
    public int Id { get; set; }

    /// <summary>Unique human-readable name.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Optional emoji or icon identifier rendered by the UI.</summary>
    public string? Icon { get; set; }

    /// <summary>Events of this type.</summary>
    public ICollection<Event> Events { get; set; } = new List<Event>();
}
