// Generated by GitHub Copilot
namespace EventSync.Api.Data.Entities;

/// <summary>
/// Represents a scheduled event hosted by an organizer.
/// </summary>
/// <remarks>
/// Soft-delete via <see cref="IsDeleted"/> is enforced by a global query filter.
/// <see cref="IsCancelled"/> is a separate domain state distinct from deletion.
/// </remarks>
public class Event
{
    /// <summary>Primary key (Guid).</summary>
    public Guid Id { get; set; }

    /// <summary>Foreign key to <see cref="User"/> (organizer).</summary>
    public Guid OrganizerId { get; set; }

    /// <summary>Foreign key to <see cref="EventType"/>.</summary>
    public int EventTypeId { get; set; }

    /// <summary>Event title.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Custom organizer name displayed on the event and public RSVP page.</summary>
    public string OrganizerName { get; set; } = string.Empty;

    /// <summary>Optional long-form description.</summary>
    public string? Description { get; set; }

    /// <summary>Optional physical or written location.</summary>
    public string? Location { get; set; }

    /// <summary>Whether the event is virtual (online).</summary>
    public bool IsVirtual { get; set; }

    /// <summary>Optional virtual meeting URL (e.g., Teams/Zoom).</summary>
    public string? MeetingUrl { get; set; }

    /// <summary>UTC start date and time.</summary>
    public DateTime StartDate { get; set; }

    /// <summary>Optional UTC end date and time.</summary>
    public DateTime? EndDate { get; set; }

    /// <summary>Optional cap on number of RSVPs.</summary>
    public int? MaxAttendees { get; set; }

    /// <summary>Optional cover image URL.</summary>
    public string? CoverImageUrl { get; set; }

    /// <summary>UTC creation timestamp.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>UTC last-update timestamp, if any.</summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>Soft-delete flag.</summary>
    public bool IsDeleted { get; set; }

    /// <summary>True if the organizer cancelled the event.</summary>
    public bool IsCancelled { get; set; }

    /// <summary>Navigation: organizing user.</summary>
    public User Organizer { get; set; } = null!;

    /// <summary>Navigation: event type.</summary>
    public EventType EventType { get; set; } = null!;

    /// <summary>Navigation: invite links generated for this event.</summary>
    public ICollection<InviteLink> InviteLinks { get; set; } = new List<InviteLink>();

    /// <summary>Navigation: RSVPs received for this event.</summary>
    public ICollection<Rsvp> Rsvps { get; set; } = new List<Rsvp>();
}
