// Generated by GitHub Copilot
namespace EventSync.Api.Data.Entities;

/// <summary>
/// A shareable invite token granting RSVP access to a specific event.
/// </summary>
/// <remarks>
/// Security: <see cref="Token"/> values must be generated from a cryptographically secure random
/// source (e.g., <c>RandomNumberGenerator</c>) and treated as bearer tokens. Use of the link is
/// rate-limited via <see cref="MaxUses"/> and <see cref="ExpiresAt"/>.
/// </remarks>
public class InviteLink
{
    /// <summary>Primary key (Guid).</summary>
    public Guid Id { get; set; }

    /// <summary>Foreign key to <see cref="Event"/>.</summary>
    public Guid EventId { get; set; }

    /// <summary>Opaque, cryptographically random token shared in URLs. Unique.</summary>
    public string Token { get; set; } = string.Empty;

    /// <summary>Optional UTC expiration.</summary>
    public DateTime? ExpiresAt { get; set; }

    /// <summary>Optional maximum number of times this link may be used.</summary>
    public int? MaxUses { get; set; }

    /// <summary>Number of times this link has been used to RSVP.</summary>
    public int UseCount { get; set; }

    /// <summary>Whether this link is currently active (organizer can disable).</summary>
    public bool IsActive { get; set; } = true;

    /// <summary>UTC creation timestamp.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>Navigation: parent event.</summary>
    public Event Event { get; set; } = null!;

    /// <summary>Navigation: RSVPs that came through this link.</summary>
    public ICollection<Rsvp> Rsvps { get; set; } = new List<Rsvp>();
}
