// Generated by GitHub Copilot
namespace EventSync.Api.Data.Entities;

/// <summary>
/// RSVP status enumeration. Persisted as <c>tinyint</c>.
/// </summary>
/// <remarks>
/// Numeric values are part of the persisted contract — do NOT renumber existing
/// members. <see cref="Pending"/> represents a record that has not yet been
/// answered (e.g., a placeholder created by an organizer-side workflow). The
/// public submit-RSVP endpoint must reject <see cref="Pending"/>.
/// </remarks>
public enum RsvpStatus : byte
{
    /// <summary>No response yet.</summary>
    Pending = 0,

    /// <summary>Guest has accepted the invitation.</summary>
    Going = 1,

    /// <summary>Guest has declined the invitation.</summary>
    NotGoing = 2,

    /// <summary>Guest is undecided / tentative.</summary>
    Maybe = 3,
}

/// <summary>
/// A guest's response to an event invitation.
/// </summary>
/// <remarks>
/// Security: <see cref="IpAddress"/> is captured for abuse mitigation only and must be handled in
/// accordance with privacy regulations (treated as personal data).
/// </remarks>
public class Rsvp
{
    /// <summary>Primary key (Guid).</summary>
    public Guid Id { get; set; }

    /// <summary>Foreign key to <see cref="Event"/>.</summary>
    public Guid EventId { get; set; }

    /// <summary>Optional foreign key to <see cref="InviteLink"/> used for this RSVP.</summary>
    public Guid? InviteLinkId { get; set; }

    /// <summary>Guest's display name (required).</summary>
    public string GuestName { get; set; } = string.Empty;

    /// <summary>Optional guest email for follow-up communication.</summary>
    public string? GuestEmail { get; set; }

    /// <summary>RSVP status (Yes/No/Maybe).</summary>
    public RsvpStatus Status { get; set; }

    /// <summary>Optional free-text note from the guest (length-limited).</summary>
    public string? Note { get; set; }

    /// <summary>UTC timestamp when the RSVP was first recorded.</summary>
    public DateTime RespondedAt { get; set; }

    /// <summary>UTC timestamp of the most recent change, if any.</summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>Optional IPv4/IPv6 of submitter (truncated max 45 chars).</summary>
    public string? IpAddress { get; set; }

    /// <summary>Navigation: the event being responded to.</summary>
    public Event Event { get; set; } = null!;

    /// <summary>Navigation: invite link used (if any).</summary>
    public InviteLink? InviteLink { get; set; }
}
