// Generated by GitHub Copilot
namespace EventSync.Api.Data.Entities;

/// <summary>
/// Represents an application user authenticated via Auth0.
/// </summary>
/// <remarks>
/// Security: Auth0Id is the canonical external identity claim and must be treated as a unique
/// secret-bearing identifier. Soft-delete (<see cref="IsDeleted"/>) preserves historical
/// auditability rather than hard-removing records.
/// </remarks>
public class User
{
    /// <summary>Primary key (Guid).</summary>
    public Guid Id { get; set; }

    /// <summary>External Auth0 subject identifier (e.g., "auth0|abc123"). Unique.</summary>
    public string Auth0Id { get; set; } = string.Empty;

    /// <summary>User email address.</summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>Public display name.</summary>
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>Optional avatar image URL.</summary>
    public string? AvatarUrl { get; set; }

    /// <summary>UTC timestamp when the user record was created.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>UTC timestamp of the most recent update, if any.</summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>Soft-delete flag. Filtered out by global query filter.</summary>
    public bool IsDeleted { get; set; }

    /// <summary>Events organized by this user.</summary>
    public ICollection<Event> OrganizedEvents { get; set; } = new List<Event>();
}
