// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

/** Visual variant of the badge. Colour is supplementary — text is required. */
export type StatusBadgeVariant = 'default' | 'success' | 'warning' | 'danger' | 'info';

/**
 * Coloured pill that always carries a text label.
 *
 * WCAG 1.4.1 ("Use of Color") — the meaning of the badge is conveyed by the
 * `status` text first; colour is a redundant secondary cue.
 */
@Component({
  selector: 'app-status-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span [class]="badgeClass()">
      {{ status() }}
    </span>
  `,
})
export class StatusBadgeComponent {
  readonly status = input.required<string>();
  readonly variant = input<StatusBadgeVariant>('default');

  protected readonly badgeClass = computed(() => {
    const variants: Record<StatusBadgeVariant, string> = {
      default: 'bg-slate-100 text-slate-700',
      success: 'bg-emerald-100 text-emerald-800',
      warning: 'bg-amber-100 text-amber-800',
      danger: 'bg-rose-100 text-rose-800',
      info: 'bg-sky-100 text-sky-800',
    };
    return `inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${variants[this.variant()]}`;
  });
}
