// Generated by GitHub Copilot
import { provideHttpClient, withFetch, withInterceptors } from '@angular/common/http';
import {
  ApplicationConfig,
  ErrorHandler,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideAuth0 } from '@auth0/auth0-angular';

import { authInterceptor } from './core/auth/auth.interceptor';
import { errorInterceptor } from './core/error/error.interceptor';
import { GlobalErrorHandler } from './core/error/global-error-handler';
import { environment } from '../environments/environment';
import { routes } from './app.routes';

/**
 * Application-wide DI configuration.
 *
 * Providers:
 * - `provideRouter`              — lazy-loaded route table.
 * - `provideHttpClient(withFetch())` — modern Fetch-backed HttpClient.
 * - `withInterceptors([authInterceptor, errorInterceptor])` — auth attaches a
 *   Bearer token first; the error interceptor then translates HTTP failures
 *   into toasts and a redirect on 401.
 * - `{ provide: ErrorHandler, useClass: GlobalErrorHandler }` — last-resort
 *   handler for uncaught (non-HTTP) errors.
 * - `provideAuth0(...)`          — initialises the Auth0 SPA SDK with the
 *   tenant settings from `environment.auth0`.
 */
export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(withFetch(), withInterceptors([authInterceptor, errorInterceptor])),
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
    provideAuth0(environment.auth0),
  ],
};
