// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

import { FooterComponent } from './layout/footer/footer';
import { HeaderComponent } from './layout/header/header';
import { ToastContainerComponent } from './shared/components/toast-container/toast-container.component';

/**
 * Root application shell. Wraps the routed view in a header/footer layout.
 *
 * Accessibility: uses semantic landmarks (<header>, <main>, <footer>) provided
 * by child components and the host template. The global toast queue lives at
 * the root so all routes share a single live region.
 */
@Component({
  selector: 'app-root',
  imports: [RouterOutlet, HeaderComponent, FooterComponent, ToastContainerComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App {}
