// Generated by GitHub Copilot
import { Routes } from '@angular/router';

import { authGuard } from './core/auth/auth.guard';

/**
 * Application route table.
 *
 * - `/`            redirects to `/dashboard`.
 * - `/login`       Public sign-in page (Auth0 redirect launcher).
 * - `/auth/callback` Public landing for the Auth0 redirect.
 * - `/dashboard`   Protected by `authGuard` — redirects to `/login` when anonymous.
 *
 * Lazy-loading keeps the initial bundle small. Public RSVP routes (Phase 4)
 * will be added later and intentionally remain unguarded.
 */
export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
  {
    path: 'login',
    loadComponent: () =>
      import('./features/auth/login/login.component').then((m) => m.LoginComponent),
    title: 'Sign in — EventSync',
  },
  {
    path: 'auth/callback',
    loadComponent: () =>
      import('./features/auth/auth-callback/auth-callback.component').then(
        (m) => m.AuthCallbackComponent,
      ),
    title: 'Signing in — EventSync',
  },
  {
    path: 'dashboard',
    canActivate: [authGuard],
    loadComponent: () =>
      import('./features/dashboard/dashboard.component').then((m) => m.DashboardComponent),
    title: 'Dashboard — EventSync',
  },
  {
    path: 'events',
    canActivate: [authGuard],
    loadChildren: () =>
      import('./features/events/events.routes').then((m) => m.EVENTS_ROUTES),
  },
  // Public RSVP — intentionally unguarded. Anyone with a valid invite token
  // may view and submit; server-side validation is the sole authority.
  {
    path: 'rsvp',
    loadChildren: () =>
      import('./features/public-rsvp/public-rsvp.routes').then((m) => m.PUBLIC_RSVP_ROUTES),
  },
  { path: '**', redirectTo: 'dashboard' },
];
