// Generated by GitHub Copilot
import { provideHttpClient, withFetch, withInterceptors } from '@angular/common/http';
import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideAuth0 } from '@auth0/auth0-angular';

import { authInterceptor } from './core/auth/auth.interceptor';
import { environment } from '../environments/environment';
import { routes } from './app.routes';

/**
 * Application-wide DI configuration.
 *
 * Providers:
 * - `provideRouter`              — lazy-loaded route table.
 * - `provideHttpClient(withFetch())` — modern Fetch-backed HttpClient.
 * - `withInterceptors([authInterceptor])` — attaches Bearer tokens to API calls.
 * - `provideAuth0(...)`          — initialises the Auth0 SPA SDK with the
 *   tenant settings from `environment.auth0`.
 */
export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(withFetch(), withInterceptors([authInterceptor])),
    provideAuth0(environment.auth0),
  ],
};
