// Generated by GitHub Copilot
import { AbstractControl, ValidationErrors, ValidatorFn } from '@angular/forms';

/**
 * Reactive-form validator: fails when the bound `Date`/string value is in the
 * past (relative to `Date.now()`).
 *
 * Empty values pass — combine with `Validators.required` to make a field mandatory.
 */
export function futureDate(): ValidatorFn {
  return (control: AbstractControl): ValidationErrors | null => {
    const value = control.value;
    if (value === null || value === undefined || value === '') {
      return null;
    }
    const candidate = new Date(value as string);
    if (Number.isNaN(candidate.getTime())) {
      return { invalidDate: true };
    }
    return candidate.getTime() > Date.now() ? null : { futureDate: true };
  };
}

/**
 * Validator: fails when the value is not a syntactically valid absolute http(s) URL.
 *
 * Empty values pass.
 */
export function urlFormat(): ValidatorFn {
  return (control: AbstractControl): ValidationErrors | null => {
    const value = control.value;
    if (value === null || value === undefined || value === '') {
      return null;
    }
    try {
      const url = new URL(String(value));
      return url.protocol === 'http:' || url.protocol === 'https:'
        ? null
        : { urlFormat: true };
    } catch {
      return { urlFormat: true };
    }
  };
}

/**
 * Cross-field validator: place on the `endDate` control to require it to be
 * strictly after the value of a sibling control identified by name.
 *
 * Returns `null` when either field is empty (the individual validators handle
 * "required" semantics).
 */
export function dateAfter(siblingControlName: string): ValidatorFn {
  return (control: AbstractControl): ValidationErrors | null => {
    const value = control.value;
    if (value === null || value === undefined || value === '') {
      return null;
    }
    const parent = control.parent;
    if (!parent) {
      return null;
    }
    const sibling = parent.get(siblingControlName);
    const siblingValue = sibling?.value;
    if (siblingValue === null || siblingValue === undefined || siblingValue === '') {
      return null;
    }
    const start = new Date(siblingValue as string).getTime();
    const end = new Date(value as string).getTime();
    if (Number.isNaN(start) || Number.isNaN(end)) {
      return { invalidDate: true };
    }
    return end > start ? null : { dateAfter: { siblingControlName } };
  };
}
