// Generated by GitHub Copilot
using EventSync.Api.Common.Configuration;
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Features.Events.Common;
using EventSync.Api.Features.InviteLinks.CreateInviteLink;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace EventSync.Api.Features.InviteLinks.GetInviteLinks;

/// <summary>
/// Query: list every invite link for an event the current user organizes.
/// </summary>
/// <param name="EventId">Owning event identifier.</param>
public sealed record GetInviteLinksQuery(Guid EventId) : IRequest<IReadOnlyList<InviteLinkDto>>;

/// <summary>Handler for <see cref="GetInviteLinksQuery"/>.</summary>
public sealed class GetInviteLinksHandler
    : IRequestHandler<GetInviteLinksQuery, IReadOnlyList<InviteLinkDto>>
{
    private readonly ICurrentUserService _currentUser;
    private readonly AppDbContext _dbContext;
    private readonly FrontendOptions _frontend;

    /// <summary>Initializes a new instance of <see cref="GetInviteLinksHandler"/>.</summary>
    public GetInviteLinksHandler(
        ICurrentUserService currentUser,
        AppDbContext dbContext,
        IOptions<FrontendOptions> frontendOptions)
    {
        _currentUser = currentUser;
        _dbContext = dbContext;
        _frontend = frontendOptions.Value;
    }

    /// <inheritdoc/>
    /// <exception cref="KeyNotFoundException">Event does not exist.</exception>
    /// <exception cref="UnauthorizedAccessException">Event is owned by another user.</exception>
    public async Task<IReadOnlyList<InviteLinkDto>> Handle(
        GetInviteLinksQuery request,
        CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var ev = await _dbContext.Events
            .AsNoTracking()
            .FirstOrDefaultAsync(e => e.Id == request.EventId, cancellationToken)
            ?? throw new KeyNotFoundException($"Event {request.EventId} not found.");

        if (ev.OrganizerId != user.Id)
        {
            throw new UnauthorizedAccessException("You do not have access to this event's invite links.");
        }

        var links = await _dbContext.InviteLinks
            .AsNoTracking()
            .Where(l => l.EventId == ev.Id)
            .OrderByDescending(l => l.CreatedAt)
            .ToListAsync(cancellationToken);

        return links.Select(l => CreateInviteLinkHandler.ToDto(l, _frontend.BaseUrl)).ToList();
    }
}
