// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';

/**
 * Site footer. Renders copyright with a reactive current year.
 *
 * Accessibility: rendered as a <footer> landmark.
 */
@Component({
  selector: 'app-footer',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './footer.html',
  styleUrl: './footer.css',
})
export class FooterComponent {
  /** Captured at construction; templates must not call new Date() directly. */
  private readonly nowYear = signal(new Date().getFullYear());

  /** Year used in the copyright line. */
  protected readonly year = computed(() => this.nowYear());
}
