// Generated by GitHub Copilot
import { DatePipe } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  signal,
} from '@angular/core';
import { Router, RouterLink } from '@angular/router';

import { EventService } from '../../../core/api/event.service';
import { environment } from '../../../../environments/environment';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { LoadingSpinnerComponent } from '../../../shared/components/loading-spinner/loading-spinner.component';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';
import { RelativeDatePipe } from '../../../shared/pipes/relative-date.pipe';
import { InviteLinkManagerComponent } from './invite-link-manager/invite-link-manager.component';
import { RsvpListComponent } from './rsvp-list/rsvp-list.component';

type DialogKind = 'cancel' | 'delete' | null;

/**
 * Read-only detail page for a single event.
 *
 * Loads the event by id (route param bound via `withComponentInputBinding`),
 * shows status badges, organizer + RSVP summary cards, and the destructive
 * action buttons (Edit, Cancel, Delete). Cancel and Delete go through the
 * shared `ConfirmDialogComponent`.
 */
@Component({
  selector: 'app-event-detail',
  imports: [
    RouterLink,
    DatePipe,
    RelativeDatePipe,
    StatusBadgeComponent,
    LoadingSpinnerComponent,
    ConfirmDialogComponent,
    InviteLinkManagerComponent,
    RsvpListComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './event-detail.component.html',
})
export class EventDetailComponent {
  private readonly eventService = inject(EventService);
  private readonly router = inject(Router);

  /** Route parameter — bound by `withComponentInputBinding`. */
  readonly id = input.required<string>();

  protected readonly loading = signal(true);
  protected readonly errorMessage = signal<string | null>(null);
  protected readonly busy = signal(false);
  protected readonly openDialog = signal<DialogKind>(null);

  protected readonly event = this.eventService.selectedEvent;

  /** Resolves a relative server path to a full URL for image display. */
  protected readonly coverImageSrc = computed(() => {
    const url = this.event()?.coverImageUrl;
    if (!url) return null;
    // Already absolute (external URL) — use as-is.
    if (url.startsWith('http://') || url.startsWith('https://')) return url;
    // Relative path from upload endpoint — prepend the API origin.
    const apiOrigin = environment.apiUrl.replace(/\/api\/v1$/, '');
    return `${apiOrigin}${url}`;
  });

  protected readonly status = computed<{ text: string; variant: 'success' | 'danger' | 'default' }>(
    () => {
      const ev = this.event();
      if (!ev) return { text: 'Loading', variant: 'default' };
      if (ev.isCancelled) return { text: 'Cancelled', variant: 'danger' };
      const upcoming = new Date(ev.startDate).getTime() > Date.now();
      return upcoming
        ? { text: 'Upcoming', variant: 'success' }
        : { text: 'Past', variant: 'default' };
    },
  );

  protected readonly descriptionLines = computed(() => {
    const desc = this.event()?.description;
    if (!desc) return [] as string[];
    return desc.split(/\r?\n/);
  });

  // eslint-disable-next-line @typescript-eslint/no-unused-private-class-members
  private readonly loadEvent = effect(() => {
    const id = this.id();
    if (!id) return;
    this.loading.set(true);
    this.errorMessage.set(null);
    this.eventService.getEvent(id).subscribe({
      next: () => this.loading.set(false),
      error: () => {
        this.loading.set(false);
        this.errorMessage.set(this.eventService.error() ?? 'Could not load event.');
      },
    });
  });

  protected requestCancel(): void {
    this.openDialog.set('cancel');
  }

  protected requestDelete(): void {
    this.openDialog.set('delete');
  }

  protected closeDialog(): void {
    this.openDialog.set(null);
  }

  protected confirmCancel(): void {
    const ev = this.event();
    if (!ev || this.busy()) return;
    this.busy.set(true);
    this.eventService.cancelEvent(ev.id).subscribe({
      next: () => {
        this.busy.set(false);
        this.closeDialog();
        this.eventService.getEvent(ev.id).subscribe({ error: () => undefined });
      },
      error: () => {
        this.busy.set(false);
        this.closeDialog();
        this.errorMessage.set(this.eventService.error() ?? 'Could not cancel event.');
      },
    });
  }

  protected confirmDelete(): void {
    const ev = this.event();
    if (!ev || this.busy()) return;
    this.busy.set(true);
    this.eventService.deleteEvent(ev.id).subscribe({
      next: () => {
        this.busy.set(false);
        this.closeDialog();
        this.router.navigate(['/events']);
      },
      error: () => {
        this.busy.set(false);
        this.closeDialog();
        this.errorMessage.set(this.eventService.error() ?? 'Could not delete event.');
      },
    });
  }
}
