// Generated by GitHub Copilot
using EventSync.Api.Common.Exceptions;
using EventSync.Api.Common.Models;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.Events.Common;
using EventSync.Api.Features.RSVPs.Common;
using EventSync.Api.Features.RSVPs.GetPublicEvent;
using EventSync.Api.Features.RSVPs.GetRsvps;
using EventSync.Api.Features.RSVPs.GetRsvpSummary;
using EventSync.Api.Features.RSVPs.SubmitRsvp;
using MediatR;

namespace EventSync.Api.Features.RSVPs;

/// <summary>
/// Maps RSVP minimal-API endpoints. Splits the route table into:
/// <list type="bullet">
///   <item>Authenticated organizer endpoints under <c>/api/v1/events/{eventId}/rsvps</c></item>
///   <item>Anonymous public endpoints under <c>/api/v1/invite/{token}</c></item>
/// </list>
/// </summary>
public static class RsvpEndpoints
{
    /// <summary>Registers all RSVP endpoints.</summary>
    /// <param name="app">Endpoint route builder.</param>
    /// <param name="rsvpRateLimitPolicy">
    /// Optional named rate-limit policy applied to <c>POST /api/v1/invite/{token}/rsvp</c>.
    /// When <c>null</c>, no rate limit is enforced (useful for tests).
    /// </param>
    public static IEndpointRouteBuilder MapRsvpEndpoints(
        this IEndpointRouteBuilder app,
        string? rsvpRateLimitPolicy = null)
    {
        MapOrganizerEndpoints(app);
        MapPublicEndpoints(app, rsvpRateLimitPolicy);
        return app;
    }

    /// <summary>
    /// Authenticated organizer endpoints. <c>RequireAuthorization()</c> is applied at the group
    /// level so every child inherits authentication automatically.
    /// </summary>
    private static void MapOrganizerEndpoints(IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/v1/events/{eventId:guid}/rsvps")
            .WithTags("RSVPs")
            .RequireAuthorization();

        group.MapGet("/", async (
            Guid eventId,
            RsvpStatus? status,
            int? page,
            int? pageSize,
            IMediator mediator,
            CancellationToken ct) =>
        {
            try
            {
                var result = await mediator.Send(
                    new GetRsvpsQuery(eventId, status, page ?? 1, pageSize ?? 20),
                    ct);
                return Results.Ok(result);
            }
            catch (KeyNotFoundException ex)
            {
                return Results.NotFound(new { error = ex.Message });
            }
            catch (UnauthorizedAccessException)
            {
                return Results.Forbid();
            }
        })
        .WithName("GetRsvps")
        .WithSummary("List RSVPs for an event you organize, optionally filtered by status.")
        .Produces<PagedResult<RsvpDto>>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status401Unauthorized)
        .Produces(StatusCodes.Status403Forbidden)
        .Produces(StatusCodes.Status404NotFound);

        group.MapGet("/summary", async (Guid eventId, IMediator mediator, CancellationToken ct) =>
        {
            try
            {
                var summary = await mediator.Send(new GetRsvpSummaryQuery(eventId), ct);
                return Results.Ok(summary);
            }
            catch (KeyNotFoundException ex)
            {
                return Results.NotFound(new { error = ex.Message });
            }
            catch (UnauthorizedAccessException)
            {
                return Results.Forbid();
            }
        })
        .WithName("GetRsvpSummary")
        .WithSummary("Aggregate RSVP counts for an event you organize.")
        .Produces<RsvpSummaryDto>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status401Unauthorized)
        .Produces(StatusCodes.Status403Forbidden)
        .Produces(StatusCodes.Status404NotFound);
    }

    /// <summary>
    /// Anonymous public endpoints. Each route is explicitly tagged
    /// <c>AllowAnonymous</c> per the security checklist; the absence of
    /// <c>RequireAuthorization</c> alone is not considered sufficient.
    /// </summary>
    private static void MapPublicEndpoints(IEndpointRouteBuilder app, string? rsvpRateLimitPolicy)
    {
        var group = app.MapGroup("/api/v1/invite/{token}")
            .WithTags("Public RSVP")
            .AllowAnonymous();

        group.MapGet("/", async (string token, IMediator mediator, CancellationToken ct) =>
        {
            try
            {
                var dto = await mediator.Send(new GetPublicEventQuery(token), ct);
                return Results.Ok(dto);
            }
            catch (InvalidInviteException ex)
            {
                return Results.Json(
                    new { message = ex.Message },
                    statusCode: StatusCodes.Status410Gone);
            }
        })
        .WithName("GetPublicEvent")
        .WithSummary("Load the public event projection for a guest visiting an invite URL.")
        .AllowAnonymous()
        .Produces<PublicEventDto>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status410Gone);

        var submitRsvp = group.MapPost("/rsvp", async (
            string token,
            SubmitRsvpRequest body,
            HttpContext httpContext,
            IMediator mediator,
            CancellationToken ct) =>
        {
            var ipAddress = ResolveCallerIp(httpContext);
            var command = new SubmitRsvpCommand(
                token,
                body.GuestName ?? string.Empty,
                body.GuestEmail,
                body.Status,
                body.Note)
            {
                IpAddress = ipAddress,
            };

            // ValidationException + InvalidInviteException are translated to
            // 400 / 410 by the global ExceptionHandlingMiddleware.
            var confirmation = await mediator.Send(command, ct);
            return Results.Created($"/api/v1/invite/{token}/rsvp/{confirmation.Id}", confirmation);
        })
        .WithName("SubmitRsvp")
        .WithSummary("Anonymously submit (or update) an RSVP for an invite token.")
        .AllowAnonymous()
        .Produces<RsvpConfirmationDto>(StatusCodes.Status201Created)
        .ProducesValidationProblem()
        .Produces(StatusCodes.Status410Gone)
        .Produces(StatusCodes.Status429TooManyRequests);

        if (!string.IsNullOrWhiteSpace(rsvpRateLimitPolicy))
        {
            submitRsvp.RequireRateLimiting(rsvpRateLimitPolicy);
        }
    }

    /// <summary>
    /// Resolves the caller's IP address. Honours the first hop of <c>X-Forwarded-For</c>
    /// when present (common behind reverse proxies); otherwise falls back to the
    /// transport-level remote address.
    /// </summary>
    /// <remarks>
    /// Note: the X-Forwarded-For header is attacker-controlled and is stored as
    /// audit metadata only. It must NEVER be used for authorization decisions.
    /// </remarks>
    private static string? ResolveCallerIp(HttpContext httpContext)
    {
        if (httpContext.Request.Headers.TryGetValue("X-Forwarded-For", out var forwarded) &&
            !string.IsNullOrWhiteSpace(forwarded))
        {
            var firstHop = forwarded.ToString().Split(',', 2)[0].Trim();
            if (!string.IsNullOrEmpty(firstHop))
            {
                return firstHop;
            }
        }

        return httpContext.Connection.RemoteIpAddress?.ToString();
    }
}

/// <summary>
/// Public request payload for <c>POST /api/v1/invite/{token}/rsvp</c>.
/// </summary>
/// <param name="GuestName">Required guest display name.</param>
/// <param name="GuestEmail">Optional contact email.</param>
/// <param name="Status">Going / NotGoing / Maybe.</param>
/// <param name="Note">Optional free-text note.</param>
public sealed record SubmitRsvpRequest(
    string? GuestName,
    string? GuestEmail,
    RsvpStatus Status,
    string? Note);
