// Generated by GitHub Copilot
using EventSync.Api.Common.Models;
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.RSVPs.Common;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.RSVPs.GetRsvps;

/// <summary>
/// Query: paginated list of RSVPs for an event the current user organizes.
/// </summary>
/// <param name="EventId">Owning event identifier.</param>
/// <param name="Status">Optional status filter.</param>
/// <param name="Page">1-based page number.</param>
/// <param name="PageSize">Items per page (capped at 100).</param>
public sealed record GetRsvpsQuery(
    Guid EventId,
    RsvpStatus? Status,
    int Page = 1,
    int PageSize = 20) : IRequest<PagedResult<RsvpDto>>;

/// <summary>Handler for <see cref="GetRsvpsQuery"/>.</summary>
public sealed class GetRsvpsHandler : IRequestHandler<GetRsvpsQuery, PagedResult<RsvpDto>>
{
    private readonly AppDbContext _dbContext;
    private readonly ICurrentUserService _currentUser;

    /// <summary>Initializes a new instance of <see cref="GetRsvpsHandler"/>.</summary>
    public GetRsvpsHandler(AppDbContext dbContext, ICurrentUserService currentUser)
    {
        _dbContext = dbContext;
        _currentUser = currentUser;
    }

    /// <inheritdoc/>
    /// <exception cref="KeyNotFoundException">Event does not exist.</exception>
    /// <exception cref="UnauthorizedAccessException">Event is owned by another user.</exception>
    public async Task<PagedResult<RsvpDto>> Handle(GetRsvpsQuery request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var ev = await _dbContext.Events
            .AsNoTracking()
            .FirstOrDefaultAsync(e => e.Id == request.EventId, cancellationToken)
            ?? throw new KeyNotFoundException($"Event {request.EventId} not found.");

        if (ev.OrganizerId != user.Id)
        {
            throw new UnauthorizedAccessException("You do not have access to this event's RSVPs.");
        }

        var page = request.Page < 1 ? 1 : request.Page;
        var pageSize = request.PageSize switch
        {
            < 1 => 20,
            > 100 => 100,
            _ => request.PageSize,
        };

        var query = _dbContext.Rsvps
            .AsNoTracking()
            .Where(r => r.EventId == ev.Id);

        if (request.Status.HasValue)
        {
            query = query.Where(r => r.Status == request.Status.Value);
        }

        var total = await query.CountAsync(cancellationToken);

        var items = await query
            .OrderByDescending(r => r.RespondedAt)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .Select(r => new RsvpDto(
                r.Id,
                r.GuestName,
                r.GuestEmail,
                r.Status,
                r.Note,
                r.RespondedAt,
                r.UpdatedAt))
            .ToListAsync(cancellationToken);

        return new PagedResult<RsvpDto>(items, page, pageSize, total);
    }
}
