// Generated by GitHub Copilot
using EventSync.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EventSync.Api.Data.Configurations;

/// <summary>
/// EF Core configuration for <see cref="Event"/>.
/// </summary>
public sealed class EventConfiguration : IEntityTypeConfiguration<Event>
{
    /// <inheritdoc/>
    public void Configure(EntityTypeBuilder<Event> builder)
    {
        builder.ToTable("Events");

        builder.HasKey(e => e.Id);

        builder.Property(e => e.Title).HasMaxLength(200).IsRequired();
        builder.Property(e => e.Description).HasMaxLength(2000);
        builder.Property(e => e.Location).HasMaxLength(300);
        builder.Property(e => e.MeetingUrl).HasMaxLength(512);
        builder.Property(e => e.CoverImageUrl).HasMaxLength(512);
        builder.Property(e => e.IsVirtual).HasDefaultValue(false);
        builder.Property(e => e.IsDeleted).HasDefaultValue(false);
        builder.Property(e => e.IsCancelled).HasDefaultValue(false);
        builder.Property(e => e.CreatedAt).IsRequired();
        builder.Property(e => e.StartDate).IsRequired();

        builder.HasOne(e => e.Organizer)
               .WithMany(u => u.OrganizedEvents)
               .HasForeignKey(e => e.OrganizerId)
               .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne(e => e.EventType)
               .WithMany(t => t.Events)
               .HasForeignKey(e => e.EventTypeId)
               .OnDelete(DeleteBehavior.Restrict);

        builder.HasIndex(e => new { e.OrganizerId, e.IsDeleted });
        builder.HasIndex(e => e.StartDate);

        builder.HasQueryFilter(e => !e.IsDeleted);
    }
}
