// Generated by GitHub Copilot
using EventSync.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EventSync.Api.Data.Configurations;

/// <summary>
/// EF Core configuration for <see cref="EventType"/>.
/// </summary>
public sealed class EventTypeConfiguration : IEntityTypeConfiguration<EventType>
{
    /// <inheritdoc/>
    public void Configure(EntityTypeBuilder<EventType> builder)
    {
        builder.ToTable("EventTypes");

        builder.HasKey(t => t.Id);
        builder.Property(t => t.Id).ValueGeneratedOnAdd();

        builder.Property(t => t.Name).HasMaxLength(50).IsRequired();
        builder.Property(t => t.Icon).HasMaxLength(50);

        builder.HasIndex(t => t.Name).IsUnique();
    }
}
