// Generated by GitHub Copilot
using EventSync.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EventSync.Api.Data.Configurations;

/// <summary>
/// EF Core configuration for <see cref="InviteLink"/>.
/// </summary>
public sealed class InviteLinkConfiguration : IEntityTypeConfiguration<InviteLink>
{
    /// <inheritdoc/>
    public void Configure(EntityTypeBuilder<InviteLink> builder)
    {
        builder.ToTable("InviteLinks");

        builder.HasKey(i => i.Id);

        builder.Property(i => i.Token).HasMaxLength(64).IsRequired();
        builder.Property(i => i.UseCount).HasDefaultValue(0);
        builder.Property(i => i.IsActive).HasDefaultValue(true);
        builder.Property(i => i.CreatedAt).IsRequired();

        builder.HasOne(i => i.Event)
               .WithMany(e => e.InviteLinks)
               .HasForeignKey(i => i.EventId)
               .OnDelete(DeleteBehavior.Cascade);

        // Match parent Event soft-delete filter.
        builder.HasQueryFilter(i => !i.Event.IsDeleted);

        builder.HasIndex(i => i.Token).IsUnique();
    }
}
