// Generated by GitHub Copilot
using EventSync.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EventSync.Api.Data.Configurations;

/// <summary>
/// EF Core configuration for <see cref="Rsvp"/>.
/// </summary>
public sealed class RsvpConfiguration : IEntityTypeConfiguration<Rsvp>
{
    /// <inheritdoc/>
    public void Configure(EntityTypeBuilder<Rsvp> builder)
    {
        builder.ToTable("Rsvps");

        builder.HasKey(r => r.Id);

        builder.Property(r => r.GuestName).HasMaxLength(100).IsRequired();
        builder.Property(r => r.GuestEmail).HasMaxLength(256);
        builder.Property(r => r.Status).HasConversion<byte>().IsRequired();
        builder.Property(r => r.Note).HasMaxLength(500);
        builder.Property(r => r.IpAddress).HasMaxLength(45);
        builder.Property(r => r.RespondedAt).IsRequired();

        // Restrict on Event side to avoid SQL Server multiple-cascade-paths via InviteLinks.
        builder.HasOne(r => r.Event)
               .WithMany(e => e.Rsvps)
               .HasForeignKey(r => r.EventId)
               .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne(r => r.InviteLink)
               .WithMany(i => i.Rsvps)
               .HasForeignKey(r => r.InviteLinkId)
               .OnDelete(DeleteBehavior.SetNull);

        // Match parent Event soft-delete filter so navigations stay consistent.
        builder.HasQueryFilter(r => !r.Event.IsDeleted);

        builder.HasIndex(r => new { r.EventId, r.Status });

        // Filtered unique index: one RSVP per (Event, Email) when email is supplied.
        builder.HasIndex(r => new { r.GuestEmail, r.EventId })
               .IsUnique()
               .HasFilter("[GuestEmail] IS NOT NULL");
    }
}
