// Generated by GitHub Copilot
using EventSync.Api.Features.Events.Common;
using EventSync.Api.Features.InviteLinks.CreateInviteLink;
using EventSync.Api.Features.InviteLinks.DeactivateInviteLink;
using EventSync.Api.Features.InviteLinks.GetInviteLinks;
using FluentValidation;
using MediatR;

namespace EventSync.Api.Features.InviteLinks;

/// <summary>
/// Maps invite-link minimal-API endpoints onto the application route table.
/// All endpoints require a valid bearer token (organizer-only).
/// </summary>
public static class InviteLinkEndpoints
{
    /// <summary>
    /// Registers <c>/api/v1/events/{eventId}/invite-links</c> and
    /// <c>/api/v1/invite-links/{linkId}</c>.
    /// </summary>
    public static IEndpointRouteBuilder MapInviteLinkEndpoints(this IEndpointRouteBuilder app)
    {
        var perEventGroup = app.MapGroup("/api/v1/events/{eventId:guid}/invite-links")
            .WithTags("Invite Links")
            .RequireAuthorization();

        perEventGroup.MapGet("/", async (Guid eventId, IMediator mediator, CancellationToken ct) =>
        {
            try
            {
                var links = await mediator.Send(new GetInviteLinksQuery(eventId), ct);
                return Results.Ok(links);
            }
            catch (KeyNotFoundException ex)
            {
                return Results.NotFound(new { error = ex.Message });
            }
            catch (UnauthorizedAccessException)
            {
                return Results.Forbid();
            }
        })
        .WithName("GetInviteLinks")
        .WithSummary("List all invite links for an event you organize.")
        .Produces<IReadOnlyList<InviteLinkDto>>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status401Unauthorized)
        .Produces(StatusCodes.Status403Forbidden)
        .Produces(StatusCodes.Status404NotFound);

        perEventGroup.MapPost("/", async (
            Guid eventId,
            CreateInviteLinkCommand body,
            IMediator mediator,
            CancellationToken ct) =>
        {
            try
            {
                // Bind the route id authoritatively; ignore any mismatched id in the body.
                var command = body with { EventId = eventId };
                var dto = await mediator.Send(command, ct);
                return Results.Created($"/api/v1/invite-links/{dto.Id}", dto);
            }
            catch (ValidationException ex)
            {
                return Results.ValidationProblem(
                    ex.Errors.GroupBy(e => e.PropertyName)
                        .ToDictionary(g => g.Key, g => g.Select(e => e.ErrorMessage).ToArray()));
            }
            catch (KeyNotFoundException ex)
            {
                return Results.NotFound(new { error = ex.Message });
            }
            catch (UnauthorizedAccessException)
            {
                return Results.Forbid();
            }
        })
        .WithName("CreateInviteLink")
        .WithSummary("Create a new shareable invite link for an event you organize.")
        .Produces<InviteLinkDto>(StatusCodes.Status201Created)
        .ProducesValidationProblem()
        .Produces(StatusCodes.Status401Unauthorized)
        .Produces(StatusCodes.Status403Forbidden)
        .Produces(StatusCodes.Status404NotFound);

        var linkGroup = app.MapGroup("/api/v1/invite-links")
            .WithTags("Invite Links")
            .RequireAuthorization();

        linkGroup.MapDelete("/{linkId:guid}", async (Guid linkId, IMediator mediator, CancellationToken ct) =>
        {
            try
            {
                await mediator.Send(new DeactivateInviteLinkCommand(linkId), ct);
                return Results.NoContent();
            }
            catch (KeyNotFoundException ex)
            {
                return Results.NotFound(new { error = ex.Message });
            }
            catch (UnauthorizedAccessException)
            {
                return Results.Forbid();
            }
        })
        .WithName("DeactivateInviteLink")
        .WithSummary("Deactivate (soft-disable) an invite link.")
        .Produces(StatusCodes.Status204NoContent)
        .Produces(StatusCodes.Status401Unauthorized)
        .Produces(StatusCodes.Status403Forbidden)
        .Produces(StatusCodes.Status404NotFound);

        return app;
    }
}
