// Generated by GitHub Copilot
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using FluentValidation;
using MediatR;

namespace EventSync.Api.Features.Auth.UpdateProfile;

/// <summary>
/// Request: update the current user's display name and/or avatar URL.
/// </summary>
/// <param name="DisplayName">Required. Length 1–100.</param>
/// <param name="AvatarUrl">Optional. When provided must be a valid absolute URL up to 512 chars.</param>
public sealed record UpdateProfileCommand(string DisplayName, string? AvatarUrl)
    : IRequest<UserProfileDto>;

/// <summary>FluentValidation rules for <see cref="UpdateProfileCommand"/>.</summary>
public sealed class UpdateProfileValidator : AbstractValidator<UpdateProfileCommand>
{
    /// <summary>Configures the validation rules.</summary>
    public UpdateProfileValidator()
    {
        RuleFor(x => x.DisplayName)
            .NotEmpty()
            .MaximumLength(100);

        RuleFor(x => x.AvatarUrl)
            .MaximumLength(512)
            .Must(BeAValidAbsoluteUrl)
                .WithMessage("AvatarUrl must be a valid absolute http(s) URL.")
            .When(x => !string.IsNullOrWhiteSpace(x.AvatarUrl));
    }

    private static bool BeAValidAbsoluteUrl(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return true;
        }

        return Uri.TryCreate(value, UriKind.Absolute, out var uri)
            && (uri.Scheme == Uri.UriSchemeHttp || uri.Scheme == Uri.UriSchemeHttps);
    }
}

/// <summary>Handler for <see cref="UpdateProfileCommand"/>.</summary>
public sealed class UpdateProfileHandler : IRequestHandler<UpdateProfileCommand, UserProfileDto>
{
    private readonly ICurrentUserService _currentUser;
    private readonly AppDbContext _dbContext;

    /// <summary>Initializes a new instance of <see cref="UpdateProfileHandler"/>.</summary>
    /// <param name="currentUser">Current-user accessor.</param>
    /// <param name="dbContext">EF Core context.</param>
    public UpdateProfileHandler(ICurrentUserService currentUser, AppDbContext dbContext)
    {
        _currentUser = currentUser;
        _dbContext = dbContext;
    }

    /// <inheritdoc/>
    public async Task<UserProfileDto> Handle(UpdateProfileCommand request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        user.DisplayName = request.DisplayName.Trim();
        user.AvatarUrl = string.IsNullOrWhiteSpace(request.AvatarUrl) ? null : request.AvatarUrl.Trim();
        user.UpdatedAt = DateTime.Now;

        await _dbContext.SaveChangesAsync(cancellationToken);

        return new UserProfileDto(user.Id, user.Email, user.DisplayName, user.AvatarUrl);
    }
}
