// Generated by GitHub Copilot
import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { Router, RouterLink } from '@angular/router';

import {
  type RsvpConfirmationDto,
  RsvpStatus,
} from '../../../core/models/rsvp.model';
import { StatusBadgeComponent, type StatusBadgeVariant } from '../../../shared/components/status-badge/status-badge.component';

/** Display descriptor for the chosen status. */
interface StatusDisplay {
  readonly text: string;
  readonly variant: StatusBadgeVariant;
}

/**
 * Public confirmation screen rendered after a successful RSVP submission.
 *
 * The originating page passes the `RsvpConfirmationDto` via `history.state`,
 * which avoids leaking guest details into the URL while still saving a server
 * round-trip. If the state is missing (deep link, hard refresh, etc.) we
 * gracefully fall back to a generic thank-you message.
 */
@Component({
  selector: 'app-rsvp-confirmation',
  imports: [DatePipe, RouterLink, StatusBadgeComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './rsvp-confirmation.component.html',
})
export class RsvpConfirmationComponent {
  private readonly router = inject(Router);

  /** Route parameter \u2014 bound by `withComponentInputBinding`. */
  readonly token = input.required<string>();

  /**
   * Reads the confirmation payload from the navigation state once.
   *
   * `getCurrentNavigation()` is null on direct page loads; we then fall back
   * to `history.state`, which the browser preserves across the routed
   * navigation if it was set via `router.navigate(..., { state })`.
   */
  protected readonly confirmation = computed<RsvpConfirmationDto | null>(() => {
    const fromNav = this.router.getCurrentNavigation()?.extras?.state as
      | { confirmation?: RsvpConfirmationDto }
      | undefined;
    if (fromNav?.confirmation) return fromNav.confirmation;

    if (typeof history !== 'undefined') {
      const fromHistory = history.state as { confirmation?: RsvpConfirmationDto } | null;
      return fromHistory?.confirmation ?? null;
    }
    return null;
  });

  /** Status badge text + colour for the confirmation card. */
  protected readonly statusDisplay = computed<StatusDisplay | null>(() => {
    const c = this.confirmation();
    if (!c) return null;
    switch (c.status) {
      case RsvpStatus.Going:
        return { text: 'Going', variant: 'success' };
      case RsvpStatus.Maybe:
        return { text: 'Maybe', variant: 'warning' };
      case RsvpStatus.NotGoing:
        return { text: 'Not going', variant: 'danger' };
      default:
        return { text: 'Recorded', variant: 'default' };
    }
  });
}
