// Generated by GitHub Copilot
import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';

import { environment } from '../../../environments/environment';
import type { UserProfileDto } from '../models/user-profile.model';

/** Payload accepted by `PUT /auth/profile`. */
export interface UpdateProfilePayload {
  readonly displayName: string;
  readonly avatarUrl?: string | null;
}

/**
 * Typed client for the `/api/v1/auth/*` endpoints.
 *
 * The Auth0 bearer token is attached automatically by `authInterceptor`,
 * so callers don't need to deal with headers.
 */
@Injectable({ providedIn: 'root' })
export class AuthApiService {
  private readonly http = inject(HttpClient);
  private readonly baseUrl = `${environment.apiUrl}/auth`;

  /** GET the current user's profile (provisions on first call). */
  getProfile(): Observable<UserProfileDto> {
    return this.http.get<UserProfileDto>(`${this.baseUrl}/profile`);
  }

  /** PUT updates to the current user's profile. */
  updateProfile(payload: UpdateProfilePayload): Observable<UserProfileDto> {
    return this.http.put<UserProfileDto>(`${this.baseUrl}/profile`, payload);
  }
}
