// Generated by GitHub Copilot
import { HttpClient, HttpParams } from '@angular/common/http';
import { Injectable, inject, signal } from '@angular/core';
import { Observable, tap } from 'rxjs';

import { environment } from '../../../environments/environment';
import type {
  CreateEventRequest,
  EventDetailDto,
  EventDto,
  EventListParams,
  EventSummaryDto,
  EventTypeDto,
  UpdateEventRequest,
} from '../models/event.model';
import type { PagedResult } from '../models/paged-result.model';

/**
 * Typed HTTP client + lightweight signal cache for the `/events` and
 * `/event-types` resources.
 *
 * The Auth0 bearer token is attached by `authInterceptor`, so callers never
 * touch headers. Each method returns the underlying `Observable` so component
 * code can compose with `toSignal`, async pipe, or imperative `.subscribe()`.
 *
 * Security: the API enforces ownership server-side. State held here is purely
 * a UI-cache; treating any field as authoritative for security decisions is
 * forbidden.
 */
@Injectable({ providedIn: 'root' })
export class EventService {
  private readonly http = inject(HttpClient);
  private readonly eventsUrl = `${environment.apiUrl}/events`;
  private readonly eventTypesUrl = `${environment.apiUrl}/event-types`;

  private readonly uploadsUrl = `${environment.apiUrl}/uploads`;

  /** Latest paged list returned by {@link getEvents}. `null` until first call. */
  readonly events = signal<PagedResult<EventSummaryDto> | null>(null);

  /** Last event loaded by {@link getEvent}. `null` until first call. */
  readonly selectedEvent = signal<EventDetailDto | null>(null);

  /** Cached lookup list. Empty array until {@link getEventTypes} is called. */
  readonly eventTypes = signal<readonly EventTypeDto[]>([]);

  /** True while ANY method is in-flight. Components may use it for spinners. */
  readonly loading = signal(false);

  /** Most recent error message, or `null` on success. */
  readonly error = signal<string | null>(null);

  /** GET /events — paginated, filterable, sortable. */
  getEvents(params: EventListParams = {}): Observable<PagedResult<EventSummaryDto>> {
    let httpParams = new HttpParams();
    if (params.page !== undefined) httpParams = httpParams.set('page', params.page);
    if (params.pageSize !== undefined) httpParams = httpParams.set('pageSize', params.pageSize);
    if (params.search) httpParams = httpParams.set('search', params.search);
    if (params.typeId !== null && params.typeId !== undefined) {
      httpParams = httpParams.set('typeId', params.typeId);
    }
    if (params.sortBy) httpParams = httpParams.set('sortBy', params.sortBy);
    if (params.sortDir) httpParams = httpParams.set('sortDir', params.sortDir);

    return this.runWithState(
      this.http.get<PagedResult<EventSummaryDto>>(this.eventsUrl, { params: httpParams }),
    ).pipe(tap((result) => this.events.set(result)));
  }

  /** GET /events/{id} — full detail. */
  getEvent(id: string): Observable<EventDetailDto> {
    return this.runWithState(
      this.http.get<EventDetailDto>(`${this.eventsUrl}/${encodeURIComponent(id)}`),
    ).pipe(tap((result) => this.selectedEvent.set(result)));
  }

  /** POST /events — returns the created event. */
  createEvent(data: CreateEventRequest): Observable<EventDto> {
    return this.runWithState(this.http.post<EventDto>(this.eventsUrl, data));
  }

  /** PUT /events/{id} — returns the updated event. */
  updateEvent(id: string, data: UpdateEventRequest): Observable<EventDto> {
    return this.runWithState(
      this.http.put<EventDto>(`${this.eventsUrl}/${encodeURIComponent(id)}`, data),
    );
  }

  /** DELETE /events/{id} — soft-delete; returns 204. */
  deleteEvent(id: string): Observable<void> {
    return this.runWithState(
      this.http.delete<void>(`${this.eventsUrl}/${encodeURIComponent(id)}`),
    );
  }

  /** PATCH /events/{id}/cancel — returns 204. */
  cancelEvent(id: string): Observable<void> {
    return this.runWithState(
      this.http.patch<void>(`${this.eventsUrl}/${encodeURIComponent(id)}/cancel`, {}),
    );
  }

  /** GET /event-types — caches into the `eventTypes` signal. */
  getEventTypes(): Observable<EventTypeDto[]> {
    return this.runWithState(this.http.get<EventTypeDto[]>(this.eventTypesUrl)).pipe(
      tap((types) => this.eventTypes.set(types)),
    );
  }

  /**
   * POST /uploads/images — uploads a cover image file.
   * Returns the server-relative URL (e.g. `/uploads/events/abc.jpg`).
   */
  uploadImage(file: File): Observable<{ url: string }> {
    const formData = new FormData();
    formData.append('file', file);
    return this.runWithState(
      this.http.post<{ url: string }>(`${this.uploadsUrl}/images`, formData),
    );
  }

  /**
   * Wraps an HTTP observable with the shared `loading` / `error` signal updates.
   * Errors are re-thrown so caller `.subscribe({ error })` handlers still fire.
   */
  private runWithState<T>(source: Observable<T>): Observable<T> {
    this.loading.set(true);
    this.error.set(null);
    return new Observable<T>((subscriber) => {
      const sub = source.subscribe({
        next: (value) => subscriber.next(value),
        error: (err: unknown) => {
          this.loading.set(false);
          this.error.set(this.toMessage(err));
          subscriber.error(err);
        },
        complete: () => {
          this.loading.set(false);
          subscriber.complete();
        },
      });
      return () => sub.unsubscribe();
    });
  }

  /** Normalises an unknown error into a human-readable string. */
  private toMessage(err: unknown): string {
    if (typeof err === 'string') return err;
    if (err && typeof err === 'object') {
      const e = err as { error?: { detail?: string; title?: string }; message?: string };
      return e.error?.detail ?? e.error?.title ?? e.message ?? 'Request failed.';
    }
    return 'Request failed.';
  }
}
