// Generated by GitHub Copilot
import { HttpClient } from '@angular/common/http';
import { Injectable, inject, signal } from '@angular/core';
import { Observable, tap } from 'rxjs';

import { environment } from '../../../environments/environment';
import type {
  CreateInviteLinkRequest,
  InviteLinkDto,
} from '../models/invite-link.model';

/**
 * Typed HTTP client + signal cache for the `/events/{id}/invite-links` and
 * `/invite-links/{id}` resources.
 *
 * Security:
 * - The Auth0 bearer token is attached automatically by `authInterceptor`.
 * - Server-side ownership checks gate every endpoint; the cache here is
 *   strictly a UI convenience and MUST NOT be relied on for authorization.
 */
@Injectable({ providedIn: 'root' })
export class InviteLinkService {
  private readonly http = inject(HttpClient);
  private readonly eventsUrl = `${environment.apiUrl}/events`;
  private readonly linksUrl = `${environment.apiUrl}/invite-links`;

  /** Latest list returned by {@link getInviteLinks} (empty until first call). */
  readonly links = signal<readonly InviteLinkDto[]>([]);

  /** True while ANY method is in-flight. */
  readonly loading = signal(false);

  /** Most recent error message, or null on success. */
  readonly error = signal<string | null>(null);

  /** GET /events/{eventId}/invite-links — refreshes the {@link links} signal. */
  getInviteLinks(eventId: string): Observable<InviteLinkDto[]> {
    return this.run(
      this.http.get<InviteLinkDto[]>(
        `${this.eventsUrl}/${encodeURIComponent(eventId)}/invite-links`,
      ),
    ).pipe(tap((items) => this.links.set(items)));
  }

  /** POST /events/{eventId}/invite-links — prepends the new link to the cache. */
  createInviteLink(
    eventId: string,
    data: CreateInviteLinkRequest,
  ): Observable<InviteLinkDto> {
    return this.run(
      this.http.post<InviteLinkDto>(
        `${this.eventsUrl}/${encodeURIComponent(eventId)}/invite-links`,
        data,
      ),
    ).pipe(tap((link) => this.links.update((existing) => [link, ...existing])));
  }

  /** DELETE /invite-links/{linkId} — patches the cache to mark inactive. */
  deactivateLink(linkId: string): Observable<void> {
    return this.run(
      this.http.delete<void>(`${this.linksUrl}/${encodeURIComponent(linkId)}`),
    ).pipe(
      tap(() =>
        this.links.update((existing) =>
          existing.map((l) => (l.id === linkId ? { ...l, isActive: false } : l)),
        ),
      ),
    );
  }

  /** Wraps an HTTP observable with shared `loading` / `error` signal updates. */
  private run<T>(source: Observable<T>): Observable<T> {
    this.loading.set(true);
    this.error.set(null);
    return new Observable<T>((subscriber) => {
      const sub = source.subscribe({
        next: (value) => subscriber.next(value),
        error: (err: unknown) => {
          this.loading.set(false);
          this.error.set(this.toMessage(err));
          subscriber.error(err);
        },
        complete: () => {
          this.loading.set(false);
          subscriber.complete();
        },
      });
      return () => sub.unsubscribe();
    });
  }

  /** Normalises an unknown error into a human-readable string. */
  private toMessage(err: unknown): string {
    if (typeof err === 'string') return err;
    if (err && typeof err === 'object') {
      const e = err as { error?: { detail?: string; title?: string }; message?: string };
      return e.error?.detail ?? e.error?.title ?? e.message ?? 'Request failed.';
    }
    return 'Request failed.';
  }
}
