// Generated by GitHub Copilot
import { HttpClient, HttpParams } from '@angular/common/http';
import { Injectable, inject, signal } from '@angular/core';
import { Observable, tap } from 'rxjs';

import { environment } from '../../../environments/environment';
import type { PagedResult } from '../models/paged-result.model';
import type {
  PublicEventDto,
  RsvpConfirmationDto,
  RsvpDto,
  RsvpStatus,
  RsvpSummaryDto,
  SubmitRsvpRequest,
} from '../models/rsvp.model';

/** Pagination + filter parameters accepted by {@link RsvpService.getRsvps}. */
export interface GetRsvpsParams {
  readonly status?: RsvpStatus;
  readonly page: number;
  readonly pageSize: number;
}

/**
 * HTTP client for both the public and authenticated RSVP endpoints.
 *
 * Public methods ({@link getPublicEvent}, {@link submitRsvp}) target the
 * `/invite/{token}` routes which the auth interceptor explicitly skips, so
 * unauthenticated guests can hit them.
 *
 * Authenticated methods ({@link getRsvps}, {@link getRsvpSummary}) require an
 * Auth0 access token (attached automatically by `authInterceptor`).
 */
@Injectable({ providedIn: 'root' })
export class RsvpService {
  private readonly http = inject(HttpClient);
  private readonly inviteUrl = `${environment.apiUrl}/invite`;
  private readonly eventsUrl = `${environment.apiUrl}/events`;

  /** Most recent paged list of RSVPs (organizer view). */
  readonly rsvps = signal<PagedResult<RsvpDto> | null>(null);

  /** Most recent RSVP summary (organizer view). */
  readonly summary = signal<RsvpSummaryDto | null>(null);

  /** True while ANY method is in-flight. */
  readonly loading = signal(false);

  /** Most recent error message, or null on success. */
  readonly error = signal<string | null>(null);

  /**
   * GET /invite/{token} — public, no bearer token attached.
   *
   * Returns 410 Gone when the link is invalid/expired/exhausted; the caller
   * should display a friendly message rather than treating it as a fatal error.
   */
  getPublicEvent(token: string): Observable<PublicEventDto> {
    return this.run(
      this.http.get<PublicEventDto>(`${this.inviteUrl}/${encodeURIComponent(token)}`),
    );
  }

  /** POST /invite/{token}/rsvp — public; returns the guest's confirmation row. */
  submitRsvp(token: string, data: SubmitRsvpRequest): Observable<RsvpConfirmationDto> {
    return this.run(
      this.http.post<RsvpConfirmationDto>(
        `${this.inviteUrl}/${encodeURIComponent(token)}/rsvp`,
        data,
      ),
    );
  }

  /** GET /events/{eventId}/rsvps — paginated organizer view. */
  getRsvps(eventId: string, params: GetRsvpsParams): Observable<PagedResult<RsvpDto>> {
    let httpParams = new HttpParams()
      .set('page', params.page)
      .set('pageSize', params.pageSize);
    if (params.status !== undefined) {
      httpParams = httpParams.set('status', params.status);
    }
    return this.run(
      this.http.get<PagedResult<RsvpDto>>(
        `${this.eventsUrl}/${encodeURIComponent(eventId)}/rsvps`,
        { params: httpParams },
      ),
    ).pipe(tap((result) => this.rsvps.set(result)));
  }

  /** GET /events/{eventId}/rsvps/summary — aggregate counts. */
  getRsvpSummary(eventId: string): Observable<RsvpSummaryDto> {
    return this.run(
      this.http.get<RsvpSummaryDto>(
        `${this.eventsUrl}/${encodeURIComponent(eventId)}/rsvps/summary`,
      ),
    ).pipe(tap((result) => this.summary.set(result)));
  }

  /** Wraps an HTTP observable with shared `loading` / `error` signal updates. */
  private run<T>(source: Observable<T>): Observable<T> {
    this.loading.set(true);
    this.error.set(null);
    return new Observable<T>((subscriber) => {
      const sub = source.subscribe({
        next: (value) => subscriber.next(value),
        error: (err: unknown) => {
          this.loading.set(false);
          this.error.set(this.toMessage(err));
          subscriber.error(err);
        },
        complete: () => {
          this.loading.set(false);
          subscriber.complete();
        },
      });
      return () => sub.unsubscribe();
    });
  }

  /** Normalises an unknown error into a human-readable string. */
  private toMessage(err: unknown): string {
    if (typeof err === 'string') return err;
    if (err && typeof err === 'object') {
      const e = err as {
        error?: { detail?: string; title?: string; message?: string };
        message?: string;
      };
      return (
        e.error?.message ?? e.error?.detail ?? e.error?.title ?? e.message ?? 'Request failed.'
      );
    }
    return 'Request failed.';
  }
}
