// Generated by GitHub Copilot
namespace EventSync.Api.Common.Configuration;

/// <summary>
/// Strongly-typed binding for the <c>Frontend</c> configuration section.
/// </summary>
/// <remarks>
/// Bound at startup via <c>builder.Services.Configure&lt;FrontendOptions&gt;(...)</c>
/// and consumed through <c>IOptions&lt;FrontendOptions&gt;</c> wherever the API
/// needs to construct user-facing URLs (e.g., invite links).
/// </remarks>
public sealed class FrontendOptions
{
    /// <summary>Configuration section name.</summary>
    public const string SectionName = "Frontend";

    /// <summary>
    /// Public origin of the Angular client, e.g., <c>http://localhost:4200</c>.
    /// Must NOT contain a trailing slash; helpers normalise as needed.
    /// </summary>
    public string BaseUrl { get; set; } = string.Empty;
}
