// Generated by GitHub Copilot
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  inject,
  signal,
  viewChild,
} from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { filter, map } from 'rxjs';

import { AuthService } from '../../core/auth/auth.service';

/**
 * Top application header. Renders auth-aware navigation:
 * - Anonymous visitors see a "Sign in" link.
 * - Authenticated users see their avatar + display name with a dropdown menu
 *   containing "Sign out".
 *
 * Accessibility:
 * - The dropdown trigger uses `aria-haspopup="menu"` and `aria-expanded`.
 * - The menu uses `role="menu"` with `role="menuitem"` children.
 * - `Escape` closes the menu and returns focus to the trigger.
 * - Tab order is preserved (no positive tabindex used).
 */
@Component({
  selector: 'app-header',
  imports: [RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './header.html',
  styleUrl: './header.css',
  host: {
    '(document:click)': 'onDocumentClick($event)',
    '(document:keydown.escape)': 'closeMenu()',
  },
})
export class HeaderComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  /** True when the current route is the public RSVP page. */
  protected readonly isPublicPage = toSignal(
    this.router.events.pipe(
      filter((e): e is NavigationEnd => e instanceof NavigationEnd),
      map((e) => e.urlAfterRedirects.startsWith('/rsvp')),
    ),
    { initialValue: this.router.url.startsWith('/rsvp') },
  );

  /** Trigger button — used to restore focus when the menu closes. */
  private readonly menuButton = viewChild<ElementRef<HTMLButtonElement>>('menuButton');

  /** Menu open/closed state. */
  protected readonly isMenuOpen = signal(false);

  protected readonly isAuthenticated = this.auth.isAuthenticated;
  protected readonly isLoading = this.auth.isLoading;
  protected readonly displayName = this.auth.displayName;
  protected readonly avatarUrl = this.auth.avatarUrl;

  /** Trimmed initial used as a graceful fallback when no avatar URL is present. */
  protected readonly avatarInitial = computed(() => {
    const name = this.displayName();
    return name?.charAt(0)?.toUpperCase() ?? '?';
  });

  /** Toggle the dropdown. Focus stays on the button. */
  protected toggleMenu(): void {
    this.isMenuOpen.update((open) => !open);
  }

  /** Close the dropdown and restore focus to the trigger. */
  protected closeMenu(): void {
    if (!this.isMenuOpen()) {
      return;
    }
    this.isMenuOpen.set(false);
    this.menuButton()?.nativeElement.focus();
  }

  /** Click-outside handler: close the menu when clicking elsewhere. */
  protected onDocumentClick(event: MouseEvent): void {
    if (!this.isMenuOpen()) {
      return;
    }
    const target = event.target as Node | null;
    const button = this.menuButton()?.nativeElement;
    if (button && target && (button === target || button.contains(target))) {
      return;
    }
    this.isMenuOpen.set(false);
  }

  /** Sign-out menu action. */
  protected onSignOut(): void {
    this.isMenuOpen.set(false);
    this.auth.logout();
  }
}
