// Generated by GitHub Copilot
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.RSVPs.Common;

/// <summary>
/// Resolves and validates a public invite-link token in a single round-trip.
/// </summary>
/// <remarks>
/// Returning a tuple rather than throwing keeps the validation logic re-usable
/// across queries (where 410 is expected) and commands (where the same handler
/// may translate the failure differently). Callers throw
/// <see cref="EventSync.Api.Common.Exceptions.InvalidInviteException"/> when they
/// want to surface a "Gone" response.
/// </remarks>
public interface IInviteValidationService
{
    /// <summary>
    /// Looks up the invite link by token and reports the first reason it cannot be honoured.
    /// </summary>
    /// <param name="token">URL-safe random token.</param>
    /// <param name="forSubmission">
    /// When <c>true</c>, additionally rejects links whose underlying event has been
    /// cancelled. When <c>false</c> (the default, used by GET) cancelled events are
    /// returned so the public page can render a "cancelled" notice.
    /// </param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    /// A tuple of <c>(Link, ErrorMessage)</c>. <c>Link</c> is non-null only when validation
    /// succeeds; <c>ErrorMessage</c> is non-null only when validation fails.
    /// </returns>
    Task<(InviteLink? Link, string? ErrorMessage)> ValidateTokenAsync(
        string token,
        bool forSubmission = false,
        CancellationToken cancellationToken = default);
}

/// <inheritdoc cref="IInviteValidationService"/>
public sealed class InviteValidationService : IInviteValidationService
{
    private readonly AppDbContext _dbContext;

    /// <summary>Initializes a new instance of <see cref="InviteValidationService"/>.</summary>
    public InviteValidationService(AppDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    /// <inheritdoc/>
    public async Task<(InviteLink? Link, string? ErrorMessage)> ValidateTokenAsync(
        string token,
        bool forSubmission = false,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(token))
        {
            return (null, "Invite link not found");
        }

        // IgnoreQueryFilters so a soft-deleted Event still surfaces the link, allowing us
        // to return a precise "Event no longer available" message rather than the generic
        // "not found" (which would otherwise leak whether the token had ever existed).
        var link = await _dbContext.InviteLinks
            .IgnoreQueryFilters()
            .Include(l => l.Event)
                .ThenInclude(e => e.EventType)
            .Include(l => l.Event)
                .ThenInclude(e => e.Organizer)
            .AsNoTracking()
            .FirstOrDefaultAsync(l => l.Token == token, cancellationToken);

        if (link is null)
        {
            return (null, "Invite link not found");
        }

        if (!link.IsActive)
        {
            return (null, "This invite link has been deactivated");
        }

        if (link.ExpiresAt is DateTime expiry && expiry < DateTime.Now)
        {
            return (null, "This invite link has expired");
        }

        if (link.MaxUses is int max && link.UseCount >= max)
        {
            return (null, "This invite link has reached its limit");
        }

        if (link.Event.IsDeleted)
        {
            return (null, "Event no longer available");
        }

        // Cancelled events are still readable (so the public page can show a notice),
        // but new RSVP submissions are blocked.
        if (forSubmission && link.Event.IsCancelled)
        {
            return (null, "This event has been cancelled and is no longer accepting RSVPs");
        }

        return (link, null);
    }
}
