// Generated by GitHub Copilot
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.Events.Common;

namespace EventSync.Api.Features.RSVPs.Common;

/// <summary>
/// Public-facing event projection returned to anonymous invite-page visitors.
/// </summary>
/// <remarks>
/// Privacy: this DTO must NEVER include sensitive fields such as the organizer's
/// email, the internal event id, or any audit metadata. Adding fields here is a
/// security review item.
/// </remarks>
/// <param name="Title">Event title.</param>
/// <param name="Description">Optional long-form description.</param>
/// <param name="EventType">Event-type lookup row (icon + name only).</param>
/// <param name="Location">Optional physical location (null for virtual events).</param>
/// <param name="IsVirtual">Whether the event is online.</param>
/// <param name="StartDate">UTC start date and time.</param>
/// <param name="EndDate">Optional UTC end date and time.</param>
/// <param name="OrganizerName">Organizer display name. Email is intentionally excluded.</param>
/// <param name="CoverImageUrl">Optional cover image URL.</param>
/// <param name="IsCancelled">True when the organizer cancelled the event.</param>
public sealed record PublicEventDto(
    string Title,
    string? Description,
    EventTypeDto EventType,
    string? Location,
    bool IsVirtual,
    DateTime StartDate,
    DateTime? EndDate,
    string OrganizerName,
    string? CoverImageUrl,
    bool IsCancelled);

/// <summary>
/// Read-model for an RSVP row in the organizer-side list.
/// </summary>
/// <param name="Id">RSVP identifier.</param>
/// <param name="GuestName">Guest display name.</param>
/// <param name="GuestEmail">Optional contact email.</param>
/// <param name="Status">Going / NotGoing / Maybe / Pending.</param>
/// <param name="Note">Optional free-text note from the guest.</param>
/// <param name="RespondedAt">UTC timestamp the RSVP was first recorded.</param>
/// <param name="UpdatedAt">UTC timestamp of the most recent update.</param>
public sealed record RsvpDto(
    Guid Id,
    string GuestName,
    string? GuestEmail,
    RsvpStatus Status,
    string? Note,
    DateTime RespondedAt,
    DateTime? UpdatedAt);

/// <summary>
/// Confirmation payload returned to the guest after a successful RSVP submission.
/// </summary>
/// <param name="Id">RSVP identifier.</param>
/// <param name="GuestName">Echoed guest name.</param>
/// <param name="Status">Recorded status.</param>
/// <param name="EventTitle">Title of the event RSVP'd to.</param>
/// <param name="EventDate">UTC start date of the event.</param>
public sealed record RsvpConfirmationDto(
    Guid Id,
    string GuestName,
    RsvpStatus Status,
    string EventTitle,
    DateTime EventDate);
