// Generated by GitHub Copilot
using EventSync.Api.Common.Configuration;
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.Events.Common;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace EventSync.Api.Features.InviteLinks.CreateInviteLink;

/// <summary>
/// Command: create a new invite link for an event the current user organizes.
/// </summary>
/// <param name="EventId">Owning event identifier.</param>
/// <param name="ExpiresAt">Optional UTC expiration. Must be in the future when supplied.</param>
/// <param name="MaxUses">Optional usage cap. Must be &gt;= 1 when supplied.</param>
public sealed record CreateInviteLinkCommand(
    Guid EventId,
    DateTime? ExpiresAt,
    int? MaxUses) : IRequest<InviteLinkDto>;

/// <summary>FluentValidation rules for <see cref="CreateInviteLinkCommand"/>.</summary>
public sealed class CreateInviteLinkValidator : AbstractValidator<CreateInviteLinkCommand>
{
    /// <summary>Configures the validation rules.</summary>
    public CreateInviteLinkValidator()
    {
        RuleFor(x => x.EventId).NotEmpty();

        RuleFor(x => x.ExpiresAt)
            .GreaterThan(_ => DateTime.UtcNow)
                .WithMessage("ExpiresAt must be in the future.")
            .When(x => x.ExpiresAt.HasValue);

        RuleFor(x => x.MaxUses)
            .GreaterThanOrEqualTo(1)
                .WithMessage("MaxUses must be at least 1.")
            .When(x => x.MaxUses.HasValue);
    }
}

/// <summary>Handler for <see cref="CreateInviteLinkCommand"/>.</summary>
public sealed class CreateInviteLinkHandler : IRequestHandler<CreateInviteLinkCommand, InviteLinkDto>
{
    private readonly ICurrentUserService _currentUser;
    private readonly AppDbContext _dbContext;
    private readonly ITokenGenerator _tokenGenerator;
    private readonly FrontendOptions _frontend;

    /// <summary>Initializes a new instance of <see cref="CreateInviteLinkHandler"/>.</summary>
    public CreateInviteLinkHandler(
        ICurrentUserService currentUser,
        AppDbContext dbContext,
        ITokenGenerator tokenGenerator,
        IOptions<FrontendOptions> frontendOptions)
    {
        _currentUser = currentUser;
        _dbContext = dbContext;
        _tokenGenerator = tokenGenerator;
        _frontend = frontendOptions.Value;
    }

    /// <inheritdoc/>
    /// <exception cref="KeyNotFoundException">Event does not exist.</exception>
    /// <exception cref="UnauthorizedAccessException">Event is owned by another user.</exception>
    public async Task<InviteLinkDto> Handle(CreateInviteLinkCommand request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var ev = await _dbContext.Events
            .AsNoTracking()
            .FirstOrDefaultAsync(e => e.Id == request.EventId, cancellationToken)
            ?? throw new KeyNotFoundException($"Event {request.EventId} not found.");

        if (ev.OrganizerId != user.Id)
        {
            throw new UnauthorizedAccessException("You do not have permission to create invites for this event.");
        }

        var entity = new InviteLink
        {
            Id = Guid.NewGuid(),
            EventId = ev.Id,
            Token = _tokenGenerator.GenerateUrlSafeToken(),
            ExpiresAt = request.ExpiresAt.HasValue
                ? DateTime.SpecifyKind(request.ExpiresAt.Value, DateTimeKind.Utc)
                : null,
            MaxUses = request.MaxUses,
            UseCount = 0,
            IsActive = true,
            CreatedAt = DateTime.UtcNow,
        };

        _dbContext.InviteLinks.Add(entity);
        await _dbContext.SaveChangesAsync(cancellationToken);

        return ToDto(entity, _frontend.BaseUrl);
    }

    /// <summary>Maps an <see cref="InviteLink"/> entity to its public DTO with the full URL.</summary>
    public static InviteLinkDto ToDto(InviteLink entity, string baseUrl)
    {
        var trimmedBase = baseUrl.TrimEnd('/');
        return new InviteLinkDto(
            entity.Id,
            entity.Token,
            $"{trimmedBase}/rsvp/{entity.Token}",
            entity.ExpiresAt,
            entity.MaxUses,
            entity.UseCount,
            entity.IsActive,
            entity.CreatedAt);
    }
}
