// Generated by GitHub Copilot
import { Injectable } from '@angular/core';

/**
 * Cross-browser clipboard helper.
 *
 * Tries the asynchronous, user-permission-aware Clipboard API first; falls back
 * to the deprecated `document.execCommand('copy')` when the modern API is
 * unavailable (e.g. older Safari, insecure context, certain webviews).
 *
 * Security: copies user-supplied text only \u2014 never call this with sensitive
 * server-side state without an explicit user gesture.
 */
@Injectable({ providedIn: 'root' })
export class ClipboardService {
  /**
   * Copies the provided text to the system clipboard.
   *
   * @param text Text to copy. Empty strings are still attempted so callers can
   *   "clear" the clipboard if needed.
   * @returns Promise that resolves to `true` on success, `false` on any failure.
   */
  async copy(text: string): Promise<boolean> {
    if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
      try {
        await navigator.clipboard.writeText(text);
        return true;
      } catch (err) {
        console.warn('[Clipboard] navigator.clipboard.writeText failed; trying fallback.', err);
        // Fall through to the legacy path.
      }
    }

    return this.legacyCopy(text);
  }

  /**
   * Legacy fallback using a temporary textarea + `document.execCommand('copy')`.
   * Marked as deprecated by the spec but still widely supported.
   */
  private legacyCopy(text: string): boolean {
    if (typeof document === 'undefined') return false;
    const textarea = document.createElement('textarea');
    textarea.value = text;
    // Visually hide while keeping it focusable enough to copy from.
    textarea.setAttribute('readonly', '');
    textarea.style.position = 'fixed';
    textarea.style.top = '-1000px';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);

    try {
      textarea.select();
      textarea.setSelectionRange(0, text.length);
      // eslint-disable-next-line @typescript-eslint/no-deprecated
      return document.execCommand('copy');
    } catch (err) {
      console.warn('[Clipboard] Legacy copy failed.', err);
      return false;
    } finally {
      document.body.removeChild(textarea);
    }
  }
}
