// Generated by GitHub Copilot
import { Injectable, signal } from '@angular/core';

/** Visual + semantic kind of a toast message. */
export type ToastType = 'success' | 'error' | 'info';

/** Single toast entry rendered by `ToastContainerComponent`. */
export interface ToastMessage {
  readonly id: string;
  readonly type: ToastType;
  readonly message: string;
}

/**
 * Lightweight in-memory notification bus.
 *
 * Components consume the `toasts` signal to render the queue, and call
 * {@link success}, {@link error}, or {@link info} to enqueue a new entry.
 * Each toast auto-dismisses after {@link AUTO_DISMISS_MS} unless the user
 * dismisses it manually.
 *
 * Accessibility:
 * - The container exposes each toast with `aria-live="polite"` + `role="status"`
 *   so screen readers announce them without stealing focus.
 * - Errors deliberately use the same polite live region (not assertive) to
 *   avoid interrupting the user mid-task; raise the urgency only if a future
 *   UX requirement demands it.
 */
@Injectable({ providedIn: 'root' })
export class ToastService {
  /** Auto-dismiss delay in milliseconds. */
  static readonly AUTO_DISMISS_MS = 4000;

  /** Reactive queue of currently-visible toasts. */
  readonly toasts = signal<readonly ToastMessage[]>([]);

  /** Enqueue a success toast. */
  success(message: string): string {
    return this.push('success', message);
  }

  /** Enqueue an error toast. */
  error(message: string): string {
    return this.push('error', message);
  }

  /** Enqueue an informational toast. */
  info(message: string): string {
    return this.push('info', message);
  }

  /** Remove a toast by id (no-op if it has already been dismissed). */
  dismiss(id: string): void {
    this.toasts.update((current) => current.filter((t) => t.id !== id));
  }

  /** Internal push + auto-dismiss timer. */
  private push(type: ToastType, message: string): string {
    const id = this.nextId();
    const toast: ToastMessage = { id, type, message };
    this.toasts.update((current) => [...current, toast]);
    setTimeout(() => this.dismiss(id), ToastService.AUTO_DISMISS_MS);
    return id;
  }

  /** Generates a sufficiently-unique id without pulling in a uuid dependency. */
  private nextId(): string {
    if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
      return crypto.randomUUID();
    }
    return `toast-${Date.now()}-${Math.floor(Math.random() * 1_000_000)}`;
  }
}
