// Generated by GitHub Copilot
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Features.Events.Common;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.Events.UpdateEvent;

/// <summary>
/// Command: update mutable fields on an existing event owned by the current user.
/// </summary>
public sealed record UpdateEventCommand(
    Guid Id,
    string Title,
    string OrganizerName,
    string? Description,
    int EventTypeId,
    string? Location,
    bool IsVirtual,
    string? MeetingUrl,
    DateTime StartDate,
    DateTime? EndDate,
    int? MaxAttendees,
    string? CoverImageUrl) : IRequest<EventDto>;

/// <summary>
/// FluentValidation rules for <see cref="UpdateEventCommand"/>.
/// </summary>
/// <remarks>
/// Mirrors <c>CreateEventValidator</c> but does NOT enforce a future
/// <c>StartDate</c>: an event that has already started can still be edited
/// (e.g., to fix a typo or extend the end time). Toggle <see cref="EnforceFutureStart"/>
/// to <c>true</c> if your tenant prefers strict future-only updates.
/// </remarks>
public sealed class UpdateEventValidator : AbstractValidator<UpdateEventCommand>
{
    /// <summary>
    /// When <c>true</c>, <see cref="UpdateEventCommand.StartDate"/> must be in the
    /// future. Defaults to <c>false</c> per spec ("allow past start date if event
    /// already started").
    /// </summary>
    public static bool EnforceFutureStart { get; set; }

    /// <summary>Configures the validation rules.</summary>
    public UpdateEventValidator()
    {
        RuleFor(x => x.Id).NotEmpty();
        RuleFor(x => x.Title).NotEmpty().MaximumLength(200);
        RuleFor(x => x.OrganizerName).NotEmpty().MaximumLength(100);
        RuleFor(x => x.Description).MaximumLength(2000);
        RuleFor(x => x.EventTypeId).GreaterThan(0);
        RuleFor(x => x.Location).MaximumLength(300);

        RuleFor(x => x.MeetingUrl)
            .Must(BeAValidAbsoluteUrl)
                .WithMessage("MeetingUrl must be a valid absolute http(s) URL.")
            .MaximumLength(1024)
            .When(x => !string.IsNullOrWhiteSpace(x.MeetingUrl));

        // Conditional future-start enforcement.
        RuleFor(x => x.StartDate)
            .GreaterThan(_ => DateTime.Now)
                .WithMessage("StartDate must be in the future.")
            .When(_ => EnforceFutureStart);

        RuleFor(x => x.EndDate)
            .GreaterThan(x => x.StartDate)
                .WithMessage("EndDate must be after StartDate.")
            .When(x => x.EndDate.HasValue);

        RuleFor(x => x.MaxAttendees)
            .GreaterThanOrEqualTo(1)
            .When(x => x.MaxAttendees.HasValue);

        RuleFor(x => x.CoverImageUrl)
            .Must(BeAValidImageUrl)
                .WithMessage("CoverImageUrl must be a valid https URL or an /uploads/ path.")
            .MaximumLength(512)
            .When(x => !string.IsNullOrWhiteSpace(x.CoverImageUrl));
    }

    private static bool BeAValidAbsoluteUrl(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return true;
        }

        return Uri.TryCreate(value, UriKind.Absolute, out var uri)
            && (uri.Scheme == Uri.UriSchemeHttp || uri.Scheme == Uri.UriSchemeHttps);
    }

    /// <summary>
    /// Accepts either an absolute http(s) URL or a server-relative path beginning
    /// with <c>/uploads/</c> (returned by the upload endpoint).
    /// </summary>
    private static bool BeAValidImageUrl(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return true;
        }

        if (value.StartsWith("/uploads/", StringComparison.Ordinal))
        {
            return true;
        }

        return BeAValidAbsoluteUrl(value);
    }
}

/// <summary>Handler for <see cref="UpdateEventCommand"/>.</summary>
public sealed class UpdateEventHandler : IRequestHandler<UpdateEventCommand, EventDto>
{
    private readonly ICurrentUserService _currentUser;
    private readonly AppDbContext _dbContext;

    /// <summary>Initializes a new instance of <see cref="UpdateEventHandler"/>.</summary>
    public UpdateEventHandler(ICurrentUserService currentUser, AppDbContext dbContext)
    {
        _currentUser = currentUser;
        _dbContext = dbContext;
    }

    /// <inheritdoc/>
    /// <exception cref="KeyNotFoundException">Thrown when the event does not exist.</exception>
    /// <exception cref="UnauthorizedAccessException">Thrown when the event is owned by another user.</exception>
    public async Task<EventDto> Handle(UpdateEventCommand request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var entity = await _dbContext.Events
            .Include(e => e.EventType)
            .FirstOrDefaultAsync(e => e.Id == request.Id, cancellationToken)
            ?? throw new KeyNotFoundException($"Event {request.Id} not found.");

        if (entity.OrganizerId != user.Id)
        {
            throw new UnauthorizedAccessException("You do not have permission to modify this event.");
        }

        // If the event type is changing, verify the new lookup row exists.
        if (entity.EventTypeId != request.EventTypeId)
        {
            var typeExists = await _dbContext.EventTypes
                .AsNoTracking()
                .AnyAsync(t => t.Id == request.EventTypeId, cancellationToken);

            if (!typeExists)
            {
                throw new ValidationException(
                    [new FluentValidation.Results.ValidationFailure(
                        nameof(request.EventTypeId),
                        $"EventTypeId {request.EventTypeId} does not exist.")]);
            }

            entity.EventTypeId = request.EventTypeId;
            // Force EF to reload the navigation property in the response.
            entity.EventType = null!;
        }

        entity.Title = request.Title.Trim();
        entity.OrganizerName = request.OrganizerName.Trim();
        entity.Description = string.IsNullOrWhiteSpace(request.Description) ? null : request.Description.Trim();
        entity.Location = string.IsNullOrWhiteSpace(request.Location) ? null : request.Location.Trim();
        entity.IsVirtual = request.IsVirtual;
        entity.MeetingUrl = string.IsNullOrWhiteSpace(request.MeetingUrl) ? null : request.MeetingUrl.Trim();
        entity.StartDate = request.StartDate;
        entity.EndDate = request.EndDate;
        entity.MaxAttendees = request.MaxAttendees;
        entity.CoverImageUrl = string.IsNullOrWhiteSpace(request.CoverImageUrl) ? null : request.CoverImageUrl.Trim();
        entity.UpdatedAt = DateTime.Now;

        await _dbContext.SaveChangesAsync(cancellationToken);

        // Reload the EventType navigation if the FK changed.
        if (entity.EventType is null)
        {
            await _dbContext.Entry(entity).Reference(e => e.EventType).LoadAsync(cancellationToken);
        }

        return new EventDto(
            entity.Id,
            entity.Title,
            entity.OrganizerName,
            entity.Description,
            entity.Location,
            entity.IsVirtual,
            entity.MeetingUrl,
            entity.StartDate,
            entity.EndDate,
            entity.MaxAttendees,
            entity.IsCancelled,
            entity.CreatedAt,
            entity.UpdatedAt,
            new EventTypeDto(entity.EventType.Id, entity.EventType.Name, entity.EventType.Icon));
    }
}
