// Generated by GitHub Copilot
using System.Security.Claims;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Common.Services;

/// <summary>
/// Resolves the current authenticated user from the incoming HTTP request and
/// provides on-demand "first-time" provisioning into the local <c>Users</c> table.
/// </summary>
/// <remarks>
/// Security:
/// <list type="bullet">
///   <item>Claims are read from a validated JWT (set up in Program.cs); never trust client-supplied values.</item>
///   <item>Missing optional claims (email, name, picture) are tolerated — defaults are used so the
///         request still succeeds and the user can complete their profile via <c>PUT /auth/profile</c>.</item>
/// </list>
/// </remarks>
public interface ICurrentUserService
{
    /// <summary>Auth0 subject identifier (the <c>sub</c> claim). Null when unauthenticated.</summary>
    string? Auth0Id { get; }

    /// <summary>Email claim, if present.</summary>
    string? Email { get; }

    /// <summary>Display name from <c>name</c> or <c>nickname</c> claim.</summary>
    string? Name { get; }

    /// <summary>Picture URL claim, if present.</summary>
    string? Picture { get; }

    /// <summary>True when the request carries a validated bearer token with a <c>sub</c> claim.</summary>
    bool IsAuthenticated { get; }

    /// <summary>
    /// Returns the local <see cref="User"/> for the current Auth0 identity, creating one
    /// on first sign-in. Throws <see cref="UnauthorizedAccessException"/> when there is
    /// no authenticated principal.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task<User> GetOrCreateUserAsync(CancellationToken cancellationToken = default);
}

/// <inheritdoc cref="ICurrentUserService"/>
public sealed class CurrentUserService : ICurrentUserService
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly AppDbContext _dbContext;

    /// <summary>
    /// Initializes a new instance of <see cref="CurrentUserService"/>.
    /// </summary>
    /// <param name="httpContextAccessor">Provides the current HTTP context (and its <see cref="ClaimsPrincipal"/>).</param>
    /// <param name="dbContext">EF Core context used for user provisioning.</param>
    public CurrentUserService(IHttpContextAccessor httpContextAccessor, AppDbContext dbContext)
    {
        _httpContextAccessor = httpContextAccessor;
        _dbContext = dbContext;
    }

    private ClaimsPrincipal? Principal => _httpContextAccessor.HttpContext?.User;

    /// <inheritdoc/>
    public string? Auth0Id =>
        // After JWT mapping, "sub" is exposed as ClaimTypes.NameIdentifier.
        Principal?.FindFirstValue(ClaimTypes.NameIdentifier)
        ?? Principal?.FindFirstValue("sub");

    /// <inheritdoc/>
    public string? Email => Principal?.FindFirstValue(ClaimTypes.Email)
                            ?? Principal?.FindFirstValue("email");

    /// <inheritdoc/>
    public string? Name => Principal?.FindFirstValue("name")
                           ?? Principal?.FindFirstValue("nickname")
                           ?? Principal?.FindFirstValue(ClaimTypes.Name);

    /// <inheritdoc/>
    public string? Picture => Principal?.FindFirstValue("picture");

    /// <inheritdoc/>
    public bool IsAuthenticated => !string.IsNullOrWhiteSpace(Auth0Id);

    /// <inheritdoc/>
    public async Task<User> GetOrCreateUserAsync(CancellationToken cancellationToken = default)
    {
        var auth0Id = Auth0Id
            ?? throw new UnauthorizedAccessException("No authenticated user on the current request.");

        var user = await _dbContext.Users
            .FirstOrDefaultAsync(u => u.Auth0Id == auth0Id, cancellationToken);

        if (user is not null)
        {
            return user;
        }

        // First sign-in: provision a local row from the available claims.
        // Defaults guard against missing claims so the request can still complete.
        var now = DateTime.Now;
        user = new User
        {
            Id = Guid.NewGuid(),
            Auth0Id = auth0Id,
            Email = Email ?? string.Empty,
            DisplayName = !string.IsNullOrWhiteSpace(Name) ? Name! : (Email ?? "New User"),
            AvatarUrl = Picture,
            CreatedAt = now,
        };

        _dbContext.Users.Add(user);
        await _dbContext.SaveChangesAsync(cancellationToken);
        return user;
    }
}
