// Generated by GitHub Copilot
using System.Security.Cryptography;

namespace EventSync.Api.Common.Services;

/// <summary>
/// Generates cryptographically-strong, URL-safe random tokens.
/// </summary>
public interface ITokenGenerator
{
    /// <summary>
    /// Returns a URL-safe random string with at least <paramref name="byteLength"/>
    /// bytes of entropy.
    /// </summary>
    /// <param name="byteLength">
    /// Underlying entropy in bytes. The default of <c>32</c> yields a 256-bit secret
    /// rendered as ~43 URL-safe characters.
    /// </param>
    /// <returns>A URL-safe Base64 string (without padding).</returns>
    string GenerateUrlSafeToken(int byteLength = 32);
}

/// <inheritdoc cref="ITokenGenerator"/>
/// <remarks>
/// Security: relies exclusively on <see cref="RandomNumberGenerator"/> — never on
/// <see cref="Random"/> or <see cref="Guid"/>, which are not cryptographically
/// secure. The result is unguessable and safe to use as a bearer-style token.
/// </remarks>
public sealed class TokenGenerator : ITokenGenerator
{
    /// <inheritdoc/>
    public string GenerateUrlSafeToken(int byteLength = 32)
    {
        if (byteLength < 16)
        {
            throw new ArgumentOutOfRangeException(
                nameof(byteLength),
                "Token must use at least 16 bytes (128 bits) of entropy.");
        }

        var bytes = RandomNumberGenerator.GetBytes(byteLength);
        // Standard Base64 → URL-safe variant (RFC 4648 §5) without padding.
        return Convert.ToBase64String(bytes)
            .Replace('+', '-')
            .Replace('/', '_')
            .TrimEnd('=');
    }
}
