// Generated by GitHub Copilot
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.InviteLinks.DeactivateInviteLink;

/// <summary>
/// Command: disable an invite link so it can no longer accept RSVPs.
/// </summary>
/// <param name="LinkId">Invite link identifier.</param>
public sealed record DeactivateInviteLinkCommand(Guid LinkId) : IRequest<Unit>;

/// <summary>Handler for <see cref="DeactivateInviteLinkCommand"/>.</summary>
public sealed class DeactivateInviteLinkHandler : IRequestHandler<DeactivateInviteLinkCommand, Unit>
{
    private readonly ICurrentUserService _currentUser;
    private readonly AppDbContext _dbContext;

    /// <summary>Initializes a new instance of <see cref="DeactivateInviteLinkHandler"/>.</summary>
    public DeactivateInviteLinkHandler(ICurrentUserService currentUser, AppDbContext dbContext)
    {
        _currentUser = currentUser;
        _dbContext = dbContext;
    }

    /// <inheritdoc/>
    /// <exception cref="KeyNotFoundException">Link does not exist.</exception>
    /// <exception cref="UnauthorizedAccessException">Link belongs to an event owned by another user.</exception>
    public async Task<Unit> Handle(DeactivateInviteLinkCommand request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var link = await _dbContext.InviteLinks
            .Include(l => l.Event)
            .FirstOrDefaultAsync(l => l.Id == request.LinkId, cancellationToken)
            ?? throw new KeyNotFoundException($"Invite link {request.LinkId} not found.");

        if (link.Event.OrganizerId != user.Id)
        {
            throw new UnauthorizedAccessException("You do not have permission to modify this invite link.");
        }

        if (link.IsActive)
        {
            link.IsActive = false;
            await _dbContext.SaveChangesAsync(cancellationToken);
        }

        return Unit.Value;
    }
}
