// Generated by GitHub Copilot
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.Events.CancelEvent;

/// <summary>
/// Command: mark an event owned by the current user as cancelled (without deleting it).
/// </summary>
/// <param name="Id">Event identifier.</param>
public sealed record CancelEventCommand(Guid Id) : IRequest<Unit>;

/// <summary>Handler for <see cref="CancelEventCommand"/>.</summary>
public sealed class CancelEventHandler : IRequestHandler<CancelEventCommand, Unit>
{
    private readonly ICurrentUserService _currentUser;
    private readonly AppDbContext _dbContext;

    /// <summary>Initializes a new instance of <see cref="CancelEventHandler"/>.</summary>
    public CancelEventHandler(ICurrentUserService currentUser, AppDbContext dbContext)
    {
        _currentUser = currentUser;
        _dbContext = dbContext;
    }

    /// <inheritdoc/>
    /// <exception cref="KeyNotFoundException">Thrown when the event does not exist.</exception>
    /// <exception cref="UnauthorizedAccessException">Thrown when the event is owned by another user.</exception>
    public async Task<Unit> Handle(CancelEventCommand request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var entity = await _dbContext.Events
            .FirstOrDefaultAsync(e => e.Id == request.Id, cancellationToken)
            ?? throw new KeyNotFoundException($"Event {request.Id} not found.");

        if (entity.OrganizerId != user.Id)
        {
            throw new UnauthorizedAccessException("You do not have permission to cancel this event.");
        }

        entity.IsCancelled = true;
        entity.UpdatedAt = DateTime.Now;

        await _dbContext.SaveChangesAsync(cancellationToken);
        return Unit.Value;
    }
}
