// Generated by GitHub Copilot
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  signal,
} from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';

import { EventService } from '../../../core/api/event.service';
import { environment } from '../../../../environments/environment';
import type { UpdateEventRequest } from '../../../core/models/event.model';
import {
  dateAfter,
  urlFormat,
} from '../../../shared/validators/custom-validators';

/**
 * Edits an existing event. The id is bound from the route via `withComponentInputBinding`
 * and `input.required<string>()` so route changes re-resolve naturally.
 *
 * Validation mirrors the create form **except** that StartDate is NOT forced to
 * be in the future — once an event has started, the organizer can still fix
 * typos or extend the end time.
 */
@Component({
  selector: 'app-edit-event',
  imports: [ReactiveFormsModule, RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './edit-event.component.html',
})
export class EditEventComponent {
  private readonly fb = inject(FormBuilder);
  private readonly eventService = inject(EventService);
  private readonly router = inject(Router);

  /** Route parameter — bound by `withComponentInputBinding`. */
  readonly id = input.required<string>();

  protected readonly eventTypes = this.eventService.eventTypes;
  protected readonly loading = signal(true);
  protected readonly submitting = signal(false);
  protected readonly loadError = signal<string | null>(null);
  protected readonly submitError = signal<string | null>(null);
  protected readonly originalTitle = signal<string>('');
  protected readonly uploading = signal(false);
  protected readonly uploadError = signal<string | null>(null);
  protected readonly coverImageUrl = signal<string | null>(null);
  protected readonly coverPreview = signal<string | null>(null);

  protected readonly form = this.fb.nonNullable.group({
    title: ['', [Validators.required, Validators.maxLength(200)]],
    description: ['', [Validators.maxLength(2000)]],
    eventTypeId: this.fb.control<number | null>(null, [Validators.required]),
    location: ['', [Validators.maxLength(300)]],
    isVirtual: [false],
    meetingUrl: ['', [urlFormat()]],
    startDate: ['', [Validators.required]],
    endDate: ['', [dateAfter('startDate')]],
    maxAttendees: this.fb.control<number | null>(null, [Validators.min(1)]),
  });

  private readonly isVirtual = toSignal(this.form.controls.isVirtual.valueChanges, {
    initialValue: false,
  });

  protected readonly showMeetingUrl = computed(() => this.isVirtual() === true);

  // eslint-disable-next-line @typescript-eslint/no-unused-private-class-members
  private readonly toggleMeetingUrlValidators = effect(() => {
    const required = this.showMeetingUrl();
    const ctrl = this.form.controls.meetingUrl;
    ctrl.setValidators(
      required ? [Validators.required, urlFormat()] : [urlFormat()],
    );
    ctrl.updateValueAndValidity({ emitEvent: false });
  });

  // eslint-disable-next-line @typescript-eslint/no-unused-private-class-members
  private readonly loadEvent = effect(() => {
    const id = this.id();
    if (!id) return;
    this.loading.set(true);
    this.loadError.set(null);
    this.eventService.getEvent(id).subscribe({
      next: (ev) => {
        this.originalTitle.set(ev.title);
        this.form.reset({
          title: ev.title,
          description: ev.description ?? '',
          eventTypeId: ev.eventType.id,
          location: ev.location ?? '',
          isVirtual: ev.isVirtual,
          meetingUrl: ev.meetingUrl ?? '',
          startDate: this.toLocalInput(ev.startDate),
          endDate: ev.endDate ? this.toLocalInput(ev.endDate) : '',
          maxAttendees: ev.maxAttendees,
        });
        // Restore cover image state from server.
        if (ev.coverImageUrl) {
          this.coverImageUrl.set(ev.coverImageUrl);
          this.coverPreview.set(this.resolveImageUrl(ev.coverImageUrl));
        }
        this.loading.set(false);
      },
      error: () => {
        this.loading.set(false);
        this.loadError.set(
          this.eventService.error() ?? 'Could not load event.',
        );
      },
    });
  });

  constructor() {
    if (this.eventTypes().length === 0) {
      this.eventService.getEventTypes().subscribe({ error: () => undefined });
    }
  }

  protected onSubmit(): void {
    if (this.form.invalid || this.submitting()) {
      this.form.markAllAsTouched();
      return;
    }
    const v = this.form.getRawValue();
    const payload: UpdateEventRequest = {
      title: v.title.trim(),
      description: v.description.trim() || null,
      eventTypeId: Number(v.eventTypeId),
      location: v.location.trim() || null,
      isVirtual: v.isVirtual,
      meetingUrl: v.isVirtual ? v.meetingUrl.trim() || null : null,
      startDate: new Date(v.startDate).toISOString(),
      endDate: v.endDate ? new Date(v.endDate).toISOString() : null,
      maxAttendees: v.maxAttendees ?? null,
      coverImageUrl: this.coverImageUrl(),
    };

    this.submitting.set(true);
    this.submitError.set(null);
    this.eventService.updateEvent(this.id(), payload).subscribe({
      next: (updated) => {
        this.submitting.set(false);
        this.router.navigate(['/events', updated.id]);
      },
      error: () => {
        this.submitting.set(false);
        this.submitError.set(
          this.eventService.error() ?? 'Could not save changes. Please try again.',
        );
      },
    });
  }

  /** Resolves a possibly-relative image path to a full URL. */
  private resolveImageUrl(url: string): string {
    if (url.startsWith('http://') || url.startsWith('https://')) return url;
    const apiOrigin = environment.apiUrl.replace(/\/api\/v1$/, '');
    return `${apiOrigin}${url}`;
  }

  /**
   * Converts an ISO/UTC string into the `YYYY-MM-DDTHH:mm` shape the
   * `<input type="datetime-local">` element expects, in the user's local zone.
   */
  private toLocalInput(iso: string): string {
    const d = new Date(iso);
    const pad = (n: number) => `${n}`.padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }

  /** Handles cover image file selection. Uploads immediately and stores the returned URL. */
  protected onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;
    this.uploadFile(file);
  }

  /** Handles drag-and-drop onto the cover image zone. */
  protected onDrop(event: DragEvent): void {
    const file = event.dataTransfer?.files?.[0];
    if (!file) return;
    this.uploadFile(file);
  }

  private uploadFile(file: File): void {
    const allowed = ['image/jpeg', 'image/png', 'image/webp'];
    if (!allowed.includes(file.type)) {
      this.uploadError.set('Only JPEG, PNG, and WebP images are allowed.');
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      this.uploadError.set('Image must be under 5 MB.');
      return;
    }

    this.coverPreview.set(URL.createObjectURL(file));
    this.uploading.set(true);
    this.uploadError.set(null);

    this.eventService.uploadImage(file).subscribe({
      next: (res) => {
        this.coverImageUrl.set(res.url);
        this.uploading.set(false);
      },
      error: () => {
        this.uploading.set(false);
        this.uploadError.set(this.eventService.error() ?? 'Upload failed.');
        this.coverPreview.set(null);
      },
    });
  }

  /** Removes the cover image. */
  protected removeCover(): void {
    this.coverImageUrl.set(null);
    this.coverPreview.set(null);
    this.uploadError.set(null);
  }
}
