// Generated by GitHub Copilot
/** Production environment configuration. Same shape as environment.ts. */
export const environment = {
  production: true,
  apiUrl: '/api/v1',
  auth0: {
    domain: 'dev-nqo6u1us6l2sh6km.us.auth0.com',
    clientId: 'crFbObfbMi1KMNkUFYIlchE7snX7QvZe',
    authorizationParams: {
      redirect_uri: window.location.origin + '/auth/callback',
      audience: 'https://eventsync-api',
    },
  },
} as const;
