// Generated by GitHub Copilot
/** Production environment configuration. Same shape as environment.ts. */
export const environment = {
  production: true,
  apiUrl: '/api/v1',
  auth0: {
    domain: 'dev-nqo6u1us6l2sh6km.us.auth0.com',
    clientId: 'crFbObfbMi1KMNkUFYIlchE7snX7QvZe',
    /**
     * Persist tokens in localStorage so the session survives a full page refresh.
     *
     * Trade-off: localStorage is readable by any script on the same origin —
     * keep CSP strict, never load third-party scripts that aren't audited, and
     * sanitise all rendered HTML to prevent XSS from exfiltrating tokens.
     */
    cacheLocation: 'localstorage' as const,
    /**
     * Use refresh tokens (with rotation) to silently renew expired access tokens
     * without forcing the user back through Universal Login.
     */
    useRefreshTokens: true,
    authorizationParams: {
      redirect_uri: window.location.origin + '/auth/callback',
      audience: 'https://eventsync-api',
    },
  },
} as const;
