// Generated by GitHub Copilot
using EventSync.Api.Data;
using EventSync.Api.Features.Events.Common;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.EventTypes.GetEventTypes;

/// <summary>
/// Query: list all available event types ordered by name.
/// </summary>
public sealed record GetEventTypesQuery() : IRequest<IReadOnlyList<EventTypeDto>>;

/// <summary>Handler for <see cref="GetEventTypesQuery"/>.</summary>
public sealed class GetEventTypesHandler : IRequestHandler<GetEventTypesQuery, IReadOnlyList<EventTypeDto>>
{
    private readonly AppDbContext _dbContext;

    /// <summary>Initializes a new instance of <see cref="GetEventTypesHandler"/>.</summary>
    public GetEventTypesHandler(AppDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    /// <inheritdoc/>
    public async Task<IReadOnlyList<EventTypeDto>> Handle(
        GetEventTypesQuery request,
        CancellationToken cancellationToken)
    {
        return await _dbContext.EventTypes
            .AsNoTracking()
            .OrderBy(t => t.Name)
            .Select(t => new EventTypeDto(t.Id, t.Name, t.Icon))
            .ToListAsync(cancellationToken);
    }
}
