// Generated by GitHub Copilot
using System.Diagnostics;
using System.Text.Json;
using EventSync.Api.Common.Exceptions;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;

namespace EventSync.Api.Common.Middleware;

/// <summary>
/// Catches unhandled exceptions raised by downstream middleware/endpoints and
/// translates them into RFC 7807 <see cref="ProblemDetails"/> responses.
/// </summary>
/// <remarks>
/// Security: in non-Development environments the middleware never includes
/// stack traces, inner exceptions, or any other server-side detail in the
/// payload — all callers see is the generic <c>"An unexpected error occurred"</c>
/// message plus the trace identifier (which they can quote when contacting support).
/// </remarks>
public sealed class ExceptionHandlingMiddleware
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    private readonly RequestDelegate _next;
    private readonly ILogger<ExceptionHandlingMiddleware> _logger;
    private readonly IHostEnvironment _environment;

    /// <summary>Initializes a new instance of <see cref="ExceptionHandlingMiddleware"/>.</summary>
    public ExceptionHandlingMiddleware(
        RequestDelegate next,
        ILogger<ExceptionHandlingMiddleware> logger,
        IHostEnvironment environment)
    {
        _next = next;
        _logger = logger;
        _environment = environment;
    }

    /// <summary>Processes the HTTP request, catching and translating any unhandled exception.</summary>
    public async Task InvokeAsync(HttpContext context)
    {
        try
        {
            await _next(context);
        }
        catch (Exception ex)
        {
            await HandleExceptionAsync(context, ex);
        }
    }

    private async Task HandleExceptionAsync(HttpContext context, Exception exception)
    {
        var traceId = Activity.Current?.Id ?? context.TraceIdentifier;

        var (status, title, detail) = exception switch
        {
            ValidationException => (
                StatusCodes.Status400BadRequest,
                "Validation failed",
                "One or more validation errors occurred."),
            ForbiddenAccessException fax => (
                StatusCodes.Status403Forbidden,
                "Forbidden",
                fax.Message),
            UnauthorizedAccessException => (
                StatusCodes.Status403Forbidden,
                "Forbidden",
                "You do not have permission to perform this action."),
            NotFoundException nfe => (
                StatusCodes.Status404NotFound,
                "Resource not found",
                nfe.Message),
            KeyNotFoundException knf => (
                StatusCodes.Status404NotFound,
                "Resource not found",
                knf.Message),
            InvalidInviteException iie => (
                StatusCodes.Status410Gone,
                "Invite link unavailable",
                iie.Message),
            _ => (
                StatusCodes.Status500InternalServerError,
                "Server error",
                "An unexpected error occurred."),
        };

        // Always log the full exception server-side. Use structured logging — never
        // string-interpolate user-supplied data into the message template.
        if (status >= 500)
        {
            _logger.LogError(
                exception,
                "Unhandled exception while processing {Method} {Path}. TraceId={TraceId}",
                context.Request.Method,
                context.Request.Path,
                traceId);
        }
        else
        {
            _logger.LogWarning(
                exception,
                "Handled {ExceptionType} ({Status}) while processing {Method} {Path}. TraceId={TraceId}",
                exception.GetType().Name,
                status,
                context.Request.Method,
                context.Request.Path,
                traceId);
        }

        if (context.Response.HasStarted)
        {
            // Headers/body already flushed — nothing safe to write.
            _logger.LogWarning("Response already started; cannot write ProblemDetails. TraceId={TraceId}", traceId);
            return;
        }

        var problem = new ProblemDetails
        {
            Type = $"https://httpstatuses.io/{status}",
            Title = title,
            Status = status,
            Detail = detail,
            Instance = context.Request.Path,
        };
        problem.Extensions["traceId"] = traceId;

        // Validation errors: surface the property → messages map for client UX.
        if (exception is ValidationException validation)
        {
            var errors = validation.Errors
                .GroupBy(e => e.PropertyName)
                .ToDictionary(
                    g => string.IsNullOrWhiteSpace(g.Key) ? "_" : g.Key,
                    g => g.Select(e => e.ErrorMessage).ToArray());
            problem.Extensions["errors"] = errors;
        }

        // Development-only diagnostics. NEVER include in non-Development environments.
        if (_environment.IsDevelopment())
        {
            problem.Extensions["exception"] = exception.GetType().FullName;
            problem.Extensions["stackTrace"] = exception.StackTrace;
            if (exception.InnerException is not null)
            {
                problem.Extensions["innerException"] = new
                {
                    type = exception.InnerException.GetType().FullName,
                    message = exception.InnerException.Message,
                };
            }
        }

        context.Response.Clear();
        context.Response.StatusCode = status;
        context.Response.ContentType = "application/problem+json";
        await JsonSerializer.SerializeAsync(context.Response.Body, problem, JsonOptions);
    }
}

/// <summary>Extension helpers for registering <see cref="ExceptionHandlingMiddleware"/>.</summary>
public static class ExceptionHandlingMiddlewareExtensions
{
    /// <summary>Adds the global exception handler to the request pipeline.</summary>
    public static IApplicationBuilder UseExceptionHandling(this IApplicationBuilder app)
        => app.UseMiddleware<ExceptionHandlingMiddleware>();
}
