// Generated by GitHub Copilot
using Microsoft.Extensions.Options;

namespace EventSync.Api.Common.Middleware;

/// <summary>
/// Strongly-typed options for <see cref="SecurityHeadersMiddleware"/>.
/// Bound from configuration section <c>"SecurityHeaders"</c> when present;
/// reasonable defaults apply otherwise.
/// </summary>
public sealed class SecurityHeadersOptions
{
    /// <summary>Configuration section name.</summary>
    public const string SectionName = "SecurityHeaders";

    /// <summary>Auth0 tenant domain — appended to <c>connect-src</c> in the CSP.</summary>
    public string? Auth0Domain { get; set; }

    /// <summary>Optional explicit override for the CSP <c>connect-src</c> list.</summary>
    public string[]? AdditionalConnectSources { get; set; }
}

/// <summary>
/// Adds a baseline of HTTP security response headers in line with the Accenture
/// HTTP Security Headers Standard.
/// </summary>
/// <remarks>
/// HSTS is only emitted outside Development to avoid pinning developer browsers
/// to HTTPS for <c>localhost</c>. The CSP is intentionally strict
/// (<c>script-src 'self'</c>, no inline JS) — the Angular build serves bundled
/// JS files so no <c>'unsafe-inline'</c> is required for scripts.
/// </remarks>
public sealed class SecurityHeadersMiddleware
{
    private readonly RequestDelegate _next;
    private readonly IHostEnvironment _environment;
    private readonly string _csp;

    /// <summary>Initializes a new instance of <see cref="SecurityHeadersMiddleware"/>.</summary>
    public SecurityHeadersMiddleware(
        RequestDelegate next,
        IHostEnvironment environment,
        IOptions<SecurityHeadersOptions> options)
    {
        _next = next;
        _environment = environment;
        _csp = BuildContentSecurityPolicy(options.Value);
    }

    /// <summary>Processes the HTTP request, attaching security headers to the response.</summary>
    public Task InvokeAsync(HttpContext context)
    {
        // Headers must be set before the response starts streaming.
        context.Response.OnStarting(() =>
        {
            var headers = context.Response.Headers;

            // Disclose less about the server stack.
            headers.Remove("Server");
            headers.Remove("X-Powered-By");

            headers["X-Content-Type-Options"] = "nosniff";
            headers["X-Frame-Options"] = "DENY";
            headers["Referrer-Policy"] = "strict-origin-when-cross-origin";
            headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()";
            headers["Content-Security-Policy"] = _csp;

            if (!_environment.IsDevelopment())
            {
                // 1 year, include subdomains. Only safe outside Development because
                // the dev host runs HTTP on localhost.
                headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains";
            }

            return Task.CompletedTask;
        });

        return _next(context);
    }

    private static string BuildContentSecurityPolicy(SecurityHeadersOptions options)
    {
        var connectSources = new List<string> { "'self'" };

        if (!string.IsNullOrWhiteSpace(options.Auth0Domain))
        {
            connectSources.Add($"https://{options.Auth0Domain}");
        }

        if (options.AdditionalConnectSources is { Length: > 0 } additional)
        {
            connectSources.AddRange(additional.Where(s => !string.IsNullOrWhiteSpace(s)));
        }

        var connectSrc = string.Join(' ', connectSources);

        return string.Join("; ", new[]
        {
            "default-src 'self'",
            "script-src 'self'",
            "style-src 'self' 'unsafe-inline'",
            "img-src 'self' data: https:",
            $"connect-src {connectSrc}",
            "frame-ancestors 'none'",
            "base-uri 'self'",
            "form-action 'self'",
            "object-src 'none'",
        });
    }
}

/// <summary>Extension helpers for registering <see cref="SecurityHeadersMiddleware"/>.</summary>
public static class SecurityHeadersMiddlewareExtensions
{
    /// <summary>Adds the security-headers middleware to the request pipeline.</summary>
    public static IApplicationBuilder UseSecurityHeaders(this IApplicationBuilder app)
        => app.UseMiddleware<SecurityHeadersMiddleware>();
}
