// Generated by GitHub Copilot
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.Events.DeleteEvent;

/// <summary>
/// Command: soft-delete an event owned by the current user.
/// </summary>
/// <param name="Id">Event identifier.</param>
public sealed record DeleteEventCommand(Guid Id) : IRequest<Unit>;

/// <summary>Handler for <see cref="DeleteEventCommand"/>.</summary>
public sealed class DeleteEventHandler : IRequestHandler<DeleteEventCommand, Unit>
{
    private readonly ICurrentUserService _currentUser;
    private readonly AppDbContext _dbContext;

    /// <summary>Initializes a new instance of <see cref="DeleteEventHandler"/>.</summary>
    public DeleteEventHandler(ICurrentUserService currentUser, AppDbContext dbContext)
    {
        _currentUser = currentUser;
        _dbContext = dbContext;
    }

    /// <inheritdoc/>
    /// <exception cref="KeyNotFoundException">Thrown when the event does not exist.</exception>
    /// <exception cref="UnauthorizedAccessException">Thrown when the event is owned by another user.</exception>
    public async Task<Unit> Handle(DeleteEventCommand request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var entity = await _dbContext.Events
            .FirstOrDefaultAsync(e => e.Id == request.Id, cancellationToken)
            ?? throw new KeyNotFoundException($"Event {request.Id} not found.");

        if (entity.OrganizerId != user.Id)
        {
            throw new UnauthorizedAccessException("You do not have permission to delete this event.");
        }

        // Soft-delete: preserves audit history and cascades naturally via the
        // global query filter on dependent reads.
        entity.IsDeleted = true;
        entity.UpdatedAt = DateTime.UtcNow;

        await _dbContext.SaveChangesAsync(cancellationToken);
        return Unit.Value;
    }
}
