// Generated by GitHub Copilot
namespace EventSync.Api.Features.Uploads;

/// <summary>
/// Maps the image-upload minimal-API endpoint onto the application route table.
/// Uploaded files are persisted to <c>wwwroot/uploads/events/</c> and served as
/// static files. Only authenticated users may upload.
///
/// Security:
/// - 5 MB hard limit via <c>RequestSizeLimit</c>.
/// - Whitelist of raster MIME types (<c>image/jpeg</c>, <c>image/png</c>, <c>image/webp</c>).
/// - Magic-byte validation prevents Content-Type spoofing.
/// - GUID-based file names — user-supplied filename is never used on disk.
/// - Files served with <c>X-Content-Type-Options: nosniff</c> (default Kestrel behaviour).
/// - SVG is explicitly excluded to prevent stored-XSS.
/// </summary>
public static class UploadEndpoints
{
    private const long MaxFileSize = 5 * 1024 * 1024; // 5 MB

    private static readonly Dictionary<string, byte[][]> AllowedSignatures = new()
    {
        ["image/jpeg"] = [new byte[] { 0xFF, 0xD8, 0xFF }],
        ["image/png"] = [new byte[] { 0x89, 0x50, 0x4E, 0x47 }],
        ["image/webp"] = [new byte[] { 0x52, 0x49, 0x46, 0x46 }], // "RIFF"
    };

    private static readonly Dictionary<string, string> MimeToExtension = new()
    {
        ["image/jpeg"] = ".jpg",
        ["image/png"] = ".png",
        ["image/webp"] = ".webp",
    };

    /// <summary>
    /// Registers <c>POST /api/v1/uploads/images</c>.
    /// </summary>
    public static IEndpointRouteBuilder MapUploadEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/v1/uploads")
            .WithTags("Uploads")
            .RequireAuthorization();

        group.MapPost("/images", async (IFormFile file, IWebHostEnvironment env) =>
        {
            // --- Size check ---
            if (file.Length == 0)
            {
                return Results.BadRequest(new { error = "File is empty." });
            }

            if (file.Length > MaxFileSize)
            {
                return Results.BadRequest(new { error = $"File exceeds the {MaxFileSize / (1024 * 1024)} MB limit." });
            }

            // --- MIME type whitelist ---
            var contentType = file.ContentType.ToLowerInvariant();
            if (!AllowedSignatures.ContainsKey(contentType))
            {
                return Results.BadRequest(new { error = "Only JPEG, PNG, and WebP images are allowed." });
            }

            // --- Magic-byte verification ---
            using var stream = file.OpenReadStream();
            var headerBytes = new byte[12]; // longest signature we check is 4 bytes, but read 12 for RIFF+WEBP
            var bytesRead = await stream.ReadAsync(headerBytes.AsMemory(0, headerBytes.Length));
            if (bytesRead < 3)
            {
                return Results.BadRequest(new { error = "File is too small to be a valid image." });
            }

            var signaturesForType = AllowedSignatures[contentType];
            var magicMatch = false;
            foreach (var sig in signaturesForType)
            {
                if (bytesRead >= sig.Length && headerBytes.AsSpan(0, sig.Length).SequenceEqual(sig))
                {
                    // Extra check for WebP: bytes 8-11 must be "WEBP"
                    if (contentType == "image/webp")
                    {
                        if (bytesRead >= 12 &&
                            headerBytes[8] == 0x57 && // W
                            headerBytes[9] == 0x45 && // E
                            headerBytes[10] == 0x42 && // B
                            headerBytes[11] == 0x50)   // P
                        {
                            magicMatch = true;
                        }
                    }
                    else
                    {
                        magicMatch = true;
                    }
                }
            }

            if (!magicMatch)
            {
                return Results.BadRequest(new { error = "File content does not match its declared type." });
            }

            // --- Save to disk ---
            var extension = MimeToExtension[contentType];
            var fileName = $"{Guid.NewGuid()}{extension}";
            var uploadsDir = Path.Combine(env.WebRootPath ?? Path.Combine(env.ContentRootPath, "wwwroot"), "uploads", "events");
            Directory.CreateDirectory(uploadsDir);

            var filePath = Path.Combine(uploadsDir, fileName);
            stream.Position = 0;
            using (var fileStream = new FileStream(filePath, FileMode.Create, FileAccess.Write, FileShare.None))
            {
                await stream.CopyToAsync(fileStream);
            }

            var url = $"/uploads/events/{fileName}";
            return Results.Ok(new { url });
        })
        .WithName("UploadImage")
        .WithSummary("Upload a cover image (JPEG, PNG, or WebP, max 5 MB). Returns the relative URL.")
        .DisableAntiforgery()
        .Accepts<IFormFile>("multipart/form-data")
        .Produces(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status400BadRequest)
        .Produces(StatusCodes.Status401Unauthorized);

        return app;
    }
}
