// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';

/**
 * Accessible pagination control.
 *
 * - Renders Previous, condensed page numbers (with ellipsis), and Next.
 * - The current page button has `aria-current="page"` and is non-interactive.
 * - The container uses `aria-label="Pagination"` per WAI-ARIA APG guidance.
 */
@Component({
  selector: 'app-pagination',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './pagination.component.html',
})
export class PaginationComponent {
  readonly currentPage = input.required<number>();
  readonly totalPages = input.required<number>();
  readonly pageSize = input<number | undefined>(undefined);
  readonly pageChange = output<number>();

  /**
   * Compact list of pages with `'…'` placeholders.
   * Always shows the first, last, current, and one neighbour either side.
   */
  protected readonly pages = computed<readonly (number | '…')[]>(() => {
    const total = this.totalPages();
    const current = this.currentPage();
    if (total <= 1) return total === 1 ? [1] : [];

    const set = new Set<number>([1, total, current, current - 1, current + 1]);
    const sorted = [...set].filter((n) => n >= 1 && n <= total).sort((a, b) => a - b);

    const out: (number | '…')[] = [];
    let prev = 0;
    for (const page of sorted) {
      if (prev && page - prev > 1) out.push('…');
      out.push(page);
      prev = page;
    }
    return out;
  });

  protected readonly canGoPrev = computed(() => this.currentPage() > 1);
  protected readonly canGoNext = computed(() => this.currentPage() < this.totalPages());

  protected goTo(page: number): void {
    if (page < 1 || page > this.totalPages() || page === this.currentPage()) return;
    this.pageChange.emit(page);
  }

  protected isNumber(value: number | '…'): value is number {
    return typeof value === 'number';
  }
}
