// Generated by GitHub Copilot
using EventSync.Api.Features.Auth.GetProfile;
using EventSync.Api.Features.Auth.UpdateProfile;
using FluentValidation;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace EventSync.Api.Features.Auth;

/// <summary>
/// Maps Auth-feature minimal-API endpoints onto the application route table.
/// </summary>
public static class AuthEndpoints
{
    /// <summary>
    /// Registers <c>/api/v1/auth/*</c> endpoints. All routes require a valid bearer token.
    /// </summary>
    /// <param name="app">The application route builder.</param>
    /// <returns>The supplied <paramref name="app"/> for chaining.</returns>
    public static IEndpointRouteBuilder MapAuthEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/v1/auth")
            .WithTags("Auth")
            .RequireAuthorization();

        group.MapGet("/profile", async (IMediator mediator, CancellationToken ct) =>
        {
            var profile = await mediator.Send(new GetProfileQuery(), ct);
            return Results.Ok(profile);
        })
        .WithName("GetProfile")
        .WithSummary("Get the current user's profile (provisions on first call).")
        .Produces<UserProfileDto>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status401Unauthorized);

        group.MapPut("/profile", async (
            [FromBody] UpdateProfileCommand command,
            IMediator mediator,
            CancellationToken ct) =>
        {
            try
            {
                var updated = await mediator.Send(command, ct);
                return Results.Ok(updated);
            }
            catch (ValidationException ex)
            {
                // Phase 5 will replace this with a global problem-details handler.
                var errors = ex.Errors
                    .GroupBy(e => e.PropertyName)
                    .ToDictionary(g => g.Key, g => g.Select(e => e.ErrorMessage).ToArray());
                return Results.ValidationProblem(errors);
            }
        })
        .WithName("UpdateProfile")
        .WithSummary("Update the current user's display name and avatar URL.")
        .Produces<UserProfileDto>(StatusCodes.Status200OK)
        .ProducesValidationProblem()
        .Produces(StatusCodes.Status401Unauthorized);

        return app;
    }
}
