// Generated by GitHub Copilot
namespace EventSync.Api.Features.Auth;

/// <summary>
/// Public-facing representation of an authenticated user's profile.
/// </summary>
/// <param name="Id">Local user primary key.</param>
/// <param name="Email">Email address.</param>
/// <param name="DisplayName">Display name shown to other users.</param>
/// <param name="AvatarUrl">Optional avatar image URL.</param>
public record UserProfileDto(Guid Id, string Email, string DisplayName, string? AvatarUrl);
