// Generated by GitHub Copilot
using EventSync.Api.Common.Exceptions;
using EventSync.Api.Features.Events.Common;
using EventSync.Api.Features.RSVPs.Common;
using MediatR;

namespace EventSync.Api.Features.RSVPs.GetPublicEvent;

/// <summary>
/// Query: load the public-facing event projection for a guest visiting an invite URL.
/// </summary>
/// <param name="Token">URL-safe invite token.</param>
public sealed record GetPublicEventQuery(string Token) : IRequest<PublicEventDto>;

/// <summary>Handler for <see cref="GetPublicEventQuery"/>.</summary>
public sealed class GetPublicEventHandler : IRequestHandler<GetPublicEventQuery, PublicEventDto>
{
    private readonly IInviteValidationService _inviteValidation;

    /// <summary>Initializes a new instance of <see cref="GetPublicEventHandler"/>.</summary>
    public GetPublicEventHandler(IInviteValidationService inviteValidation)
    {
        _inviteValidation = inviteValidation;
    }

    /// <inheritdoc/>
    /// <exception cref="InvalidInviteException">Thrown when the token is unknown, deactivated, expired, exhausted, or the event is gone.</exception>
    public async Task<PublicEventDto> Handle(GetPublicEventQuery request, CancellationToken cancellationToken)
    {
        var (link, error) = await _inviteValidation.ValidateTokenAsync(
            request.Token,
            cancellationToken: cancellationToken);
        if (link is null)
        {
            throw new InvalidInviteException(error ?? "Invite link not found");
        }

        var ev = link.Event;

        // Privacy: only DisplayName, never Organizer.Email.
        return new PublicEventDto(
            ev.Title,
            ev.Description,
            new EventTypeDto(ev.EventType.Id, ev.EventType.Name, ev.EventType.Icon),
            ev.Location,
            ev.IsVirtual,
            ev.StartDate,
            ev.EndDate,
            ev.Organizer.DisplayName,
            ev.CoverImageUrl,
            ev.IsCancelled);
    }
}
