// Generated by GitHub Copilot
using EventSync.Api.Common.Exceptions;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.Events.Common;
using EventSync.Api.Features.RSVPs.Common;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.RSVPs.GetPublicEvent;

/// <summary>
/// Query: load the public-facing event projection for a guest visiting an invite URL.
/// </summary>
/// <param name="Token">URL-safe invite token.</param>
public sealed record GetPublicEventQuery(string Token) : IRequest<PublicEventDto>;

/// <summary>Handler for <see cref="GetPublicEventQuery"/>.</summary>
public sealed class GetPublicEventHandler : IRequestHandler<GetPublicEventQuery, PublicEventDto>
{
    private readonly IInviteValidationService _inviteValidation;
    private readonly AppDbContext _dbContext;

    /// <summary>Initializes a new instance of <see cref="GetPublicEventHandler"/>.</summary>
    public GetPublicEventHandler(IInviteValidationService inviteValidation, AppDbContext dbContext)
    {
        _inviteValidation = inviteValidation;
        _dbContext = dbContext;
    }

    /// <inheritdoc/>
    /// <exception cref="InvalidInviteException">Thrown when the token is unknown, deactivated, expired, exhausted, or the event is gone.</exception>
    public async Task<PublicEventDto> Handle(GetPublicEventQuery request, CancellationToken cancellationToken)
    {
        var (link, error) = await _inviteValidation.ValidateTokenAsync(
            request.Token,
            cancellationToken: cancellationToken);
        if (link is null)
        {
            throw new InvalidInviteException(error ?? "Invite link not found");
        }

        var ev = link.Event;

        // Availability: compute remaining seats from the current "Going" count so the
        // public page can show "X spots left" / "Event full". Only queried for capped
        // events; uncapped events report null (unlimited) and are never "full".
        int? spotsRemaining = null;
        var isFull = false;
        if (ev.MaxAttendees is int maxAttendees)
        {
            var goingCount = await _dbContext.Rsvps
                .AsNoTracking()
                .CountAsync(r => r.EventId == ev.Id && r.Status == RsvpStatus.Going, cancellationToken);
            var remaining = maxAttendees - goingCount;
            spotsRemaining = remaining > 0 ? remaining : 0;
            isFull = remaining <= 0;
        }

        // Privacy: only the organizer name set on the event, never email.
        return new PublicEventDto(
            ev.Title,
            ev.Description,
            new EventTypeDto(ev.EventType.Id, ev.EventType.Name, ev.EventType.Icon),
            ev.Location,
            ev.IsVirtual,
            ev.StartDate,
            ev.EndDate,
            ev.OrganizerName,
            ev.CoverImageUrl,
            ev.IsCancelled,
            ev.MaxAttendees,
            spotsRemaining,
            isFull);
    }
}
