// Generated by GitHub Copilot
using EventSync.Api.Common.Services;
using EventSync.Api.Data;
using EventSync.Api.Data.Entities;
using EventSync.Api.Features.Events.Common;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace EventSync.Api.Features.RSVPs.GetRsvpSummary;

/// <summary>
/// Query: aggregate RSVP counts (Going / NotGoing / Maybe / Total) for an event.
/// </summary>
/// <param name="EventId">Owning event identifier.</param>
public sealed record GetRsvpSummaryQuery(Guid EventId) : IRequest<RsvpSummaryDto>;

/// <summary>Handler for <see cref="GetRsvpSummaryQuery"/>.</summary>
public sealed class GetRsvpSummaryHandler : IRequestHandler<GetRsvpSummaryQuery, RsvpSummaryDto>
{
    private readonly AppDbContext _dbContext;
    private readonly ICurrentUserService _currentUser;

    /// <summary>Initializes a new instance of <see cref="GetRsvpSummaryHandler"/>.</summary>
    public GetRsvpSummaryHandler(AppDbContext dbContext, ICurrentUserService currentUser)
    {
        _dbContext = dbContext;
        _currentUser = currentUser;
    }

    /// <inheritdoc/>
    /// <exception cref="KeyNotFoundException">Event does not exist.</exception>
    /// <exception cref="UnauthorizedAccessException">Event is owned by another user.</exception>
    public async Task<RsvpSummaryDto> Handle(GetRsvpSummaryQuery request, CancellationToken cancellationToken)
    {
        var user = await _currentUser.GetOrCreateUserAsync(cancellationToken);

        var ev = await _dbContext.Events
            .AsNoTracking()
            .FirstOrDefaultAsync(e => e.Id == request.EventId, cancellationToken)
            ?? throw new KeyNotFoundException($"Event {request.EventId} not found.");

        if (ev.OrganizerId != user.Id)
        {
            throw new UnauthorizedAccessException("You do not have access to this event's RSVPs.");
        }

        var counts = await _dbContext.Rsvps
            .AsNoTracking()
            .Where(r => r.EventId == ev.Id)
            .GroupBy(r => r.Status)
            .Select(g => new { Status = g.Key, Count = g.Count() })
            .ToListAsync(cancellationToken);

        var going = counts.FirstOrDefault(c => c.Status == RsvpStatus.Going)?.Count ?? 0;
        var notGoing = counts.FirstOrDefault(c => c.Status == RsvpStatus.NotGoing)?.Count ?? 0;
        var maybe = counts.FirstOrDefault(c => c.Status == RsvpStatus.Maybe)?.Count ?? 0;

        return new RsvpSummaryDto(going, notGoing, maybe, going + notGoing + maybe);
    }
}
