// Generated by GitHub Copilot
using EventSync.Api.Features.Events.Common;
using EventSync.Api.Features.EventTypes.GetEventTypes;
using MediatR;

namespace EventSync.Api.Features.EventTypes;

/// <summary>
/// Maps EventType-feature minimal-API endpoints onto the application route table.
/// </summary>
public static class EventTypeEndpoints
{
    /// <summary>
    /// Registers <c>/api/v1/event-types</c> endpoints.
    /// </summary>
    /// <param name="app">The application route builder.</param>
    /// <returns>The supplied <paramref name="app"/> for chaining.</returns>
    public static IEndpointRouteBuilder MapEventTypeEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/v1/event-types")
            .WithTags("EventTypes")
            .RequireAuthorization();

        group.MapGet("/", async (IMediator mediator, CancellationToken ct) =>
        {
            var types = await mediator.Send(new GetEventTypesQuery(), ct);
            return Results.Ok(types);
        })
        .WithName("GetEventTypes")
        .WithSummary("List all available event types ordered by name.")
        .Produces<IReadOnlyList<EventTypeDto>>(StatusCodes.Status200OK)
        .Produces(StatusCodes.Status401Unauthorized);

        return app;
    }
}
