// Generated by GitHub Copilot
import { DatePipe } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  Signal,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { toObservable, toSignal } from '@angular/core/rxjs-interop';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { catchError, debounceTime, distinctUntilChanged, of, startWith, switchMap } from 'rxjs';

import { EventService } from '../../../core/api/event.service';
import type {
  EventListParams,
  EventSummaryDto,
  EventTypeDto,
} from '../../../core/models/event.model';
import type { PagedResult } from '../../../core/models/paged-result.model';

type SortBy = 'date' | 'title';
type SortDir = 'asc' | 'desc';

/**
 * Lists the current user's events with debounced search, type filter, sort
 * toggle and paging. Renders a desktop table and a stacked mobile card view.
 *
 * Accessibility:
 * - Filter controls have associated `<label>` elements.
 * - Action icon buttons carry `aria-label`s.
 * - Table uses semantic `<thead>` / `<th scope="col">` markup.
 * - Status badges expose state via text (not colour alone).
 */
@Component({
  selector: 'app-event-list',
  imports: [ReactiveFormsModule, RouterLink, DatePipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './event-list.component.html',
})
export class EventListComponent {
  private readonly eventService = inject(EventService);

  protected readonly searchControl = new FormControl<string>('', { nonNullable: true });
  protected readonly eventTypeFilter = signal<number | null>(null);
  protected readonly sortBy = signal<SortBy>('date');
  protected readonly sortDir = signal<SortDir>('asc');
  protected readonly currentPage = signal(1);
  protected readonly pageSize = signal(10);

  /** Debounced search value mirrored into a signal. */
  private readonly searchValue: Signal<string> = toSignal(
    this.searchControl.valueChanges.pipe(
      debounceTime(300),
      distinctUntilChanged(),
      startWith(''),
    ),
    { initialValue: '' },
  );

  /** Combined query parameters. */
  protected readonly params = computed<EventListParams>(() => ({
    page: this.currentPage(),
    pageSize: this.pageSize(),
    search: this.searchValue() || null,
    typeId: this.eventTypeFilter(),
    sortBy: this.sortBy(),
    sortDir: this.sortDir(),
  }));

  protected readonly eventTypes = this.eventService.eventTypes;

  /** Reactive paged result driven by `params()`. */
  private readonly result = toSignal(
    toObservable(this.params).pipe(
      switchMap((p) =>
        this.eventService.getEvents(p).pipe(
          catchError(() => of(null as PagedResult<EventSummaryDto> | null)),
        ),
      ),
    ),
    { initialValue: null as PagedResult<EventSummaryDto> | null },
  );

  protected readonly events = computed(() => this.result()?.items ?? []);
  protected readonly totalPages = computed(() => this.result()?.totalPages ?? 0);
  protected readonly totalCount = computed(() => this.result()?.totalCount ?? 0);
  protected readonly loading = this.eventService.loading;
  protected readonly error = this.eventService.error;

  /** Reset to page 1 when filter/search/sort change (without depending on currentPage). */
  // eslint-disable-next-line @typescript-eslint/no-unused-private-class-members
  private readonly resetPageOnFilterChange = effect(() => {
    this.searchValue();
    this.eventTypeFilter();
    this.sortBy();
    this.sortDir();
    queueMicrotask(() => this.currentPage.set(1));
  });

  constructor() {
    this.eventService.getEventTypes().subscribe({ error: () => undefined });
  }

  protected toggleSort(column: SortBy): void {
    if (this.sortBy() === column) {
      this.sortDir.update((d) => (d === 'asc' ? 'desc' : 'asc'));
    } else {
      this.sortBy.set(column);
      this.sortDir.set('asc');
    }
  }

  protected onTypeFilterChange(value: string): void {
    if (value === '') {
      this.eventTypeFilter.set(null);
      return;
    }
    const parsed = Number(value);
    this.eventTypeFilter.set(Number.isNaN(parsed) ? null : parsed);
  }

  protected goToPage(page: number): void {
    if (page < 1 || (this.totalPages() > 0 && page > this.totalPages())) return;
    this.currentPage.set(page);
  }

  protected onDelete(item: EventSummaryDto): void {
    const ok = confirm(`Delete "${item.title}"? This cannot be undone.`);
    if (!ok) return;
    this.eventService.deleteEvent(item.id).subscribe({
      next: () =>
        this.eventService.getEvents(this.params()).subscribe({ error: () => undefined }),
    });
  }

  protected statusOf(item: EventSummaryDto): 'cancelled' | 'past' | 'upcoming' {
    if (item.isCancelled) return 'cancelled';
    return new Date(item.startDate).getTime() < Date.now() ? 'past' : 'upcoming';
  }

  protected trackById = (_: number, item: EventSummaryDto): string => item.id;
  protected trackTypeById = (_: number, item: EventTypeDto): number => item.id;
}
