// Generated by GitHub Copilot
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';

import { ToastService, type ToastType } from '../../services/toast.service';

/**
 * Renders the global toast queue in a fixed corner of the viewport.
 *
 * Layout:
 * - Bottom-right on `sm:` and up.
 * - Full-width bottom strip on mobile (`<sm:`) so toasts remain reachable.
 *
 * Accessibility:
 * - Each toast container element is `role="status"` + `aria-live="polite"`.
 * - The dismiss button has an `aria-label` so screen readers announce intent.
 * - `tabindex="-1"` on the wrapper prevents focus theft; users dismiss via
 *   either the explicit close button or by waiting for the auto-timer.
 */
@Component({
  selector: 'app-toast-container',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './toast-container.component.html',
  styleUrl: './toast-container.component.css',
})
export class ToastContainerComponent {
  private readonly toastService = inject(ToastService);

  protected readonly toasts = this.toastService.toasts;

  /** Reactive style + iconography per toast type. */
  protected readonly styles = computed(() => {
    const map: Record<ToastType, { container: string; icon: string; label: string }> = {
      success: {
        container: 'bg-emerald-600 text-white',
        icon: '\u2713',
        label: 'Success',
      },
      error: {
        container: 'bg-rose-600 text-white',
        icon: '\u2715',
        label: 'Error',
      },
      info: {
        container: 'bg-slate-800 text-white',
        icon: '\u2139',
        label: 'Information',
      },
    };
    return map;
  });

  /** Dismiss the toast with the given id. */
  protected dismiss(id: string): void {
    this.toastService.dismiss(id);
  }
}
