// Generated by GitHub Copilot
using FluentValidation;
using MediatR;

namespace EventSync.Api.Common.Behaviors;

/// <summary>
/// MediatR pipeline behavior that runs every <see cref="IValidator{T}"/> registered for
/// the incoming request. Throws <see cref="ValidationException"/> with all collected
/// failures when validation fails.
/// </summary>
/// <remarks>
/// Security: input validation is performed at the application boundary
/// (handler entry) — defense-in-depth on top of FluentValidation's auto-validation.
/// The thrown exception is converted into an HTTP 400 problem-details response by
/// the global exception handler added in Phase 5.
/// </remarks>
/// <typeparam name="TRequest">The MediatR request type.</typeparam>
/// <typeparam name="TResponse">The handler response type.</typeparam>
public sealed class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : notnull
{
    private readonly IEnumerable<IValidator<TRequest>> _validators;

    /// <summary>
    /// Initializes a new instance of <see cref="ValidationBehavior{TRequest, TResponse}"/>.
    /// </summary>
    /// <param name="validators">All validators registered for <typeparamref name="TRequest"/>.</param>
    public ValidationBehavior(IEnumerable<IValidator<TRequest>> validators)
    {
        _validators = validators;
    }

    /// <inheritdoc/>
    public async Task<TResponse> Handle(
        TRequest request,
        RequestHandlerDelegate<TResponse> next,
        CancellationToken cancellationToken)
    {
        if (!_validators.Any())
        {
            return await next(cancellationToken);
        }

        var context = new ValidationContext<TRequest>(request);

        var results = await Task.WhenAll(
            _validators.Select(v => v.ValidateAsync(context, cancellationToken)));

        var failures = results
            .Where(r => !r.IsValid)
            .SelectMany(r => r.Errors)
            .ToList();

        if (failures.Count > 0)
        {
            throw new ValidationException(failures);
        }

        return await next(cancellationToken);
    }
}
