// Generated by GitHub Copilot
import { Pipe, PipeTransform } from '@angular/core';

/**
 * Formats a date as a friendly relative string.
 *
 * Examples (relative to {@link RelativeDatePipe.now()} or the supplied `now`):
 * - "in 3 days"
 * - "2 hours ago"
 * - "today at 5:00 PM"
 *
 * The current time is read from a small overridable hook to honour the
 * "do not assume globals are available" guideline — pass an explicit `Date`
 * via the second argument when calling the pipe in tests, e.g.
 * `value | relativeDate: fixedNow`.
 */
@Pipe({ name: 'relativeDate', pure: true })
export class RelativeDatePipe implements PipeTransform {
  /**
   * @param value      A Date or any value parseable by `new Date(value)`.
   * @param now        Optional reference instant. Defaults to `new Date()`.
   * @param locale     Optional BCP-47 locale. Defaults to runtime default.
   */
  transform(
    value: Date | string | number | null | undefined,
    now: Date = RelativeDatePipe.now(),
    locale?: string,
  ): string {
    if (value === null || value === undefined || value === '') {
      return '';
    }
    const target = value instanceof Date ? value : new Date(value);
    if (Number.isNaN(target.getTime())) {
      return '';
    }

    const diffMs = target.getTime() - now.getTime();
    const diffSec = Math.round(diffMs / 1000);
    const absSec = Math.abs(diffSec);

    // "today at H:MM AM/PM" when same calendar day.
    const sameDay =
      target.getFullYear() === now.getFullYear() &&
      target.getMonth() === now.getMonth() &&
      target.getDate() === now.getDate();
    if (sameDay) {
      const time = target.toLocaleTimeString(locale, { hour: 'numeric', minute: '2-digit' });
      return `today at ${time}`;
    }

    const rtf = new Intl.RelativeTimeFormat(locale, { numeric: 'auto' });

    const units: readonly { unit: Intl.RelativeTimeFormatUnit; sec: number }[] = [
      { unit: 'year', sec: 60 * 60 * 24 * 365 },
      { unit: 'month', sec: 60 * 60 * 24 * 30 },
      { unit: 'week', sec: 60 * 60 * 24 * 7 },
      { unit: 'day', sec: 60 * 60 * 24 },
      { unit: 'hour', sec: 60 * 60 },
      { unit: 'minute', sec: 60 },
      { unit: 'second', sec: 1 },
    ];

    for (const { unit, sec } of units) {
      if (absSec >= sec || unit === 'second') {
        const rounded = Math.round(diffSec / sec);
        return rtf.format(rounded, unit);
      }
    }
    return '';
  }

  /** Indirection so tests can stub time. */
  private static now(): Date {
    return new Date();
  }
}
