// Generated by GitHub Copilot
using EventSync.Api.Common.Configuration;
using EventSync.Api.Common.Exceptions;
using EventSync.Api.Features.RSVPs.Common;
using MediatR;
using Microsoft.Extensions.Options;
using QRCoder;

namespace EventSync.Api.Features.InviteLinks.GetInviteQrCode;

/// <summary>
/// Query: render a PNG QR code that encodes the public RSVP URL for an invite token,
/// so an organizer can print or display it for guests to scan.
/// </summary>
/// <param name="Token">URL-safe invite token.</param>
public sealed record GetInviteQrCodeQuery(string Token) : IRequest<InviteQrCode>;

/// <summary>Result of a QR render: a suggested file name and the PNG bytes.</summary>
/// <param name="FileName">Suggested attachment file name (e.g. <c>invite-qr.png</c>).</param>
/// <param name="Png">PNG image bytes.</param>
public sealed record InviteQrCode(string FileName, byte[] Png);

/// <summary>Handler for <see cref="GetInviteQrCodeQuery"/>.</summary>
public sealed class GetInviteQrCodeHandler : IRequestHandler<GetInviteQrCodeQuery, InviteQrCode>
{
    private const int PixelsPerModule = 10;

    private readonly IInviteValidationService _inviteValidation;
    private readonly FrontendOptions _frontend;

    /// <summary>Initializes a new instance of <see cref="GetInviteQrCodeHandler"/>.</summary>
    public GetInviteQrCodeHandler(
        IInviteValidationService inviteValidation,
        IOptions<FrontendOptions> frontendOptions)
    {
        _inviteValidation = inviteValidation;
        _frontend = frontendOptions.Value;
    }

    /// <inheritdoc/>
    /// <exception cref="InvalidInviteException">Token is unknown, deactivated, expired, exhausted, or the event is gone.</exception>
    public async Task<InviteQrCode> Handle(GetInviteQrCodeQuery request, CancellationToken cancellationToken)
    {
        var (link, error) = await _inviteValidation.ValidateTokenAsync(
            request.Token,
            cancellationToken: cancellationToken);
        if (link is null)
        {
            throw new InvalidInviteException(error ?? "Invite link not found");
        }

        // Encode the exact public RSVP URL the copy-link action produces
        // (see CreateInviteLinkHandler.ToDto): "{baseUrl}/rsvp/{token}".
        var rsvpUrl = $"{_frontend.BaseUrl.TrimEnd('/')}/rsvp/{link.Token}";

        // PngByteQRCode is pure-managed (no System.Drawing) so it runs on Linux/Azure.
        using var generator = new QRCodeGenerator();
        using var data = generator.CreateQrCode(rsvpUrl, QRCodeGenerator.ECCLevel.M);
        var png = new PngByteQRCode(data).GetGraphic(PixelsPerModule);

        return new InviteQrCode("invite-qr.png", png);
    }
}
